apiVersion: v1
kind: ServiceAccount
metadata:
  name: neutron-db-sync
  namespace: openstack
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: neutron
    meta.helm.sh/release-namespace: openstack
imagePullSecrets:
  - name: telemetry-harbor-push
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: neutron-server
  namespace: openstack
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: neutron
    meta.helm.sh/release-namespace: openstack
imagePullSecrets:
  - name: telemetry-harbor-push
