conf:
    horizon:
        local_settings:
            config:
                allowed_hosts:
                    - ENC[AES256_GCM,data:FP4RfTNSxRFvWo/K49Le2/KzPQ==,iv:pim9iQsUfdm0RSiO0Z+zdcBtiWDtTiAlItIwpNcKz+Q=,tag:Tj5gSVHTlmPSLKgOLQzEEw==,type:str]
                csrf_cookie_secure: ENC[AES256_GCM,data:vJaZHw==,iv:IplOUap8THO3P+pov+AVjNTmXoHVk0UsttVd8cxAq5w=,tag:f0v9dfTH8LW/Ek0EjjdTWw==,type:str]
                csrf_trusted_origins:
                    - ENC[AES256_GCM,data:4jEGHKDinVVnLhl8HiuNCDkn+8/h/UnNOIyJ,iv:7YEggqZr767FgEBQOuwrCR1R4UaGlwtjYJTZpi8EpgA=,tag:YhQtYQm5UStdEmloWFFxgw==,type:str]
                endpoint_type: ENC[AES256_GCM,data:nIDqIB7V5RkAfUU=,iv:oY273UWb3OITbTKqXRoYUQX/yYGke1sriHPz0LGVxKw=,tag:l7TYTVBValO8dwNkjXkypw==,type:str]
                horizon_secret_key: ENC[AES256_GCM,data:svbpFwq1ldEUhoAjTX10DeyyXAPmA4R6qrmNLJAF7CIeeoOXa6f9g3Y/y8fqs8vjHsMFg3NvJeWNSmpIPkzewRHgbR0tmlTPRBmJE9DpyiOBDvILb7JQ1uSZTi18Knad,iv:OWw+kF5H0Gpf5osdXcsJXdBp8I9lkKgIbcbqRM66mzI=,tag:e71S7DzIEHJrRi7GBBdlUQ==,type:str]
                raw:
                    FORCE_SCRIPT_NAME: ENC[AES256_GCM,data:bUWfbj7VPM0=,iv:tp5otfxTzLrL0GiGz030x5hV5TNP5f1IWyg4Rwu+bKQ=,tag:DtiYE66Qi+PV0pnyKH2zuw==,type:str]
                    LOGIN_REDIRECT_URL: ENC[AES256_GCM,data:h9FUOwn21je8,iv:7owde79BRFJnbPeJjp2mDHJGObF7itCs+4PfN7zHNfw=,tag:ABE6Tlq4wryRhaBC+IMG0g==,type:str]
                    LOGIN_URL: ENC[AES256_GCM,data:MLltMyB2Vj7ovGCSA/wdVzlKZM8=,iv:X69gzod0Gh1GtCc5zMFLd50PNlBxu6uR4qoTdZPhqow=,tag:XLnzgv8k64yIe8RLSr8OVQ==,type:str]
                    LOGOUT_URL: ENC[AES256_GCM,data:qTJLqimzdt6uSrMm56pwt7IRGa1J,iv:7H6EkWc11djdtzJkB/xJHA+x7ZYpGTR/4577QQiXiak=,tag:TugZJ+sazT0Y1KY9lB/DCw==,type:str]
                    STATIC_URL: ENC[AES256_GCM,data:r1UCqoz7HRJpmNo2yiDzfA==,iv:6OKIb/OiAHd3Ev/Ty4xolBxcU+FmH/KUtEneQLCx1fo=,tag:aqU9R83oJHEk1rlWTbZKsQ==,type:str]
                    WEBROOT: ENC[AES256_GCM,data:qCDH61dhpPAh,iv:XTSkMIRpXCQ39uSeOpo0riZHqYj5KE0d0tWKX1foqq8=,tag:qyLiJGmoUUkLOJh/U4Oqww==,type:str]
                    COMPRESS_OFFLINE: ENC[AES256_GCM,data:stKtsu4=,iv:GYMgNQJKhKtvF/YaS7S9tQTjjbLPiJtwd6hQ1PQ3o5c=,tag:ZZRmyfLPb0xCNsuL+5n56g==,type:str]
                secure_proxy_ssl_header: ENC[AES256_GCM,data:maLaLg==,iv:3FgU8cMSzDHSV4zSTlS04IK5dVOqFd79ZpRaG06hlkU=,tag:SR1CUC7wVKQ2t7KdprqdzQ==,type:bool]
                session_cookie_secure: ENC[AES256_GCM,data:dNYFqQ==,iv:rmLj5w1qxnsyJp/k2nZcZrji0yRcNRyrpIR1MADyez8=,tag:TaPKQn9RzljLkn4U9DrUUg==,type:str]
                use_ssl: ENC[AES256_GCM,data:HWdMzw==,iv:/ZXIuV1QL+k96lpdXdCLd+Dtuav2d72aqH02w55huIU=,tag:RT8yrOeM3OQuLD1YTB7dfw==,type:str]
                auth:
                    sso:
                        enabled: ENC[AES256_GCM,data:VyE2BA==,iv:/RKZuqEwQnvIfnEyo/STcshAcmn58T9I/f/4GOFdZzI=,tag:MbSCdI2j2tEVurLC/+NjWg==,type:bool]
                        initial_choice: ENC[AES256_GCM,data:dxgXQ1FLGWyn6/c=,iv:Pk466CoEO0p+p8aCVZLv2UrqwPaA8q8i4qMiqgy042c=,tag:lo42tRl51JaKjoO/5LCLZg==,type:str]
                        websso_keystone_url: ENC[AES256_GCM,data:Vz9wWuaCdajP9craEwe60yKOzL6TZGpWqnCBxJbod/PERIqrlc31,iv:LbKo8E+FQF7FS4vJrdBYoNRuwHqWD6WUo1Iu6mdLkqY=,tag:lQ48dyvun1nr8uKNiu0aAw==,type:str]
                    idp_mapping:
                        - name: ENC[AES256_GCM,data:n2MdM1gCtR7mzO5x,iv:wsSnrCHj7+cFmF22N44GshzG4gQwmaKvWatwum+zrDY=,tag:Qjur605cv3aWUBSgWTwpwQ==,type:str]
                          label: ENC[AES256_GCM,data:wiw5fOudEbIKDmaeU0w1dA==,iv:tUzltefNQKwnGr3pZFdE+1J0luxBzhD0pXilE4Cz/Bo=,tag:e/aOi8t7pOjV1O4FnyMVKw==,type:str]
                          idp: ENC[AES256_GCM,data:uKGD0JhzpsP5Deab,iv:cgcDLkppyk7XGiI7+Q8UKT5MOesaIXTyzNnAWyqG2FU=,tag:UdFrcl6mj9faqpP0HAWpog==,type:str]
                          protocol: ENC[AES256_GCM,data:6jsJ4sFK,iv:Ma+FY2N3kGrwItoiyofrIxsKqFKoNZR2Ie5VUaj2kps=,tag:ktl+c3Cki9N165y/JyygrA==,type:str]
                session_engine: ENC[AES256_GCM,data:arOzBofb1xz1q5hlcV4eP7zWsPJT+haHggDAMGVP0mKr1TrdwPzfAvUl4QRQ0wg=,iv:kynsgT/slpiRE/U+iOc+g1rrDSBO+0llXnP56RAGglg=,tag:xmKw8s6kDyjLdclLbZTP2Q==,type:str]
endpoints:
    dashboard:
        host_fqdn_override:
            public:
                host: ENC[AES256_GCM,data:x0dOpf+ETrWI2gfNBt2mGQnntQ==,iv:tePOqpnOTjGloZvgLCgxhJZKMbxaQEwWQh9BpRSuGzs=,tag:MjhbpEGIOBqgF3E5lDlClQ==,type:str]
        port:
            web:
                public: ENC[AES256_GCM,data:Pu/9,iv:5hyeUjbRuQBlzpfM1SnT5DuecYLXUHBV/7dVAYu4jx0=,tag:k9sAH9NvXdvNUPoVaENflw==,type:int]
        scheme:
            public: ENC[AES256_GCM,data:dWXlFI0=,iv:dVQqKuxrXz2V3EQ7xKWVXiH/5SMXkXhYpR6SFFyTroY=,tag:elPl0C6iULMxSfWW/uTd5Q==,type:str]
    identity:
        auth:
            admin:
                password: ENC[AES256_GCM,data:g5Kkmg6r3NML0I4OHq2NVPYR3pvH1ZxeVtKfJFh4Yv+tBQoVU04XYiWKG8Q0eQFUTtCumUIkbPlVoTjdDy+P1Q==,iv:vXGq3ScBgFfni+FguWlNr27f3DnRooN48nEkcVjq6jk=,tag:iyEJSfZIghL61AdtGdxquw==,type:str]
                project_name: ENC[AES256_GCM,data:rwvrCvw=,iv:dgcrj2iGee4zntZubqdJiHOMuacMroSrZcQYOBIBWII=,tag:hWH4kXELeAMcYDxcoqjIAA==,type:str]
                region_name: ENC[AES256_GCM,data:ahyDn04CDAup,iv:ayLkFry10R/LfPGLqWOKjwXR+K9r+OAWwqAbN7fC3c0=,tag:5Ya1nENQAnWQEonFlwkiJA==,type:str]
    oslo_db:
        auth:
            admin:
                password: ENC[AES256_GCM,data:iiQ4t2mGL5yR4SVyyoGPwU/fdItzTBWS0urTwpn1WQBs8+HXFoykRgwtmyOZfikAGH9XAJ2NbkW5uQC/9c4dBg==,iv:cSmplV3KRHxnF989mVsqzhJv658Y4v5Y/Kx69IxEPds=,tag:9EA2JbdPyXVMU135IaA3yQ==,type:str]
            horizon:
                password: ENC[AES256_GCM,data:+qBt25NYY5MlLYsB4GKx3aWHs///JQ2ggns9z6dhUOtqX3LzSOFK+35/pNb447wE,iv:EIseMMfKrtatUNyQAMIdVSXyNYLllhHYFlbrRsOeQxE=,tag:ecAOYj5qNs1UUkJowLTJHA==,type:str]
images:
    tags:
        db_drop: ENC[AES256_GCM,data:H7Aa3IJus2iAKvxcIRymOOkGXeMXxQ6rPTeMc4wWqqo8JwwtSfaqTH/riu+eaUcCPcjDmz4j,iv:WPNZIqkPayM1Qsw55uVYBKqDmhqRdXS0taJDjXamd3M=,tag:BpfGS2X+fDOToXZ2yRP7yA==,type:str]
        db_init: ENC[AES256_GCM,data:l3qxJTQMOoCJEOtb6IdVM5vs/hUN29RbYiFETG8N5hYGFa5+JGPl9YpNdKNc4D1cMTmrjWWg,iv:QmzCVXPPN5cMpKbkdvNxkdUKBvVXaQBwjSuu6UkiTiQ=,tag:VuKPamzkkvwEu1ZLIlFG3w==,type:str]
        horizon: ENC[AES256_GCM,data:+V+ImHYzP0cGIzWA8SWW9NPWLgwIww0qMGDvDAKsldTFNZ0PKlEYmgsyVYmxthS/zZ71aEm5Qd9UDw28rCZgLhBMI1eAHsFgH40vLal4OxTTUjs+Rhv/0PNfPCba72wnStsnZVXujVao8WpWcGH9yw==,iv:7/aX54J0+Fu/MZ6y8yRnlYramL9/leG2+9lUmsB0LSU=,tag:9XfIOf66nO6wocEi6tt5LQ==,type:str]
        horizon_db_sync: ENC[AES256_GCM,data:aghfWQgnFQcCgv9WOTH08r02a04b4nDVYm2L/ktz4keDKof7VWnwpJYjp3rF,iv:xMQLnIz0ECRUepKK03IZatjYf82xS2l2tLLQkdkI3HI=,tag:QJdiRvCgLAxFIDy6vNK2qQ==,type:str]
manifests:
    ingress_api: ENC[AES256_GCM,data:JLOFl6w=,iv:MIUK5Tu8/78ybzIN+3fzPMW5kOb0n6b77+A7uexCDuc=,tag:UVnXNLJrhcfsWZzAmhaJWg==,type:bool]
    service_ingress: ENC[AES256_GCM,data:Fsp2ZN0=,iv:J1oFD9wrtH29vzpqPk7ldMh4E8d/zBTzd5UU/UgmtPg=,tag:GaG42S7G/fUE6bJ1/RPnTw==,type:bool]
pod:
    lifecycle:
        disruption_budget:
            horizon:
                min_available: ENC[AES256_GCM,data:iw==,iv:tmOWku2GFCoL5eC7E6uVi7+RYMN4LRxTIUcIlcia14g=,tag:l9K3yvGxlUu1pXK+YfItcQ==,type:int]
    replicas:
        server: ENC[AES256_GCM,data:EA==,iv:QS1VpxrsvT4Jc3nHPUY8TptVbxdO9mXactYVyz5us7g=,tag:CLAwybdeU6ansyzOdXYOsg==,type:int]
    tolerations:
        horizon:
            enabled: ENC[AES256_GCM,data:cUzTKg==,iv:cMVd1rZae85Pjxi96ZdCyXmfbqf8EzTUrVH5LIZ8siE=,tag:buH9fhKwc+Ok6xdZKBEZ8w==,type:bool]
    image_pull_secrets:
        horizon:
            - name: ENC[AES256_GCM,data:G64Von2ioZRg4jSLexvGkxD665qo,iv:nmF73ugmiYehqgLr3hhJuz0smSOLioGPO40OVGmqjUc=,tag:qZvJ9b4YLp45GeaAz8vx6g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQeGpwSHJXUjlSeDFKd00v
            eDdZZkduSU1POTl0WkQvK3U3ME4rVmxmQkRNCmxQNk8ralBiODBjV3BvQ0N4M2hq
            algvTUxaRVgxU0RyL3oxRjlKaU1GRTQKLS0tIEkxcnF6S1dvc1pmL1pRNUR4VWsr
            Q1UyWWNkQ041U1FQeTFvV1A5aTlIajgKIHXL5BBkVC/Xgj8xg4r8Jm37nqilQ0N9
            k2oCZJgJ/xHuZbQ5KU8MXwNKS5f2DtW2RtVqJk+tRpjdPtMXGDceeQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cjaxalqu6gs9mev9w0u537793ql5t0gy3a6d9qn0265s49k9ss6q7flh4j
    lastmodified: "2026-07-26T16:46:50Z"
    mac: ENC[AES256_GCM,data:ioa5rR9yqqWMEzNmRnDpsX8JDaJmbZs5MzuNCrhSlny0tRVAUsw+v13QOaepiuAAUjeeixTIts1+P3EtZ3vD/Gl0BaC7S6WOb30e5oYc2QCG0FGR1tlVpd0QTry61Klh4tu77rlKVPtFBFmWxcs+6Bb7CbcmjIBnOrQWWmCr/a8=,iv:CC+0NoEF4Esm672dS0GVbpR7EjetDbFIiBslzewdzf0=,tag:287F3SJEn1eWNJfgszWtsA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
