conf:
    horizon:
        local_settings:
            config:
                allowed_hosts:
                    - ENC[AES256_GCM,data:pXbFqjod+6e4G+hP6Y+kjaQ3PA==,iv:VWLGll9ZLMCOk4VBnHSPEIqSrRCmOnlGtgX8pYcmIzI=,tag:Xw3slBkqrjlpZfU3jR1ITA==,type:str]
                csrf_cookie_secure: ENC[AES256_GCM,data:3KGfMg==,iv:c3bVbiGcWllmiSFh7feHECeIgXsR6jsc0o0FMJA4sAQ=,tag:sgOJ2Oujdnr+Ui9NE7GJgw==,type:str]
                csrf_trusted_origins:
                    - ENC[AES256_GCM,data:erTpLkn0ZsVl1VzESgbtmMP5HkY4j83QLmex,iv:lFR0OG2j4WKfK6rsUOEGtG4sPTyzaIUyQvvAnnJSIaE=,tag:j+fgQOfbigbcIJNm+Ts76Q==,type:str]
                endpoint_type: ENC[AES256_GCM,data:gcRLsR5wNmSJ7gk=,iv:CQSsC8X2gHevEmalrYlbtUoLMOga4OQXnwL+dWJGZzs=,tag:LwoQ9YplG1J7ypz+v4T1Og==,type:str]
                horizon_secret_key: ENC[AES256_GCM,data:Df/RlBLnOzEJg3Cp+J8dS8pnybHALohfwGEVNh6492j8/AoaY1Av1McxfC1VuYfYOiOGaCjq1Gq0vrw03Y+RV8s1B//SozP7HCrX5OLGdqicyyLkFxsgHhjmLlio6RKW,iv:k9Sv8GDcPDLx8NI/cgglfvawakeFdzD9BrjJ2I6Waj0=,tag:c2gw5qSwxSL6bpz7P6T8Fw==,type:str]
                raw:
                    FORCE_SCRIPT_NAME: ENC[AES256_GCM,data:+1cISI2zAAI=,iv:TwhtZva3l5oR1ROcr87ZK7VmtrDIHCjpNpbF+5/Ual8=,tag:iqfR9UIJJXHdQx51fYYGbA==,type:str]
                    LOGIN_REDIRECT_URL: ENC[AES256_GCM,data:9zVlSEN2ulkp,iv:uION73YtgaYiD/iVSVAKN3QDFHsXEvDNk3lzIdzaNwo=,tag:prSkSxY1NzdvMHoqdtsByQ==,type:str]
                    LOGIN_URL: ENC[AES256_GCM,data:GkwlkoVgF0Wk3h7yX+6td9g4JZU=,iv:f1aHc+CvGVtCeEDsAK+PyT5LFR60SFVRZH+n9zfj5TE=,tag:CN3B/9na1IDU+MokapJPkQ==,type:str]
                    LOGOUT_URL: ENC[AES256_GCM,data:v3rw9feOkeL+yJ3AmzG0wiQIrLr6,iv:fLWlc59+WTChc7FupTNBFkSXDNCLK0zLEIsuNIk2a1U=,tag:QfRvbtJ48MKMS4gy7FYl2Q==,type:str]
                    STATIC_URL: ENC[AES256_GCM,data:ogdTPWjKVhm1CIISjrcWnw==,iv:CoQWWYR0PIZJJEt5hQdV/J4Sb9xHRwj7Wc164Lt96BE=,tag:wrK9nOkCXx+8bMaF4b1l2A==,type:str]
                    WEBROOT: ENC[AES256_GCM,data:8R61bX+55TIj,iv:g0lgQbA5G3NUzQfG5GqJV4MQxhj1P/HmiwCAfzvSCnk=,tag:McCYNvnypRN40l5JYRK0JA==,type:str]
                secure_proxy_ssl_header: ENC[AES256_GCM,data:y4q+Dg==,iv:bPSB1Wyfs8zGnbOyl5k/1RojjBRn/p3imCqQAqz+yxw=,tag:C9ITDFU12QP8QzfN5snr/g==,type:bool]
                session_cookie_secure: ENC[AES256_GCM,data:fnXEyA==,iv:uGJMTzG2A72tSrsiKLE8+KznkKZZRDLJ91bF6dW5gSc=,tag:r2GvlKRfzyA1N2V8tSAStw==,type:str]
                use_ssl: ENC[AES256_GCM,data:dWR9FQ==,iv:owVKh6A49h8007Lx+ZNbnqjtKCM9bmkc5RVExdtYUCw=,tag:2+CpkLhmNhRtNv+hL2FRMA==,type:str]
                auth:
                    sso:
                        enabled: ENC[AES256_GCM,data:IZzZzQ==,iv:sskDkmnhj3gH003B0y20HFkD1+Rb8Guj4GD6DfY3i1A=,tag:7351tgJkRNrwJQmeTkNo/Q==,type:bool]
                        initial_choice: ENC[AES256_GCM,data:8xiuviNSSEI68oA=,iv:u1XgOeWax9sali0gOfJTZEJZdKO5OnO/UDlG3u0fADg=,tag:rCBkhjhbwG0+XA0pztbodg==,type:str]
                        websso_keystone_url: ENC[AES256_GCM,data:LJXkrdQpkt2TVYI/jVf7DqJtWTTF/1de1RZVFzav4l/XsBaP77ZZ,iv:xUJiCcOaC6k2YOeXF1Xoy6R3nEIB6aJREN9Nyn1J2PE=,tag:C69kUEzy5OXjjmsfH3bHDg==,type:str]
                    idp_mapping:
                        - name: ENC[AES256_GCM,data:ZMg3eNTdxcbMfNiw,iv:y9pS5y5VKmiPXrPnPbuIDL+oa9+TkLI8ZgVSe+f6/Os=,tag:tDzHFZuDhEVVARfELf7Cag==,type:str]
                          label: ENC[AES256_GCM,data:seMIWixRzLjsazy9pgpp2w==,iv:P+/xGFmoTUVnwhqoqIWBMa2a7ifgNeOAn+slZZpLKGg=,tag:Ed8ThHzrCpLddEKGRZGFHA==,type:str]
                          idp: ENC[AES256_GCM,data:N+XXZReZACr72rjz,iv:KgFkhievAhpZA6vVXjl34lRtYJG37L8gg3OGhvwYFNY=,tag:dh+aVKqFzUGoT874nnhAUA==,type:str]
                          protocol: ENC[AES256_GCM,data:uPc4Jx/G,iv:aYjsqijmHBdQ8eB4WS07mPA2y1l0OKajQcHS0fvRXIo=,tag:BnHi6GpEugmffv4XovYRnA==,type:str]
                session_engine: ENC[AES256_GCM,data:Ku1rQl6r/o8ZQR7Qlh8+9uCm3pbeiFeqk7vOew96KTMsFjg=,iv:weP7ou1yAhqtoURdldaPXJyC/U85ZBCpkfsMBFhn1vY=,tag:gmQkQIyvHoUx2bZSbAEEDA==,type:str]
                compress_offline: ENC[AES256_GCM,data:8bqbCeo=,iv:Q7O7bhoh7r+1ONooob8RE1Kehb/IHljie3Jdr5RKZ0U=,tag:SojY0SwibSRwTQdH4XbUvw==,type:bool]
endpoints:
    dashboard:
        host_fqdn_override:
            public:
                host: ENC[AES256_GCM,data:/kxscU6FqYuWhULWs7NQlvFMoA==,iv:FWegG57cVTZ6RtQTxiT+XgBpCKg9JCtnVRWnPNUAn4Y=,tag:l0B+9rpypeyWknjWeQM0cQ==,type:str]
        port:
            web:
                public: ENC[AES256_GCM,data:lvrb,iv:jrDWLggQfb4mwRgqolOZNmtH0bU3bxVBlmyOUF2duuQ=,tag:L2e6TcseLnL3hP6qb5h+vg==,type:int]
        scheme:
            public: ENC[AES256_GCM,data:fdxSkgU=,iv:iZwBWWkhuwpYTHovHrlJLddHF9s4wKRGcV03qjVFCPI=,tag:HYqaCFOyPoo72hnmsdBipA==,type:str]
    identity:
        auth:
            admin:
                password: ENC[AES256_GCM,data:lKcx33NLKSWMO25z9wSMbRQtt18bh7zCwExrCZSWPp9pXC7PUGEzsx/31/WvwRb0/ZQCisAcS3Y4PVQ7y/vNDg==,iv:kDd+wAJZYrs4YNgfGs8iOxuzBuH5Q0iyaGbzEkDS/24=,tag:fbLWadtHSqloJ4wFn0R4Yg==,type:str]
                project_name: ENC[AES256_GCM,data:aOEcSaU=,iv:PA32YafGMilFqwydDIg8wPaOclicxSFWuB3FFYoOOQY=,tag:snrutwG8PjAr+CJKqBIomA==,type:str]
                region_name: ENC[AES256_GCM,data:LFLnSDdRXzJh,iv:az9e0D09ptJwynEpbUc0UE7+q5NHbsaFGAUj3S6gkiA=,tag:G1gmE2AhnfVpubz3G5yN7A==,type:str]
    oslo_db:
        auth:
            admin:
                password: ENC[AES256_GCM,data:cOqul+K4WijK2xbBw27Q/5MGpaje9iVWkXnxN+BYCmp0MlalAzumJhOBC8P1eL4t8diDKHEQcuV8MDO+uLQybw==,iv:BPPDioiq/t6naIvV99gWjYsqhi6T6F65D5KVomsx48s=,tag:3vvDY37ZEtzBFjRLZMSaLg==,type:str]
            horizon:
                password: ENC[AES256_GCM,data:iL7vNddhnPvcq0P+QuonVdQEi18CdvgE//F/gsJXOtCKrK0UuxUp9xPRZqm0o22h,iv:ZGxIo7+NO5rLmz4vPHmJFbPfBOyTEUkBHukiXgA6r1M=,tag:OSXORQ5eiy1HXr5NPC7iNg==,type:str]
images:
    tags:
        db_drop: ENC[AES256_GCM,data:agJCB9/7kAU35duafS7JvLSwZ928hqw6jpgZsadLzVbqawTaIi5DvAsppY0ERmY2nNqjWIAh,iv:1DEM9pMLTg+pMzLRiNwZoOqwqFTLMnIqxxhEDbPXvi0=,tag:glq5AQcjeZZI0bKngfXeaw==,type:str]
        db_init: ENC[AES256_GCM,data:1+rwheXJEDxAmlPyld6bzuyRsR4yiEMbhZNOpCOUsvslx9FucGrBaUPvcJro/Yb3yuVud6Rd,iv:54VbUC0fActAcGaVy8nUerosUl9La1Pxgzc2jLIB4WQ=,tag:/BGl7sL9l74vmzSno4ZAyQ==,type:str]
        horizon: ENC[AES256_GCM,data:T48LR82/TFxBRYI/sDQ6XVhHNhiee4fo21MeSpFVG1V4W4ktwA2wefVXCkLzldk63kVq0KGrC5ab6SZnBq9h/PIoZiLGPiYiqKnPDTiETBjquTWSfF4bBdgCQBtXr9Xk82TD6r00OsU7W52tC1fIWw==,iv:iS5jx7l1WEUv42zEVUVcw2eHooR/t9vr76qkeXuLmYU=,tag:GlDxEX5EaYL0dASid9PRGg==,type:str]
        horizon_db_sync: ENC[AES256_GCM,data:eKt3uEICBq9cvacgYIqwd+UHpKuOCHUMzTVbw/CsKc0swlMNTcpTXwRWLhWx,iv:XexJipPozdDFHE4G7ghkGccWQ+R0VB+U3HWPk2WkJFM=,tag:cmHJYD+JkbihnKdMQyKgiQ==,type:str]
manifests:
    ingress_api: ENC[AES256_GCM,data:ZcZfyiU=,iv:cn5JPeYbbYdrVE+MpTLB6dKDeO42t+EVJHhRivvis7E=,tag:qnC3rbyIgEfcs+W6wRvuHg==,type:bool]
    service_ingress: ENC[AES256_GCM,data:2oo8/1A=,iv:u/shvQc3v4KzBdTdAwc5+ePFg85a+IQPZYL+tXlklRA=,tag:4OR/F/RchCfKKPnmIccrug==,type:bool]
pod:
    lifecycle:
        disruption_budget:
            horizon:
                min_available: ENC[AES256_GCM,data:Gw==,iv:Ae2g49EjPx6hAXlMj8hL3e+33zUoEL16tQJn122SVjc=,tag:mLL3DR/KZpiT+IUf/P1RJw==,type:int]
    replicas:
        server: ENC[AES256_GCM,data:QQ==,iv:K8X0AOq+18iesRK4I5M2G3CgrBhDS8+5txGkB5S22O0=,tag:SagxhC3N4gNx15eirzlw9A==,type:int]
    tolerations:
        horizon:
            enabled: ENC[AES256_GCM,data:PdA5Fg==,iv:IobPn+KPoNgvSgMdZmfik8m2EdWNKCw/fFxEfrntg78=,tag:1KLIl7AlmzsO25uM9KO/qQ==,type:bool]
    image_pull_secrets:
        horizon:
            - name: ENC[AES256_GCM,data:erkoUaWvIgYEyQjMQ4oolB67jCBa,iv:KMN6prAgjNwqykqgWmTHNbs18s5u2RhFLI1ztu1RMmY=,tag:J6pkwoC1GWVe346tQlO+Qg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ZHlJeE8zL20vZTAwNWw0
            NkdGMk9ZRVZTcVY3NHBpOTQxVHVwTVhpVHdNCmtjNlZtbm40eC9PTXpXMTRNWG5M
            RUpvaEE3NE1nWUhUR0JqU0p4dEk0RHMKLS0tIEptaWptcy9mcGdhdVg0ZUlnSkF6
            dmdQbEFqM0dHRUczbHlEZFo3RHZOcXMKImmmc8ZJnYxlEZ7KNjiZ1dr8xuxKz/ZP
            WzA/7XAaZmYAcNa3ByaOvHee9I3bXnOuvc+87kVM28NTgdWn8C+0Fg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cjaxalqu6gs9mev9w0u537793ql5t0gy3a6d9qn0265s49k9ss6q7flh4j
    lastmodified: "2026-08-04T03:24:52Z"
    mac: ENC[AES256_GCM,data:fmrQOAbnH4OwzsyxymB9HlbhTsjEZ6vQ14uHziMzJu7OgjYzefkt0lZ19qpEvjKGeJasYjkp4zDFM70ajASxvayCaSrciaQbsnoHu4oBP52m7upBp53eJ0H91N/AsOKvu/tACBE30s8kCkyoMkISphMtxCvNyzeCH3MNyOnC3Ao=,iv:0wYsxyjbhQz5lbTLDP7re4Wwp28AulG0UOEE77zzwK4=,tag:D8DOM+46ZDi7W/c/XLa+uA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
