conf:
    horizon:
        local_settings:
            config:
                allowed_hosts:
                    - ENC[AES256_GCM,data:USuXmXfPn2B2lo2alTHRdLIhAg==,iv:ZXg9GT0cL1CjJhoSQO/7xdxdIxIss39rtkdMR9YtYlM=,tag:78RDgcG5Zd9kw6XeMZX5Tw==,type:str]
                auth:
                    idp_mapping:
                        - idp: ENC[AES256_GCM,data:kHhNGF+xojvLxf2u,iv:HtV059Qu0gfb4uLLhG/eLzr00gPrSnSx51OlwZkCluU=,tag:w/pZ1c0ALamzgGyfvSs5Qg==,type:str]
                          label: ENC[AES256_GCM,data:4wtC8MQ0O//V3wq+cfWyUA==,iv:zBX3dzLt+Au1d+gOK6yOetbf5KBJHBq0osTRCGW9mq0=,tag:w5rKpBCWqzvy6qQcskfjDw==,type:str]
                          name: ENC[AES256_GCM,data:oMTgFiiJgJj/nBMr,iv:bOgFO0iHhDXP3BcLukPYiyJLlERK1WMCu49HyeedgIo=,tag:h0LevUHF8EPM0VpZmnxIdQ==,type:str]
                          protocol: ENC[AES256_GCM,data:OOpupTM/,iv:f66db+31oOGQS7DxDPvR5V7JzfDdyWPRPLfMKfydIsE=,tag:5/CoUhJJ1FTr5+UKpPchIw==,type:str]
                    sso:
                        enabled: ENC[AES256_GCM,data:rIRWpg==,iv:1A41GQD8hnCRIhAn4/aTe491ZwPI7Xo1f+eOzUENXGg=,tag:wY4sDK7HIKFijiMb/vTcuQ==,type:bool]
                        initial_choice: ENC[AES256_GCM,data:ZnS3isZ8rlUm9Gw=,iv:8RTgvs0Lcab2NqE7eXPGv1exP9B37YSgoPelicaK5E8=,tag:1/o9nY3mMHqqlbDG25jfOQ==,type:str]
                        websso_keystone_url: ENC[AES256_GCM,data:9NmtMnVqRgNLF9p5fnEZayk3LLcwOgiSCFa97hOAtLWhK8Igi2G1,iv:g9yX6hTGQd58DZsdiqKjyKHuidjxBCoO3FZDkdiDQAE=,tag:+36FvnogmnfFXWKu9z1giA==,type:str]
                compress_offline: ENC[AES256_GCM,data:wIY09Ac=,iv:yc3XI36i9qpuvfblmO5yMc6xzYBMR/pWbpDI4U/6Fkg=,tag:jXwqVxVjBCjg/cuTLgdCmg==,type:bool]
                csrf_cookie_secure: ENC[AES256_GCM,data:/ubpMQ==,iv:elbtzw0Q5e7l6q96a3Kz8tOshDW5R0D0cHjjy8VApz0=,tag:Y8M7l9obxRsYTBTt/68h0g==,type:str]
                csrf_trusted_origins:
                    - ENC[AES256_GCM,data:hzUWn+EY8I3RqTivV3vEmd9Sk6XpXvWyNWvK,iv:5HxFfl+EQjOa5wW5ZwavmsgP3kIhaWA+aJyM65f9uSM=,tag:TMJdWt/ClHj2euxVCIAKeg==,type:str]
                endpoint_type: ENC[AES256_GCM,data:1JP4q+cUvxcaPOE=,iv:RALPfuCK1MJjh1FZyV2u22y67HiazKw4rGUSnJQ4Gvs=,tag:l5jmJkfWneqgD3r5UGdnQw==,type:str]
                horizon_secret_key: ENC[AES256_GCM,data:MLNyw8xhtJKi9seCaeXrscXa88DEBJNUPnQSQWWrmNWrPzcwth3cCseo+StQFOoX+N9oXxSXtszXWum/IulayA+1Sypb0U1lps1mIP+czsqUM09r40UPdyQD04vcYuKj,iv:7byt1R4wNlKHkU9BRl9aH7RGyUGq1GlkA8r9VITksWE=,tag:nQ50mvmzyolHM5t7SRGxbg==,type:str]
                openstack_cinder_features:
                    enable_backup: ENC[AES256_GCM,data:ZAAhCQ==,iv:2wNdW0uCiZKcfzRZL+rBFU64otFWA09QgxlGibisxTo=,tag:kKnjBJekQIqBEIIMgtsWRA==,type:str]
                raw:
                    FORCE_SCRIPT_NAME: ENC[AES256_GCM,data:CuQD2JpZ5Wk=,iv:0WOVCtrVM8vhWbLUnT5XY+C2sJFLKB8dhMH/Gb7AkXw=,tag:kzODXPz5rij5dhO9mlbm3g==,type:str]
                    LOGIN_REDIRECT_URL: ENC[AES256_GCM,data:OJanhtWSiB/P,iv:RPAiYmiu797ssnEuKBOn50/3f5KOGbNdurqmstKQ6Hw=,tag:EPe9NWW8z6C9l0/XMtgg/A==,type:str]
                    LOGIN_URL: ENC[AES256_GCM,data:GZEmex7HM8GBChvsVqx0kkn2/tg=,iv:WaACtsK1gL2xj0cgpgH4iQJoI4+DjjBU9Uo7CvSRaHk=,tag:ke7SB7zzlhNX0rXq2OhiKQ==,type:str]
                    LOGOUT_URL: ENC[AES256_GCM,data:XMoDcIKE1JsSyxXWoyC+qjCebSQb,iv:DvVmlCc1r87t2qdb9stVdr/t4dJ1oQpaem7Mnf1DNcM=,tag:7moqgNUPgXtDJ+cZTcOL1A==,type:str]
                    NG_TEMPLATE_CACHE_AGE: ENC[AES256_GCM,data:+Q==,iv:60MnAG2nlc3TCNg/xuKGOyW6QCIqTEW0KJqgFt/D338=,tag:zeycMjTW7QPy19zLNN76GQ==,type:int]
                    STATIC_URL: ENC[AES256_GCM,data:Gi+8rmIu7q6DcgDlARmc9w==,iv:bB2xMFL8hfjvbWlH0GLroAGXKSrkqKIwq6aq9voF8n4=,tag:hvBnlz7276VIMpyveY6F2w==,type:str]
                    WEBROOT: ENC[AES256_GCM,data:f/JYeFLgvONF,iv:ybXqa6bSe+m2rNCdXXNWmpd9+CTyo38ZparrG81CB8o=,tag:hMoIqFHU+F12lhl53Yn/Qg==,type:str]
                secure_proxy_ssl_header: ENC[AES256_GCM,data:iX4JxQ==,iv:n3toOOkTjpFWbhKhEIsyWCOY/6ixx8sKgIvMRyIMVbo=,tag:JWjTkxuy6D49rXefbnyenA==,type:bool]
                session_cookie_secure: ENC[AES256_GCM,data:o55OUg==,iv:yTJ2JzPj0sznk9iiZPVd46d78mGCh5JconKnY1rSbqk=,tag:OpBD/Y87NCIJne1ChyF7Vw==,type:str]
                session_engine: ENC[AES256_GCM,data:Jb0CBV4v/Qe1gz9cjsH4Cd+kpCXcTy6Sd80WN2OBJQldtJ8=,iv:TUJulbO5uraBve7F7WLHnkKdVYsxBoFYGRdZheejkH0=,tag:9N1x/Fh6jqkH8o7CMS2eKQ==,type:str]
                use_ssl: ENC[AES256_GCM,data:229gGQ==,iv:A5h6AXjdMZXGo0QgThOPzgDFT3fD8K1uMkj8/IlfADs=,tag:0AZ+e3XTEbtypnSPcIl3CA==,type:str]
endpoints:
    dashboard:
        host_fqdn_override:
            public:
                host: ENC[AES256_GCM,data:54eb6mva8OYxKX0UR+bFJDipwA==,iv:qJsvKtHXbKTBXn4GoAsV2BuYBpqmfH6o3+jljWt2OIs=,tag:jBOg/QcP/1Lqv0q6zrB45g==,type:str]
        port:
            web:
                public: ENC[AES256_GCM,data:/fbf,iv:S4G3yIJvSWXu2PwQRNqPfNUOP3EuuAtqR+ryJgHv9+c=,tag:GjjnUsHV53T3xTjrf0DyuQ==,type:int]
        scheme:
            public: ENC[AES256_GCM,data:LB9qaLA=,iv:8FQDi8PpDh4CtpUGUUL6DE+CvNUFG7rbonnSeCb9sEQ=,tag:ulaFuu6+D/T/y2bA7P6Bdg==,type:str]
    identity:
        auth:
            admin:
                password: ENC[AES256_GCM,data:JerIRQYGSZIU0sCrnujPLwkBIK6rW0wX+HT65cBiuTWWpI7UrypDOuBHkVO32OqCYJ2hq0saUGEfz464rWglYg==,iv:kkpIoG9eBHSuXzjG8ePzFXlBuHJzVYR8sIHtxXJN4wA=,tag:pd0KQeuWSUn9gthRbEtj+A==,type:str]
                project_name: ENC[AES256_GCM,data:dnVW3Tg=,iv:cwa+dFd3Gd6SyuHoeGB1vCIrxTYhO3mWtQWmRyIMErc=,tag:tMiKGmETDtx7Deu8GTw3RA==,type:str]
                region_name: ENC[AES256_GCM,data:o+mD1lIMMlx+,iv:KYit9EXYJQyBkAdp+TtsqISZPNiPvEy18HA/RJtScpg=,tag:RpqHafO994ChrSBVMOtYPQ==,type:str]
    oslo_db:
        auth:
            admin:
                password: ENC[AES256_GCM,data:nTsb/cIvWHrBKP4xY+gceiaYAtPEi6vU/h8m3OoTJgrEuzmTpNjqtlBPuBSCodgD8l9NzDB8+R691My5iZ0d1A==,iv:Nk3SN5hS+9ZR5dkueXgt6Uru3i+RDw+s81Rn2VpJFNg=,tag:kHdFXKb+7t/8W4oEik4asQ==,type:str]
            horizon:
                password: ENC[AES256_GCM,data:1NmoS92FXB8mD0LMQZ0ww9Ohu20JiLdMgjiNwv9yqJIkBqqporhABHCKqMIfE1Ip,iv:hA7Td7f5ARsoicRfssEe79dKF5FZTyQNMoIi5UgSE04=,tag:6c9es4zJ0X61dWJREwkHuw==,type:str]
images:
    tags:
        db_drop: ENC[AES256_GCM,data:Du0+KSVu7meT1yMYF3W4ex0wPkhSF+zQ1AN/9/mW5F2K0ocWGN63fXuiz8hsR3l1ZTrBv/eV,iv:QvPwlcmAvHJqsl6Z0f67jv9vJT6XEDQx73LR/IxXJr8=,tag:VwqmiWrQj+6A40mgOYb1oA==,type:str]
        db_init: ENC[AES256_GCM,data:jPjkjjHuK/e5Cgx9K/hFBOz1QzuTQxcNB7PGkMlzXsDWmUF/B3hs84UFrDTb06/mXl9tRwy1,iv:CbgU2rCjiWQnAzxUfvm0xh8xI36eJkLBBbekJdCK3hs=,tag:0O120Yxo6BoS9405qJ0obA==,type:str]
        horizon: ENC[AES256_GCM,data:kwKSA4LKAdnTbnZgyfBT/cD7Wd1Yucu/e5cqVpJnn2ABCUpxKwXPa0+Jyusb/Orv1a6qT8BX6HrqKMKwsm+/rSueuOBTEg1A7/TOAQTXo5kU+uz0pdv/kTnDpsTESGz9hOsYVTnFUs0ns0HQYAkfKQ==,iv:qg2/sxqZYn03ZNILKh9bSYUkZ4DpYwCKYZV8KgKS8HI=,tag:s5iHquLnI3Zsx1x5lp3Wxw==,type:str]
        horizon_db_sync: ENC[AES256_GCM,data:9c6LN+MpzpepAMmpiBynftcmkyNYuqT12zuwOfFTyESOLoeKq2+Dnq48hZAF,iv:bHx+9Wg19I/6UHLZF9dyHNJoJ9Au/DHPoiN+D24U2JA=,tag:Swa7pyPdvIvj1jRri+BQqQ==,type:str]
manifests:
    ingress_api: ENC[AES256_GCM,data:2EKMdyI=,iv:p8+DGtxQ0FRxv5U9WwSQ6mu8fvjhvfrIV8nsiU9wj3U=,tag:GhPvE/WDH9AXAmcSX8ONyQ==,type:bool]
    service_ingress: ENC[AES256_GCM,data:87L03xk=,iv:qMjAjLXNGAtbcb19o4X+2dl5s+rMpoh/RKTjAU88LQQ=,tag:UXmWukqceGqbXPJhkw2MYQ==,type:bool]
pod:
    image_pull_secrets:
        horizon:
            - name: ENC[AES256_GCM,data:YXQvlWu2yNsUkLCMb3lkouoagAo+,iv:hOyYPD4FQf/dAYVFxgRpPzJjO50BtVqZsnIUEf+Xf1s=,tag:Oeja74pXnjF6QvUjkZjnRA==,type:str]
    lifecycle:
        disruption_budget:
            horizon:
                min_available: ENC[AES256_GCM,data:Fg==,iv:OtG1k9IzGexkDGFEs9fwHB7gYbNpsr4lF2tXQEy6PW0=,tag:riZ0deN4dhO/t+JyDd0j8w==,type:int]
    replicas:
        server: ENC[AES256_GCM,data:AA==,iv:D1Bs25snPwhSh4+8iMkEKg2J8AlbnvNA2E6QQkM0Hrk=,tag:2dSsCsg2J/gR5IrrkoB/MQ==,type:int]
    tolerations:
        horizon:
            enabled: ENC[AES256_GCM,data:CxXqpw==,iv:ruerU7hTaU2qcNIsRH9xRxXBiNmS/Z8XtqtcNikcvS4=,tag:TbCqu55lC0EPsAKWj6lCgg==,type:bool]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpOTB2aUlrZkJEbHMyOG81
            Q2piVUJ6cGZ1Vk1SNTlzOHpIYy9JWjA4VTJVCjBOQXViY216M2tZa0Y3c1hXc1Ix
            OXY3R04raGtvRFRrL0Zic2JnSXRhQzQKLS0tIGUxY0VXSDF2d2JWMFFmWjdERUlz
            WWs4Q2VLRXpiL2Z0MERWVko0aWUvSWsKWKUC7FQKoBdzSWyj9AYNwDrBArVsfDj+
            MrHCVhvZdhtuCmZiidYC7i8Tiym2yiofTso7Hdve8bwneDDQvEaiug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cjaxalqu6gs9mev9w0u537793ql5t0gy3a6d9qn0265s49k9ss6q7flh4j
    lastmodified: "2026-08-05T07:34:30Z"
    mac: ENC[AES256_GCM,data:tLYdJlqplSsyyMjEFDEWitS72aX1S2Sa44Nd1BwB5mWTAX6+d7tpFWAgbiBiYa9IK9B91YZnWI4/BoNJy9PNN+WIHSmCFMM0pXQ19cSA4w5QIFnqGnZtFV0wBMCpEE/WwnutanTgeLOlJ72W5wDBhPjyg8FrbsqEeNOOL5T07rU=,iv:WV7d87a4PZsSEwJEOZ9dKNXMDUAh5dBr7TjOaNK+Oco=,tag:EJWIwBbdDNwWwO+UPuvVnw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
