images:
    tags:
        bootstrap: ENC[AES256_GCM,data:Blkw2kRffssR9yKN3snGXRq8fJNl/lepwlK/VQHtKX+keHwPytyMq9ICdKTzImTYimLloQG9,iv:jUw93ZKPCNEpx+Wi9Gk55RUsz5O19z439VzoU0Eq2Eg=,tag:3HNiNPofFch1HUgyM7XJ5g==,type:str]
        db_init: ENC[AES256_GCM,data:DXT6IFkpkYHVrsSE2CyfrF6ZwTfFkmLEBdPr7QEbpb0GHiRbrr8bu79psYyePogQXKE+d1Kq,iv:twsxEyzvZrN9YZ4q2U3NaUW7PGam8Ez4NQpJQ4jlhEQ=,tag:p7a8oXOQBNXb8znl98oP9g==,type:str]
        db_drop: ENC[AES256_GCM,data:wQ4ONarTDipjv5z13SsApw0neiUp3EAvnMZ2aLnbIftb1h+/YtecZ55XfdOi/UzPFx2zWPh+,iv:dK3tznB/4uIHzk5DuIqWHwTjgJTptCMsh0dzj62qaAo=,tag:xq3AAUq+a8CgFhjtXFpFPQ==,type:str]
        rabbit_init: ENC[AES256_GCM,data:STWOHSFnPCirkwYONKpMtsVkukUAhk2esHrhzUjSJy78NxtLGb7v7z+LcCWe,iv:/UcFxcueiMIGKL2ipfFQGXaYezQuozGSBVLNj0qDUOs=,tag:MX15no9RZeA0QUWN1/6A3A==,type:str]
        ks_user: ENC[AES256_GCM,data:MrmPzcF5r2T5fExo2rXpTVI1wZurXM99QPSAoScLirbxu5YKHFpnVD7eV6ufuGcJhe0ahVSP,iv:6oJvKUYGiSbFYh6MmUxLxXMbXa4uxx71AuSPVtQUNsI=,tag:d3h1rDpLGjvECb4ad7+zyg==,type:str]
        ks_service: ENC[AES256_GCM,data:XxcNc6y3amPOaqmKUbRcI+3kZhHiDLcoFSJ3TW95PeaVKOia1odtieexA3RTMzuuSea80Y5D,iv:7uQLzfnSIYiRoUYT9a5TDMzcxMExkHuKlTu6+2O2dCs=,tag:YmuzqRtcbMP8gEuke29ATw==,type:str]
        ks_endpoints: ENC[AES256_GCM,data:5Bas9w93YTPAbONDnNO0982JhHjM2gZqOpU5loLJkgfEmwZeba4YHcjf/0yKG/cM9VyMZAPp,iv:skImGMJ4VZLfIcwSwHCUP0b92yDkAr/igWbKRTE2v8k=,tag:HUrJDitEP5N6yNfsDopXjg==,type:str]
        octavia_db_sync: ENC[AES256_GCM,data:aM0aKZAuJgMHnI55yNuCynASRDd2qU2nQq4hY5mp2AEgBvN/pcVXF65wzpnVTIB7VJg86DpCezQZj62gS929eHXp4pM9WcxWL2xCjsuUJEdFUMw3eCUsW+li4kpDjkDHAUH//G+Ik3vCnL2MvGYdxQ==,iv:IuRGF+KSWAFYlidpFFu/ej5H+myX6ASW/ga/2oyIwS0=,tag:O57P0G3F6KdrQ3/avKu1Hg==,type:str]
        octavia_api: ENC[AES256_GCM,data:7U5rOqKpVZOBVvRlSWBgCMS94+FrzD+yAEGnGM6W1Nv9ly+t4OWQo+92YLACIWzvn1qQZA1A3+HFhbje/KDE2wUVa6jQf07IziZ7LVjd+GCakETiYABeWgdsGHNzyeS981xpu4jXAwrNtql58h8HxQ==,iv:2taUDTDhwkKnjWqLGpjuKqwQPtLp1e9akFZ7qZ4HstQ=,tag:1+PvTtZOIaqvZmVu7Jyl5A==,type:str]
        octavia_driver_agent: ENC[AES256_GCM,data:tNF0eF3DbmuTy4FQQnwxogDH37kx/5bmLHPY63XtXfnPL7OXZbmWtfr2y05YbTdNiGQByZIH1fBj4V1i0vjo2gE8x1Z+Yw8y8i5t2MPLALWjuodonaN958MOcaAqYe9cTVkOctJ5Ki4l7snwOsiwhQ==,iv:UaBI2mC+mvzxbIkoBHqfBr9lospH2Y1NHOfSfOP0ZDI=,tag:Ue7Dxn9nsrdIVvZI4hGD8Q==,type:str]
        octavia_housekeeping: ENC[AES256_GCM,data:s6O3D2WzCjtpZZRqjfK2ALUxT6weWmBkZyl0CLICaWWrH5+bDg2KDKXuTRiqv0Oz5VViuBtgpoN7HhVtrXRd4KKlXwNdN8Aw9vicmSZXNqt7IB809I/JRzhdNwDRmNPPB8Zf7Tgi/MU2ehzQPFZfog==,iv:UiH47gzw3qLSykZlJ5/jWWv0N6L8JH9vhRrxfLbX1sU=,tag:eRzaXLNrlVZAGtHv4DvrIg==,type:str]
    pull_policy: ENC[AES256_GCM,data:WNBMgUZzsT26Bxia,iv:KLHFYSfsKrN1kHG2KhKSLeZQAe3MFIA7llccx8Uwnvc=,tag:qBZAHPXoht/Iz3XLrRGA4g==,type:str]
conf:
    octavia:
        api_settings:
            api_handler: ENC[AES256_GCM,data:Yg33aIgCm12Oc8DlFHM=,iv:aDrHLME/Ze6bZUzqwRBIiSejTI2byDqjG6bu9OINTV0=,tag:NmrHtiqj/vBo5OXeKpldrw==,type:str]
            default_provider_driver: ENC[AES256_GCM,data:Muyn,iv:bWL7p3A4euMfh+3kQYl5foIN8APHCyFI6R6v8asbCyw=,tag:lKtI7hZnA+nVRx1p6+gNug==,type:str]
            enabled_provider_drivers: ENC[AES256_GCM,data:xS7m3Vhc6Q+bAnO6uGIgYw==,iv:zR1vBAvc2lQbfYMF+PCBgibpObYtiRV5Ieb8nZulbFw=,tag:FTdr7rztIvg52P9vTl/gkA==,type:str]
        driver_agent:
            enabled_provider_agents: ENC[AES256_GCM,data:Ve8f,iv:yQ8BaqvhiGo0mcQBaek5gphwIuGA1OMF80j/DniZR98=,tag:YWA8HEcJsdjN/N/2Zq6+KQ==,type:str]
        neutron:
            valid_interfaces: ENC[AES256_GCM,data:G+Rcfy+poaw=,iv:c6QBp3GMQ2Hh1bmpv0opxnpByA1EuGRyRwyJg2Ov+m4=,tag:k77AvzTyPDitz+br/wfexQ==,type:str]
        ovn:
            ovn_nb_connection: ENC[AES256_GCM,data:l5pN2X7xz1KNME+4WuiG/nofa0w1VMSoLH0XYefXYzN/yJmpbIZJYj4JOG81iGPSFNBVeBEcGCUoPURzq2fB,iv:ReOfqFmJ8dbIoLUP1Nh7KAdtt3+bc/+7/DPhYy2WaDM=,tag:WjXsRNVp6KBA5cNOX17ilw==,type:str]
            ovn_sb_connection: ENC[AES256_GCM,data:2P5WdR5EdQGAXOGP7oeQ0dopXxhc2pGi6nH29MNdKiJP93OqoaRFiPIzbaEmxpxK4kdYdNTKJObYXUoahbyWXD8=,iv:uLqzmvDpe7ttDHr0KEBIKDBtSZ2kxpXKKJl4+JyMu8s=,tag:IXEmmZ0K+SL7E2a73DSEgg==,type:str]
        service_auth:
            endpoint_type: ENC[AES256_GCM,data:C1YCN012NKdw8EE=,iv:PltTd83eWK6cW5w+yytA23fR2bAKKtDT91+HSkruuRM=,tag:4Bw4H7Vis4utZ389zI8wsA==,type:str]
        task_flow:
            jobboard_enabled: ENC[AES256_GCM,data:qa2s/oo=,iv:qEI+OW7Osn/+xT1SzJX4tsaYniYffVVYbsX9JNXH4FQ=,tag:0wQtLC5eKROObBbs+ANPKw==,type:bool]
pod:
    image_pull_secrets:
        default:
            - name: ENC[AES256_GCM,data:ChNucViaNCsNWM8Uhx9vIesMAVig,iv:aG2aeCl7XbXcNp5h3Ybwfcd0oSKYN6ghs8Mpmp6Ngq0=,tag:In4TM6c9ESDIeqeK85v1wQ==,type:str]
    mounts:
        octavia_api:
            octavia_api:
                volumeMounts:
                    - name: ENC[AES256_GCM,data:vlxDmeHoRg==,iv:OFeF9WuFNZA4WeUZIVce2cCJYo4ISHkwKkTY2+Ehjvg=,tag:Eh2qeBM8x7hR9GJWYV7n5g==,type:str]
                      mountPath: ENC[AES256_GCM,data:iSlV5g==,iv:sDwI7CQDrocSva3UMQwMFxhgHi6MAy4MMKy8+eDroD8=,tag:Xtffetl6ojQxnAGa7XYj3g==,type:str]
                    - name: ENC[AES256_GCM,data:l2WyIDJEu8SycmkcGHlE,iv:K07yMi1hVVmC38JUyaIdtXJZV58ZNmap2Ubi6/91upg=,tag:6YaUceZobdRyeiwM5ltFwQ==,type:str]
                      mountPath: ENC[AES256_GCM,data:whLuir2MYD68SvMt,iv:cWUos9SRj1AskJB0j+Hl0/0bLGRcexT5W+xKZhLvPO0=,tag:m6VW8Psy59q3g+eG8cVMSg==,type:str]
                    - name: ENC[AES256_GCM,data:VwAIsR1Muz5bteWhOR8hzeOlVCN4,iv:KDeMuDLjxczBkgF9rspJl76XCNJyCTcZ7BcBT3Rd+vo=,tag:XNh1iZNR/pz19U5aF435Cw==,type:str]
                      mountPath: ENC[AES256_GCM,data:8XohXIgy/e+xIPKEO1rkRw==,iv:xi/a5hWjq2xbd6/Ukc2Ug0xAJT4eM+AepOHGkR3348E=,tag:TknOdjGmwOEwm6I87Ew76Q==,type:str]
                volumes:
                    - name: ENC[AES256_GCM,data:7LyV28lyxg==,iv:eF7nEtUKx0Q93dkxFD19+i92TNMRRsxOocschumWAxg=,tag:EL+pUjUGUq6XF3f2qT++Vg==,type:str]
                      emptyDir: {}
                    - name: ENC[AES256_GCM,data:Bl2V462HwFLZ5yOfWkpI,iv:uSdKQxy579x8+f3J+bSaMMfebmyyFwX+xF9COq4posY=,tag:mW4YUnsNATKM+TfsoftOKA==,type:str]
                      hostPath:
                        path: ENC[AES256_GCM,data:icb2RTbsLJoxZ+Ysj3hOTw==,iv:OLM+HG4MdQd1vEro22bCV+YwrFdIzDQu/cgbfafByzk=,tag:ooC9XYSfMei+8tS5fA0uvg==,type:str]
                        type: ENC[AES256_GCM,data:MMOeScNKCI9SE1Elm0GZZ6w=,iv://WrUmjJ7piZ4NB4MlpDymF0oS+pRsDgu+Euqqc5ocw=,tag:IAvw46xA6OcF9ytF/HEv9Q==,type:str]
                    - name: ENC[AES256_GCM,data:U7T6ikaOsKsfkhyvgzeYkEkyrq6H,iv:OOLkatFraCt3ngDv691HYMfqgIfD46aNx/Pq1hr7iQ4=,tag:x5hh3V0B4Zsuk3QylUubjw==,type:str]
                      hostPath:
                        path: ENC[AES256_GCM,data:n0vGYQ0skA8WIo/oeqToLHPq4ZU=,iv:Lf1gF0zduKRieovV7FfbYn14po0dg/YSCIrv7ugq53E=,tag:YCBZ0TqZS4FOaXzoWwF7Bw==,type:str]
                        type: ENC[AES256_GCM,data:qQupIEQ0dtCZ,iv:UL50vi5nDX2EjrTE0b9i5n+4O3gUo4gnj49YM6ogOAA=,tag:D0kN2BtssgxFMe34cQQ9tg==,type:str]
    affinity:
        anti:
            type:
                default: ENC[AES256_GCM,data:8rYZO7yiC9R215fFE2K3maQ1+QKn6f538Rvs2eF4lEUzD7F22Q23rDIdSWzG/g==,iv:5zYwVRlniwmwEYtVsdUteYOEh9PYIAD2tgrtyzvpN84=,tag:+sCFuX/4tQx6uTgqnTjWYA==,type:str]
            topologyKey:
                default: ENC[AES256_GCM,data:zruhZwbk0BY+lDFF9SEiSJGXGpmLZw==,iv:nkqROXa+ULWhV3llQMvj++K5Y8KXtaupd1ldO19tWKc=,tag:s2C96TOnABITBKz/FS7k4A==,type:str]
    probes:
        api:
            octavia-api:
                liveness:
                    params:
                        initialDelaySeconds: ENC[AES256_GCM,data:wtqB,iv:sCgQFrEzF8X6VOLyb+S4lptCSXIteWPwQ9k8XNBLQE0=,tag:ay5DCtbfB4eTWLm8hGLdRg==,type:int]
                        timeoutSeconds: ENC[AES256_GCM,data:j3s=,iv:TI9JjdZoqGoSV+z8966HsbvQtFZPpuy3ODVeo4kw9Qc=,tag:NCB56bkTxnb9JzlFBYb2XA==,type:int]
                readiness:
                    params:
                        initialDelaySeconds: ENC[AES256_GCM,data:hxA=,iv:uWxwSagJQ0EEs9AfckXRaZidsFbgEv9SZ01P6GsqEPg=,tag:/+buvbpOOnEj3ZVqo6Gkrw==,type:int]
                        timeoutSeconds: ENC[AES256_GCM,data:oaU=,iv:9ainwIS5/5nfE0kYPNhuQ3KQzP8pJvLCElt5PPP1e5A=,tag:3tOqnlgR9zG8UB94D+f/gw==,type:int]
    replicas:
        api: ENC[AES256_GCM,data:rw==,iv:L7CML4RSnjiQgGhsFa1QONUR1SONIkg4l36Sc8N3x20=,tag:ZxPsQidITfpg0ejiQ0hFsw==,type:int]
        driver_agent: ENC[AES256_GCM,data:oA==,iv:gKUlODJm1fn4ZrEMVNcVeyf00wdgLZV+7iu8Qy3kd6Y=,tag:IA3AUSUbJpV6gtdA9BHaLw==,type:int]
        housekeeping: ENC[AES256_GCM,data:6A==,iv:/Ly2QLV+oKP3/IhsogVMnyIjj12BpYTeb+Ph1UlzFS4=,tag:VWJvpOUL44oxmDjWa4GdPA==,type:int]
    lifecycle:
        disruption_budget:
            api:
                min_available: ENC[AES256_GCM,data:Iw==,iv:7sbkmQUE12WdK5Qr2HHF74fJ7nmSrAxTpzeI1Pi/LeM=,tag:M/0KaDC0dqxWMEIveARMlw==,type:int]
endpoints:
    identity:
        auth:
            admin:
                region_name: ENC[AES256_GCM,data:H9586IsjD/xX,iv:bMhXpsg5d/ZMYh3Sau4JxoEwBKlpkaMwdVHlBIQHACY=,tag:4BdbK9ONFKdezwzxDMKEsA==,type:str]
                project_name: ENC[AES256_GCM,data:rmoCPgQ=,iv:tWxE132d+8bfGf1ayW7NkUBSjXna72w+HEMkhySnT+o=,tag:19UBUPFqOsFBnOdqzE0Z5w==,type:str]
                username: ENC[AES256_GCM,data:fb6+jrI=,iv:JGkl++qc47a3VrJYp6V3DoehGld74CWBI4kQ4ViqGuM=,tag:PKiQUwJ8Vi7nZE/yoBGF4Q==,type:str]
                password: ENC[AES256_GCM,data:wkLRby0qyP+c3ZeX2f6CWKgJPwiX3baJLcqaX3VlZq/eyJproKHqpduT1/f4aMcjOnz2kN1HDF5C0JqW3UZ3dQ==,iv:jQVDkky0SXteCEvlvgfnDM6uDUnodNww4a+T34HNygA=,tag:MLCZhRHaIPonw6aEIVL/2w==,type:str]
            octavia:
                username: ENC[AES256_GCM,data:t9iTYAaI1w==,iv:0A8AYRCohRMUFt/wjfuXWStk0Ky/pE2Fp83SU6esv3Q=,tag:9ykwVcxP1rYZnoFCgy3upg==,type:str]
                password: ENC[AES256_GCM,data:fDt4cQRmU4q+tqqX9gHSewM+cOZmB2UlaCAL3lrz7TKRcM4R2chs4DsnKU1z5WFt,iv:rGOrorXxGujHjU4jb+mtDlS3iozxSQSrUQpedtjo41k=,tag:st3iJE2ReYTbFPbrne4B5Q==,type:str]
    load_balancer:
        host_fqdn_override:
            public:
                host: ENC[AES256_GCM,data:xImKQNR+gx7F0eM2INbJ0eg0NQ==,iv:ZN8BwpQT92ewGWsvLAsydw02k6hJG26JCZvRtHJCK5E=,tag:AiBpuuPZ8AlNB6EhsXIW4w==,type:str]
        path:
            public: ENC[AES256_GCM,data:7TiP/WmR0AMiCDrHl60=,iv:BEivPvz16tdDwHNNfeB6T7bkIBoo+l7N46j4YjWMWus=,tag:G7JENif2D7gHQuER9STQ4A==,type:str]
        scheme:
            public: ENC[AES256_GCM,data:NbHVMX4=,iv:ObQSYrSXc71qIpYIsfGp61SRoh0gCPYM/zEXMCttSvE=,tag:Rg+j3qR3NVyDCKf8hNmDSw==,type:str]
        port:
            api:
                public: ENC[AES256_GCM,data:P6OK,iv:z1SuQGOkm+6HWcSo7qYWxc6hwk/SKyOfiN0Z4vqxay8=,tag:GgHZr95/ZhgW69aXjKUzTA==,type:int]
    oslo_db:
        auth:
            admin:
                username: ENC[AES256_GCM,data:fmglgA==,iv:ZN8lJXGc5vdjl3bMlyZJlWvhXuUaiMdJ++ib1eXCQWk=,tag:r8ST5n6cNxDbi1uEDSILAQ==,type:str]
                password: ENC[AES256_GCM,data:U9jNOifBKe2jbHb5SZafr4yChXvOgKMvyfLG8oTofKySJnmMLXl2/X4cttPRO8eMkB9uiPectCf4JVo+wcKiqA==,iv:RfQO2surS8E5Ric56R5NAd6jKRN85hN7lbKby1UbycI=,tag:3ATwyEFg/aFHVBXJzwHeZw==,type:str]
            octavia:
                username: ENC[AES256_GCM,data:mw3SFbtClw==,iv:I5NcVZb2TyltYn8iUtHIVDktSZwll+WhxYhPk1TNKw8=,tag:HExV8qZ0Rs057jqJoD41vw==,type:str]
                password: ENC[AES256_GCM,data:SaRzEqipeX+LQvMq4TgtYfg7tUazbG9mwsEWjgqe7Gx2ENhl0RpxnEOEWoN4ibWW,iv:pp9RIqDDPQDATojUtg7BU6k9qP0FXqHlNeSbhLMQAMM=,tag:iXvz1M7btUxDqtsCVJogMw==,type:str]
    oslo_db_persistence:
        auth:
            admin:
                username: ENC[AES256_GCM,data:WToOmw==,iv:z6PaK69FHZabhiWcIjGE/x0ugbC6ZqewqzlVLUegk28=,tag:8N+i23+nyd9teXGGBGHUEg==,type:str]
                password: ENC[AES256_GCM,data:zdM3L28gcdVdF8nM0SJ/remQ5XHRsKrRQRedM8FIug2NyjtCHUHebkusFGPvaMW8asC+gHvCo6OJCGjqd7uNag==,iv:nYNeoxNDYterMA6TbM565+brzZtT+yANuX7q4DrDwRA=,tag:d8Ia/DISZk/MF+wA6IF39w==,type:str]
            octavia:
                username: ENC[AES256_GCM,data:X9Tr4S5f4+RYmXcNedJyYIU1YA==,iv:a71jk/UWb1GwTc3C7AS3fMRwd2af8wjO3dJJaEAyiCk=,tag:5kgroVHefxU05hU2bDoblQ==,type:str]
                password: ENC[AES256_GCM,data:jm8MKYTc36imwGNsMi61P5umS9ookFSljjp+vI+cAs2rl4Ah8kmzoVSqYzNV2AKe,iv:kKve+FN7SIfHe+FRmlELTB/ytVEaa1j/K0Q58yF7220=,tag:iKytOeL53PMnUaJiZAW0Ng==,type:str]
    oslo_messaging:
        auth:
            admin:
                username: ENC[AES256_GCM,data:ZKixml0X0Ug=,iv:RtEOm4c2y6KR4y4fj06O+sur/0KWRXRqgKf27FA2LyU=,tag:+3z0yLSrMMQB2zM0iNlxlQ==,type:str]
                password: ENC[AES256_GCM,data:hg8bL24gRmPKa7ZYKTOuSpIu+CrNYgftzE0tzFCXfYWtNSTbnaHWcs9hfa+uLVJxgf9aDlk6/eRbw0wI/FKRTQ==,iv:TSb5O1XRO9LgoAyHwvqjcgVkistW8O4HnX/5jfqI/do=,tag:ROU61O1LWn7WdkZm/M9EVA==,type:str]
            octavia:
                username: ENC[AES256_GCM,data:EIsqxR3ngQ==,iv:DOdNN8zuTK/tBElt7aY0MF8A/VI/uijt2SYjLz/uf7c=,tag:rrON+FO9TKnSmiO6t+sGYQ==,type:str]
                password: ENC[AES256_GCM,data:82V2kL5kNNzC8ZELNqPzewQcUe0jE294c3nVtvqfDHdYTHi87EEECu1jF6OSOK5p,iv:/8m5ud4FUpzH7qpngCn/7WNjOwO9SpB1uwZaSZcxsKc=,tag:mEZnlNFbJDghWwIpCObS3Q==,type:str]
    oslo_cache:
        auth:
            memcache_secret_key: ENC[AES256_GCM,data:M5vdlsIiiBBuIh9zX7lXGpWCDY70voe8bAM5UrcNNexR8yFZ1Jb8M4NLqhPtfHJdlFufXPguQNpzAqMC61hGVw==,iv:pnh9K9WoH5v3hrs0fGuNSdnaMfok1g0TrQsWLa15jvg=,tag:lk2nV/FdvQszpIX7fCFzqA==,type:str]
manifests:
    daemonset_health_manager: ENC[AES256_GCM,data:m7SuDkU=,iv:mKUI8JUFuH/k0oRcoT1FspJ3fyo4ciIk0Uf3ego84+I=,tag:wvNuzV0L+Vm4UKGm/WTNfw==,type:bool]
    daemonset_worker: ENC[AES256_GCM,data:QPpEmpU=,iv:igvcF4/R8kTQuE63/CyhO69tjalCtQMYzn+XqLjGxKw=,tag:uyfGH7ciuJlWDG1OMwJOxA==,type:bool]
    ingress_api: ENC[AES256_GCM,data:V7v1HZY=,iv:7E/JnxJ+/9UGGncFrcM+4uHeUyVD23ipU8N9bvJPORA=,tag:8Wp2TWG0Z73lfBPQs7z5Vw==,type:bool]
    job_image_repo_sync: ENC[AES256_GCM,data:uQ3aFVU=,iv:8ZP7u0uCs6onVm6WoputGfcMZ8pIEAiuljerGZ9sO1s=,tag:5EDmrxhwaf9NQQx+wo7VOA==,type:bool]
    secret_credential_keys: ENC[AES256_GCM,data:R1CV5Ac=,iv:n2+nQJhlXZq3Ri9iT+5dQo8eRT40KTAoS8AUpWBbPMs=,tag:wlpQSQZ218UQKmav8Q8VZA==,type:bool]
    secret_ingress_tls: ENC[AES256_GCM,data:YDKpC9g=,iv:dWch5EpQEit0QSG5LltUjkGYsa0rjv1LSrkn4LUSRzA=,tag:Pzkl8CKHXq+2nFNYLcvrOw==,type:bool]
    service_ingress_api: ENC[AES256_GCM,data:/bfvgTs=,iv:U9fc5rJ7M0438oy6UMh+n8/sF5hbvnk+ePiM6G2WWQA=,tag:VzAYrTHIgKf2KNuK9WWmDA==,type:bool]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4K1NQelZvMmxVNjlKVTg3
            TXh3NkFMZWNGRFVRQmRDOEdpa3JhT3ZtZGpRClNuWG5QMENsYnJZQS9nUnpEbkhs
            TjVBVHlVMmN2dlFBYWhlVFFKVFo1RTQKLS0tIDlUQldIQ204UGdUdEsrREpwS2tO
            NXcrSlJpeWpKbTk4YlN3ejc0RUE1WFkK/Qwqerxfuj4ngMC2qf/gbtep2jNi05+L
            gLhxA+3AVZ5TmgTxf+fgCstZB9Qxx+SJ63WY3SscDSZapJCxPaoVrA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cjaxalqu6gs9mev9w0u537793ql5t0gy3a6d9qn0265s49k9ss6q7flh4j
    lastmodified: "2026-07-26T16:46:50Z"
    mac: ENC[AES256_GCM,data:orcjeee8rxpSykpiX5bbci9vBQqYq4264mJCfo86e+OlUedDkBYVbfPBcd5skaHtFrAJEZiUbLjxYvJxjJaxh8nbHEOBgoGhgfEliAgPPmulER2fvAU9VvyHTZ8zRvAB6w5dmP8w+UaofqbgfEKprFPzd4YUJofsHctNNxaOxdU=,iv:iOmjjimqbfr2+3iEGUPDKEnmn7NN7U1cP8Kb87yQrkU=,tag:Ll1iy0Eer6nygPG3QmqMyg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
