pod:
    replicas:
        skyline: ENC[AES256_GCM,data:eQ==,iv:N+BBawaVcxRIdFoHmhh154Fxfx51QHdUG1pkNfK9m40=,tag:710jYvxZXvDH/qBh6nzoFw==,type:int]
    tolerations:
        skyline:
            enabled: ENC[AES256_GCM,data:5QsJTw==,iv:jTJSWDZPkGsywnA5CE1zOn36MTuAxbUpyf24D6NAdvc=,tag:DNjtKZy5y8jYhKAyoTbKNg==,type:bool]
    affinity:
        anti:
            type:
                default: ENC[AES256_GCM,data:Ew0xyiSJtKG7UIITeWfrDpxM2HTjm7qfYPwVy6UfixwJ/SGabRjjGxELuJEfnA==,iv:Knn5cN9F6GGVpGZnzXTaTeuUQ5n72ocOAWeHkyayOx4=,tag:FeGBHzjsAYC8cAu5ZPFXrw==,type:str]
            topologyKey:
                default: ENC[AES256_GCM,data:tNt/7ba/A/BH5rlwpIF6klhH0gTsMw==,iv:FMvcUGvofPq+COhljxY3H94pO/RJTbOdvH9yFf3zork=,tag:pd/vxu+m1EatYK3NX+dibA==,type:str]
    resources:
        enabled: ENC[AES256_GCM,data:QODd8A==,iv:oilzadY0TLSYpNalHUeh2moyMAS0Fh4nO87FPMZDWdg=,tag:2upJ/ouZBLYEXqP0Qst+8w==,type:bool]
conf:
    skyline:
        default:
            debug: ENC[AES256_GCM,data:4/bSBRA=,iv:4mQsifxB5PrcmjeYgU3HV8YD9sVFUUDymgLBTGIMymY=,tag:8fHFH1VMRysxqsGQcvy/yw==,type:bool]
            secret_key: ENC[AES256_GCM,data:z+LmXcexwRX7WzgNfjIxvfzvJGlPXjvfEEaTqCDow5Y5o5yTF94HQBzkGF2C07hoZex1cdSW+8gt4pEyuZ6cpg==,iv:1PfgXj6OtUHc8PBKxAXe28weOImCN/7rAyHfwGjVUVY=,tag:BUnoyEnkKi90JHZLGKqebw==,type:str]
        openstack:
            interface_type: ENC[AES256_GCM,data:2GkSj4U5yoU=,iv:U/OMx/tc6CPELa6As3qwgt0XmZ3hG6tOe2MIJZPRiWQ=,tag:C/njutFhi0lJfSu0pBJKIw==,type:str]
            default_region: ENC[AES256_GCM,data:ZKFJFV7VLaoZ,iv:Lzw3gRAhl6pDejf/C46+9f2HO2dXDKn6TsAgRdZ678s=,tag:FjOfXaW68NC0/23RgUfTQA==,type:str]
            extension_mapping:
                load-balancer: ENC[AES256_GCM,data:XwUY0Zci8g==,iv:+lrCS1aYpGKfC/3DpVFxwPF1g5fzC3Ivofk/KsWDn2A=,tag:npyQdFpQC+YpxV/Ma3jpyg==,type:str]
            service_mapping:
                load-balancer: ENC[AES256_GCM,data:nDfyptIxgQ==,iv:CKKHsbud6iE0E+keMFId1dFIe6Oy3zbjVjQjyz0iDOg=,tag:s09L1P6hkKwxyeo6qlITrw==,type:str]
endpoints:
    identity:
        auth:
            admin:
                region_name: ENC[AES256_GCM,data:kRfjFPmyXL+A,iv:OnD7qf/05DZo/TGEtMdNynHesZNN2dh1RS5FimDgb9Q=,tag:76GTGYacmXmC+pX0JxWQaw==,type:str]
                project_name: ENC[AES256_GCM,data:YDXEKJI=,iv:VApmkV1qArCQKa/tjvxwSPfkXtGwozs13RgnXpPCEck=,tag:mNtaTK2n5eZmWx1RGXe28w==,type:str]
                password: ENC[AES256_GCM,data:+H9AeY/tRHT4Csnsqil77sDJrDVfpDfUuLD7CcxHqZEWiqBWVV7GKx5IgVQCezNGbXQzuzRbcA8cZbckg7yKQw==,iv:HoVvzMi07y7PzMg2jtlDifjMFWLTbu05yX5yquxQydk=,tag:3mxmu1+Gd+5wGUWlqKCREw==,type:str]
            skyline:
                region_name: ENC[AES256_GCM,data:r6Xh0IvAfnbB,iv:XNrKn0aVmhayQ/qsgo++oj3KnPUYfAy1oPDHY4u7Fxc=,tag:oiegOP+zMWP/nFCMLhp/Rg==,type:str]
                project_name: ENC[AES256_GCM,data:5rxSsE0=,iv:n7xiNuSQe6SPE1V4KmO4eR/UsiMWPPb79EEWVArC/dA=,tag:bigjU+4Tr7WpxuStGaqchw==,type:str]
                password: ENC[AES256_GCM,data:KG8gYJPvD/VSMnBt+V7gqUW0iXanXdRMvPO9KlalZV3R8N7gXwoIZiKWYBokEDEe,iv:ugttj7njmjK0hr26E8sih7+yex5fI0bqVvj9xVv/F5U=,tag:B/9b2l4WrLT8JDE/659m8Q==,type:str]
    skyline:
        host_fqdn_override:
            public:
                host: ENC[AES256_GCM,data:5jAbOqwvJoSLYD8OO5XFFGokJA==,iv:AB5AQv5zcjYGUwshmDyBrX2pzVIhQRqwlcSthHwkFTw=,tag:1Fb7ZJpWNxgLieUP4XAIRw==,type:str]
        scheme:
            public: ENC[AES256_GCM,data:QsjMBsw=,iv:NcPyp3cKCtKCPgBNNXZ/hsqezTHALumTMYRl+NjKalQ=,tag:54cedmneX6yjFloWUYHcMg==,type:str]
        port:
            api:
                public: ENC[AES256_GCM,data:XIu+,iv:FqfOAptim+a24j/IpQ82PRlqmRAL/Qb4oQF04VqG5jU=,tag:I4Z5cMCmJZetRGeoa/l+Aw==,type:int]
    oslo_db:
        auth:
            admin:
                password: ENC[AES256_GCM,data:YWefZi4gjjj16Ydvxg4U8DvQ/hjLYeCxsuc0CEtxqaG813H8piEJcgAPxLpZ8ZOaDr82otIZxVRY6+OCwECt1Q==,iv:iFCfULFNKfwRWVwV4hzz0sr3gzTdqWvZzHumwtUY5Hs=,tag:yM2hoAi/r7Ze0h7m5TbqBQ==,type:str]
            skyline:
                password: ENC[AES256_GCM,data:UtVMHNGvx2R6kUflaRPZEHs3UY0+JUQ1Wx+EgTakZMT8KbM4Ni4r7ol5kaw3zYjSAtwD3Y3Gtiqb/vP6qaHoqw==,iv:FFEDga5Lewps01BSRd1psYtUscIJJqaAiwWutuQoOoc=,tag:zO1wQDeBroHWlstwYfEbEw==,type:str]
manifests:
    ingress: ENC[AES256_GCM,data:qzHXWgg=,iv:Wq411So2yTf7k2jBXC3L+v3T7lXZl3YeRv7jUx5Pv2w=,tag:kn2OiDTL8mekAZSO0mIYzQ==,type:bool]
    service_ingress: ENC[AES256_GCM,data:cUmdzlw=,iv:5h5oCKHEI6AB9saPV6icyj/t86dv2mLrK+FXpqJafjc=,tag:688TNbsCBmbcJG1HqPATBg==,type:bool]
extraObjects:
    - apiVersion: ENC[AES256_GCM,data:GcBN342fC7NF,iv:Pj301TfLKQt8w86utwQCHMF5Pt4k5ykcGR1nV9TBjyk=,tag:nJpDFyXI8xBn/bKXSpLcTA==,type:str]
      kind: ENC[AES256_GCM,data:i6XNO/Zy727yDejJfrJVQDXv/A==,iv:mfzrKJ/tlmJULrS/FMm0/bu0vMDB7ajtXz1Vhn6/xLE=,tag:0XshQCHevShxltB/Kb6Rtw==,type:str]
      metadata:
        name: ENC[AES256_GCM,data:zQ3zr9Jydg==,iv:FPT36wvG4oC+MbJQ4XUxbnjBDBWM2Dzq6Omy1QOzFAY=,tag:6ynLJYdlBzwH17oxEXnu2g==,type:str]
        namespace: ENC[AES256_GCM,data:OZtAytXy7sOH,iv:rdYcxa0ePw0i1d1GBMxHqlZB0zBeo7k9joob3CWO7lA=,tag:vLlJsAz72ZIlpPYMdAyZzw==,type:str]
      spec:
        minAvailable: ENC[AES256_GCM,data:vA==,iv:AWc+eJ7ADlPxr4Y9QlfJp+XyZG0QLoUvRiTV1UEWZy4=,tag:aocw7Fr/XH3m9e7QwOt5sg==,type:int]
        selector:
            matchLabels:
                application: ENC[AES256_GCM,data:RcYot3CZwQ==,iv:8ZdbNhCvnE1ci9Xo22bFuI3SBroc6yGQYWpkUk5M1ck=,tag:QA7Ju+24tSKLuJWCyXiv7w==,type:str]
                component: ENC[AES256_GCM,data:BDo02ROZBQ==,iv:TJBl5FdBVukJ/kJk7hylKnfsJNc2NuPhzAgUlofp3EU=,tag:6KTKMZGXje7ByFxf37K0Sg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWWJEM2k1TWZ0Y1Q5bXlU
            dzNienZJcU90NHdETjFRWXJDSjE3UzNMWFI4CjlOeUNlTW9VU2xGY1Bab0hBUGg4
            eTV5b05ZOWRLaHNkTW42QStYcnAwRnMKLS0tIDZLdGMvWFE0R1FCT3Z1azNiUzZh
            ZjRyblJsNG1WR0hja28rM3RtNlpMUFkKhmz709q6/7QtDRsQCdhbir7TnkII/WOC
            ijkM3l/Feonf3GEp0jaZyFHey1on+pUAW9uQZ8tOSDokfoQOL181EA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cjaxalqu6gs9mev9w0u537793ql5t0gy3a6d9qn0265s49k9ss6q7flh4j
    lastmodified: "2026-07-26T16:46:50Z"
    mac: ENC[AES256_GCM,data:t7gpacRFvBY4v+Q0J0+zNjYnukcU68IxG2sfHeqOCXu/gcrIUTo7K9NiB3tkaUGK8YkruKUbt4VCddTSMrOE8Np+KmhuXH7JCtFSPScxHduM16xTJ7ZOkYMx9HDcyq6pu9S4fcbI9caGd5PucUM7jVC8tNZercPC32Yn3Mnt/pQ=,iv:dhNlBY87Lkn6tu2W+WM0FBVQ3Z2tJM1IjdrgFAnny0Q=,tag:IrJ6E2lUXLjcjQscWDr0jg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
