---
- name: Join Kubernetes worker node
  ansible.builtin.command: >-
    {{ hostvars[groups['control_plane'][0]].kubeadm_join_command }}
    --cri-socket {{ kubernetes_cri_socket | default('unix:///var/run/crio/crio.sock') }}
  args:
    creates: /etc/kubernetes/kubelet.conf
  no_log: true
