---
ansible_user: ubuntu
deployment_profile: poc-two-node

kubernetes_version: v1.36.3
kubernetes_deb_version: 1.36.3-1.1
kubernetes_minor: v1.36
crio_minor: v1.36
cilium_version: 1.19.5
gateway_api_version: v1.4.1
helm_version: v3.18.4
kubeadm_api_version: kubeadm.k8s.io/v1beta4

management_interface: eno1
provider_interface: eno2
pod_cidr: 10.200.0.0/16
service_cidr: 10.96.0.0/12
cluster_dns_domain: cluster.local

kubernetes_api_fqdn: k8s-api.dcn.ssu.ac.kr
kubernetes_api_vip: 192.168.21.8
kubernetes_api_port: 8443
kubernetes_api_vrid: 51
management_prefix: 24
# Replace this before execution. It is not a user password.
keepalived_auth_pass: REPLACE_WITH_8_CHARS

openstack_public_fqdn: cloud.dcn.ssu.ac.kr
openstack_public_gateway_ip: 192.168.21.6
openstack_internal_fqdn: internal.cloud.dcn.ssu.ac.kr
openstack_internal_gateway_ip: 192.168.21.7
external_network_cidr: 192.168.21.0/24
external_network_gateway: 192.168.21.1
external_allocation_start: 192.168.21.100
external_allocation_end: 192.168.21.200

services_repo_path: /home/ubuntu/openstack-cloud-services
repro_repo_path: /home/ubuntu/openstack-cloud-reproducibility
services_repo_ref: 13b7806e76b60c5f49865b4a428df7fe32c2af9e
allow_poc_quorum: true
confirm_ceph_device_wipe: false
confirm_provider_bridge_change: false
