pod:
  tolerations:
    mariadb:
      enabled: true
  replicas:
    server: 3
volume:
  enabled: true
  class_name: dcn-local-rwo
  size: 10Gi
  backup:
    enabled: true
    class_name: dcn-local-rwo
    size: 20Gi
manifests:
  cron_job_mariadb_backup: false
  pvc_backup: false
