labels:
  server:
    node_selector_key: openstack-database
    node_selector_value: enabled
pod:
  affinity:
    anti:
      type:
        default: requiredDuringSchedulingIgnoredDuringExecution
      topologyKey:
        default: topology.kubernetes.io/zone
  tolerations:
    mariadb:
      enabled: true
  replicas:
    server: 3
volume:
  enabled: true
  class_name: dcn-local-rwo
  size: 10Gi
  backup:
    enabled: true
    class_name: dcn-local-rwo
    size: 20Gi
manifests:
  cron_job_mariadb_backup: false
  pvc_backup: false
