apiVersion: v1
kind: Secret
metadata:
    name: openstack-mariadb-exporter
    namespace: monitoring
data:
    password: ENC[AES256_GCM,data:y07uF3dqMQrhHFQfHCi8IFSWFY516Wpzfngpe97m7WVtTGvL93IZ63lv0GVMZ4smvygXmlbZ92MOMEua/Qiwyg==,iv:SsOz1ayYj1eedXhkzqbM/nc2Rksd260g0gOZ9cqP+nI=,tag:7HKBkJWBjl81oYQyac+LEg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAydmY2MXpuK0pFRW1hSHlm
            ZW85SEE0bEpYNDlGMEVwcEFUNitzUTR4NjB3ClBZWTltQnM4cFBvMCt0ZitaWmZq
            aHUraFNoaGROcG16aElBMWZCM0MreVEKLS0tIE1rWGlNcHE1Nk5JNXJRaUo0Q092
            dDZlVlJEZDN0YlhucEw5OExZbHFZYW8KlHJtCFQARCebpTwXQekpcX/Xlrd4wh3R
            NSlWnPHj4ValsB+0rNNx2GQaSproPVQKyWvpI7jh7S1gavESj/5MNw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cjaxalqu6gs9mev9w0u537793ql5t0gy3a6d9qn0265s49k9ss6q7flh4j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T07:08:51Z"
    mac: ENC[AES256_GCM,data:2esymyi+kb16oAjwGTvSHLcUpw0aS269+3C9TIwMM9ujc8dmf+ZO3wT8OLj+4ZhMhWGFNmEmN/Hf71MRvnSIV+w2mPWbhd4q6MRIEYVmfF2z688dohhCYdnXkuXFWPtCsW2TrwBM0F3o9q2DP+Decr1LY+UnN2MafWbQbNOfjnE=,iv:7hG95zpVKzerSZZqy0h5vvdciXTayFv1uujJtXrJ7ig=,tag:3GbGCG5aLzSDNQEsbwi2og==,type:str]
    version: 3.13.3
