apiVersion: v1
kind: Secret
metadata:
    name: prometheus-openstack-exporter-keystone-user
    namespace: openstack
data:
    OS_AUTH_URL: ENC[AES256_GCM,data:WVN1bRA9iRPRb7htPlOwjFTTZPigmvs42yTc2fCMjPE5NHFMJRhVbeWK0TzxCfdxLwI5O2Rj7J+UCUxvGP8pvNxLx6KqOVEmdZ1Gsw==,iv:e/1iVvtkD0hpHwR6oORZubHGe7Bix25qigqdh93mChg=,tag:N8t4iGOmtO5dkRWt6jFEHA==,type:str]
    OS_DEFAULT_DOMAIN: ENC[AES256_GCM,data:gRdXvu2rvuDOuVoW,iv:vbacWcYvTB0uhHReuQJESI63WXbMthBN3vIHtXgjGYs=,tag:/zIDCmHDY5aYKahs/jc4Fg==,type:str]
    OS_INTERFACE: ENC[AES256_GCM,data:LcCre96+GJXaTZcq,iv:FqLSoLRs0LP5yBXQUNKzLc5zDnPo2BATEOCULGQ4LHE=,tag:Skrpl6crCdZ/JXj0wQln7w==,type:str]
    OS_PASSWORD: ENC[AES256_GCM,data:Bq4HJegVpnad8X1/yIg7Z0Cmf1zfLZ2llC2rLNt+45h/21wkBQ9bdI3ICR4ru7dTYEVDmEGU6C15ElQHBBrayw==,iv:ZlqYnRvK2TChfWieKj/QrDPrDJMtTWh7OqhFjXi+JG8=,tag:kr74KDcR46yrVI8QudJ+AA==,type:str]
    OS_PROJECT_DOMAIN_NAME: ENC[AES256_GCM,data:QI6tAYLanQhUd71d,iv:fGv4i0Z2RQCLwbyAIUtRA7hT9hqeACg3zqHdtydBWR4=,tag:Uql91csaYzEiGSZwPOmmkg==,type:str]
    OS_PROJECT_NAME: ENC[AES256_GCM,data:8wo7TCrYISnmkyP0,iv:1rFCMlc28G89KR7vuhGr5S7rpb08Vi7KrLUXxrybB0g=,tag:5awUrRHxutiGxukWBpjKlw==,type:str]
    OS_REGION_NAME: ENC[AES256_GCM,data:xHDHDddrDv30xOBY,iv:r83bvnk/iTO+W2/wXagwhZ9ex56vmKxZxl0mVoe2DSo=,tag:PAcLnOltQGSwZNX/vHdUfg==,type:str]
    OS_USERNAME: ENC[AES256_GCM,data:Kp37V3WPhyLKA34BZngMBO3dLQodL5e1DlqnbF90/3CxeO0q0cLt3Q==,iv:qsuy2eo0cdg0yya1It94z6GO3aISLaANliMtJuAENNw=,tag:sQze3cXSHn2qY0xoJDzxYg==,type:str]
    OS_USER_DOMAIN_NAME: ENC[AES256_GCM,data:hXoWt2V5Qq2FW8qA,iv:Q2KNt6k3xtcmWXPnPIxPoQtjMXbj7job0YNSAAIhvYc=,tag:svG0zs3D5A1xeTZJ653S9g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5SVYrZU1zNitQc0Ryd1Ni
            R2dJY1ZvRk1IaEpFeGpQTDY3aDEzdGllblhJCmpLRytQcmdSQmdTQzVCaTRERjN2
            ZjlCZ1JTRm5pUUxVazI0ako2SGpLeEUKLS0tIHloRTFucXg1eFNSQzhYYnFkdGdh
            QTJIZTZLazlTeTNhTnFReVZNNHNkK1UK3euiPZYGBZG9SpTDl7S3GbsQTnabDzrC
            +LcL5TgKFIwB6EFdSrctuSVutrSZHLdj7nrEU8bBwxdDqqdnh8lzAQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cjaxalqu6gs9mev9w0u537793ql5t0gy3a6d9qn0265s49k9ss6q7flh4j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T07:08:51Z"
    mac: ENC[AES256_GCM,data:1v2KtYTrXYpu4MLKGIrpe8H362fT5eDpL+5k+vr8jys4nv/mRcOAFGsiPMyfqbm428hJaLmvZVLt7bF6qZAMHK2xd/gZelrw2WOlh1KRBgDCfPjkUjT8BHBjDK0u5is0r0FyMt+CiYSwIdfUCe4JVov5LRBMsFFuzjyT9bLPqFA=,iv:oemz0JkNnt6Y8j29sr1GvslxaytU97Iz2yPDZeMyZKU=,tag:QQsyj5IerP+28Soui0e4pQ==,type:str]
    version: 3.13.3
