apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: openstack-internal-gateway
spec:
  blocks:
    - cidr: 192.168.21.7/32
  serviceSelector:
    matchLabels:
      io.cilium.gateway/owning-gateway: openstack-internal-gateway
      io.kubernetes.service.namespace: openstack-internal-gateway-system
