ARG HORIZON_BASE
FROM ${HORIZON_BASE}
COPY dcn_core_orchestration /opt/dcn-core-orchestration/dcn_core_orchestration
COPY enabled/_2210_core_orchestration.py /var/lib/openstack/lib/python3.12/site-packages/openstack_dashboard/enabled/_2210_core_orchestration.py
COPY dcn_core_orchestration /var/lib/openstack/lib/python3.12/site-packages/dcn_core_orchestration
