apiVersion: v1
kind: Secret
metadata:
    name: octavia-valkey-auth
    namespace: openstack
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:/y3a57B3oo/hd4Fdu3Ey/nARm7jLJcRO7PXfW/IZfWLe/fxVl1Fzny+yFr0rg0OD,iv:E7SSi2TcbVBuRejTPOZwx550YuxnLYUuLGIdNQFZowQ=,tag:jdXeVKc0WYalg2T5e/DucA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVzhRMVk3YXpJdTcrVjJM
            aGlXMWpScFI5OElIK1phUjA4Sjc1bG1ScVNzCnNHbmozeWE5QWd1ejZVejFyQmFQ
            TFovVU1oMFBJdDBQS3JSRnVwajNhOTAKLS0tIHJTbWE2ZVN4SlFua0lHL2ZTZU1M
            Z1UxNEF4WDBTcEVpRTVQQnkvbW9IOUEKEMBnEG53e0DEn7eimhpbgL+IJunZSev6
            FAVOzE2c8zBSJjokjApXL5kez148L5Q8yMHGKQ1D6K68YGw+Gu3Ejg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cjaxalqu6gs9mev9w0u537793ql5t0gy3a6d9qn0265s49k9ss6q7flh4j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T08:35:45Z"
    mac: ENC[AES256_GCM,data:5VN/iMERvRHkE1EpvS1boQ7QRlGku7mE26DD336N+dsnDwpeRWgyEeKtObWYDwhSaXKkMYZZdZzv6K8yHSj1EqHaNC0GKUOsh20MWfMZUIDQ53rO5Nhg0+wL9E4c850/VL2eYiLnIVNwSF7nX0/sQOzws9uHAUp5sxoj/1JaDoY=,iv:Xm8B+pC2PAD8L3D2uF2npESVaAvGJXtjRYpeJ0LIOvQ=,tag:kH4oL7YVEC9jCzIIElHVAg==,type:str]
    version: 3.13.3
