---
all:
  children:
    control_plane:
      hosts:
        cloud-controller-0:
          ansible_host: 192.168.21.10
          dns_role: primary
          node_roles: [controller, compute, cinder, object_storage, ovn_gateway]
        cloud-controller-1:
          ansible_host: 192.168.21.12
          dns_role: secondary
          node_roles: [controller, ovn_gateway]
    workers:
      hosts: {}
    ceph_nodes:
      hosts:
        cloud-controller-0:
          ceph_device: /dev/disk/by-id/REPLACE_WITH_STABLE_DEVICE_ID
