conf:
    aodh:
        DEFAULT:
            coordination_url: ENC[AES256_GCM,data:j/EFuvwr5N0g5fbZgXyGrIyjGwTcO5BA2JZBXYYzGWLedvRqxv0bVdvphtJH6RT0nKCO7hEARBjZjUcHUVkNubf7eLSsUxmypphDbXkUIFhA3iHErFqEbqtfr4t9IDxQupjpS/5N3eJdp88=,iv:A/Vgfgpmv+0D9Oq9wm4sbGtQbmfGKhtzn9U2EVTOhj4=,tag:QyMCnJslaODPFFPchoiRHw==,type:str]
endpoints:
    identity:
        auth:
            admin:
                username: ENC[AES256_GCM,data:LYSli/A=,iv:bWg9dP0eaRpthiNdrNC+Xwrixmi1h5Ho3+6v1B/V/C8=,tag:PAB856B2k5sJxrsgBpH4SA==,type:str]
                password: ENC[AES256_GCM,data:+V2GZPDitKSbamPe0qDnh1u/Lad1G53I0c8HXDiXhMoeJHHjOtN85TwyWIFyiO0CTcsIea8sEX7gKil7j7AssQ==,iv:CuAT4CQq30Hbn1WIwEXGBQQhx0uSW5Tlo44SkGMWvy4=,tag:0v9MV/C8qNXcOyQdUuF52g==,type:str]
            aodh:
                password: ENC[AES256_GCM,data:BBR/S1YkaKTqOGdf/VWKd1g2tO38dZ2KG3Lx7qOjbA1VBiQsnF9Fkcw2KOEN4t5X,iv:KYuqzUppQn1hix6eL1nqBqxtdTeDlCe27CmJ9vwumFE=,tag:ZCW9vgA+r5rEDAab+q9BJQ==,type:str]
    oslo_db:
        auth:
            admin:
                username: ENC[AES256_GCM,data:Uwexeg==,iv:K6XfnH5ghvpNloT1yFIK26/Z53+g1q66bX2lBTY6Jtc=,tag:QYgZR4YJtiwtIRI9hz+5zg==,type:str]
                password: ENC[AES256_GCM,data:e5CeUGRCq1stGGUriCKkG8DkzcA3n0cwbxDH/pzV22BsdTvJFibb9rRHn06AUdgFFjb9gg4bz7ISvWpBnLnf7Q==,iv:VFIJDG8utTMRImbW4VC57y4Xcb0iYjhrUY1+iIuQMiM=,tag:av2DY2JhDdJSQs8hT/TIsw==,type:str]
            aodh:
                username: ENC[AES256_GCM,data:29V7lw==,iv:TJVRoFD2Vety1rw1iaiAtfdbmEgdpeJ5A/ckXdVPKX0=,tag:73I+vEv3hE27p2dcvmxVjg==,type:str]
                password: ENC[AES256_GCM,data:rNhTicqUjp3DPd4EWEx+vCOQJt0LQTz5kqOKyiwa8KasssnmKFFWV+W/UEOgz+/O,iv:tSJO/MCEBvwo8RkS/uOaNV1j0SqLJyb7GqAdqACJ8C8=,tag:+/m+a5vuftq+aBRGU87hhA==,type:str]
    oslo_messaging:
        auth:
            admin:
                username: ENC[AES256_GCM,data:yahDuKJO1pg=,iv:uGP0nCVl3nA1r0buwt1bRzG7C7VEVnLiRfQgk5zM3tQ=,tag:6sTR+Rf3Bx34mA52pHPdOA==,type:str]
                password: ENC[AES256_GCM,data:SXOT8tzM5SZuufg5tWIHDEH9FxYDjLH0EkbxiAIsRbepNxS2ExbxgjBJc02qlLghNTVHTrxYPkGUhzB5d1XyHA==,iv:6l8WLr+nFOJOHoX+6qM7vfdfrxiYTXh3dU2suQOw6IU=,tag:yI3+FoDOA/4Twff4RxaHFg==,type:str]
            aodh:
                username: ENC[AES256_GCM,data:Fz3IhA==,iv:JWhdF0PIkRkzV+ox6po6OgwkXStKHh5NZiZi1ANdARo=,tag:JbWDbYQBwlGkOZY+iMrARw==,type:str]
                password: ENC[AES256_GCM,data:/iOu0L1BWrVPtkcxvNy79w4VE6Skrl19I5DzjWEM3Z0/u+QxWPKkaK4Cvt7XjRmd,iv:wPEKJPqUq9lVGn16LN1Q/TbogjFrP4dCKzDYrLTpaOI=,tag:BOSlc9+iOuYT4v2PfYwOMA==,type:str]
    oci_image_registry:
        auth:
            enabled: ENC[AES256_GCM,data:1+CEsA==,iv:2YCoRTYWT//zgX4naaQ6pN6GYyG45TdwP+1vVoa5xfg=,tag:qA1OymF7cpPtv0d5Z2AweA==,type:bool]
            aodh:
                username: ENC[AES256_GCM,data:zQIGP3Q=,iv:Vu8Bh8D3TWLed0fWRHFpfqvam7kSMTyT4nMbKZ30peI=,tag:e7x+n4BzaM1uPwvixZb06w==,type:str]
                password: ENC[AES256_GCM,data:pFp5E9rMCNGNJlLAlH+f8Rhxg8JCDtJ9HxS5WuAuBU0=,iv:qSgaBbuz99unko9JyOSHU2A62eqz6V3hmwUot0n0dl0=,tag:T9PG1z8rreFk4bdtzR6YsA==,type:str]
        hosts:
            default: ENC[AES256_GCM,data:Ubmr64YBzAHT1k+A2u3nrkpoac7xfA==,iv:QXfwKXFhUQgetSJkpXVDwgSoIqEPYeBdgiyReMUGMok=,tag:xGntt7ZDuMN1EXYvg3gFTA==,type:str]
            internal: ENC[AES256_GCM,data:Vr4mwz780QILthvm3mFTt7XB6jUtzw==,iv:uzdb4I/RR7H4x8r9wGuXDoOHgJ10O30qQTqKgbver+Y=,tag:UES1yPoZsZBBzluX4MM1Cw==,type:str]
        host_fqdn_override:
            default:
                host: ENC[AES256_GCM,data:BiAEwbvUSp1g6BEKZpmeidE2YA1FGw==,iv:I4jdeMvvCDmwzQEReTWCylGqblrW9J5duRhHF+hUezQ=,tag:8jmX9W9l+ACMp8W8f5wxkQ==,type:str]
        port:
            registry:
                default: null
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOEpFQllrMisxSVhpZSt5
            eVNpcElTblA0dkZHVUZHZlU0K2QyanIxbjFrCnhuVmZjWXU2TkQ1RFBBMXpkYU1q
            cFZHQ1NwczFXS1JHRWdSK3oxK201VjgKLS0tIDZKK0dWUDZCUEZzcXE1K1pka2M2
            WUprOFZmUlJzSjF6T0YrZDFIY3ZkUTgKzYPSeJ94Q9Cq4dEk9YKqZYgtbNLPPTm+
            AshFZehsbc88LSBCx+WkFlrlOS82IhKu5e0yV5oZ3AhvEM6kKp5nkw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cjaxalqu6gs9mev9w0u537793ql5t0gy3a6d9qn0265s49k9ss6q7flh4j
    lastmodified: "2026-07-26T08:49:12Z"
    mac: ENC[AES256_GCM,data:MBFy8zpsvwJ8DsCb4oO0+cM5PrwejJWUzGg0CM2lE63LQC4uyOkNY8O0uU6WOyPAaCwa7Y2D1pqJus6/fHXgwVju9huEi0fX8QmPma4ld3R6i0p4yjlIRJShy+nQsQcSr6lmF4FCBGCh4OtrYh7d567e9W/GHZF74E7R+MIeDEM=,iv:msq7AzpSEeXcu5WgHOGX3qVZtImSlVOhJRG2hAKtq8o=,tag:qweUV2/WNjbhVzjrgPtMNQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
