conf:
    barbican:
        simple_crypto_plugin:
            kek: ENC[AES256_GCM,data:COYDuGkKn2P8OypkLhCoOkHtPKhdIzkXNPOHACuC0PF0uELbmpzO2SWjsuQ=,iv:qBUe5O8GFdsFmWRWQYkoaO4xMgbOEXCagnMSKZO+WJw=,tag:ie69rC2Vme+cI0NG9orDMw==,type:str]
endpoints:
    identity:
        auth:
            admin:
                password: ENC[AES256_GCM,data:XSZX/tVpFchRutOmfWlV3onsE4z2L8ay808/8Wb11OMQzrGijP+Bvqpq3hALsf9qxpc31qfmc9OAOVECP+Xgvg==,iv:QiE/ybNcWtUFnRK6nER3QtUeRfu7LMuEYIu/aHli4uE=,tag:CQoIEBsYZT2mC0UYBaBWnA==,type:str]
            barbican:
                password: ENC[AES256_GCM,data:q+1hnZ5z5esQ1lfod3ntkiDTE/24wGx/R0aH/kBiHLoZvXDHzrj78qNeGXozvtcb,iv:eRg1QbDFYEyJ19ok8FlkBrGg4BiMxssIBRL8MAYwPHo=,tag:D8UeYxZwHXTUvUh+9DrYjQ==,type:str]
    oslo_db:
        auth:
            admin:
                password: ENC[AES256_GCM,data:UObyVyI1422Nh2EdCKjC1FLDqQlvQOiIbXgVMh7VyCypHwLW/s5bSoIVt0JPa9aiHtRFVYOlW+Sg+9myJCK3Vg==,iv:KBhvtJQ3S6rTblOwjbQzKWe8yUzDvEWcsT4LJavkbyg=,tag:JsNnHTuSEqW9KGpoyMI7jg==,type:str]
            barbican:
                password: ENC[AES256_GCM,data:Kxuhp3Nvdsi+j3kt9K3UuLEPn4uYoBNcEcxiALhxTXyzSF+1sCp+PvlpSsU/vNQp,iv:hFbi0cp1QWBmYd/7tRcrWD+hBFbxhQ3d5SsjwMhYjM4=,tag:oRP+6PtXM/edKF7Nbbjutw==,type:str]
    oslo_messaging:
        auth:
            admin:
                password: ENC[AES256_GCM,data:xO9gFnNO4yoyZdRKV2riajL+UvDhS4pkCjCw073txkX5r9bSLuCTWWBjPsGzYAVfW+bH+NilZK4fppWtWtEbzA==,iv:wW2k2tGZVzYKz7YauKx9IRfWo/xjrX4B/I+VjxA7VOc=,tag:f0cP/YE/pvNE0xXryUB9fw==,type:str]
            barbican:
                password: ENC[AES256_GCM,data:qWpq4ZVxbRpd2XUeNFxYnSTAPDC58vVhhdwqhUGtoqS3V7O/9E9KRnpWJQ/lHaAj,iv:99sG33rXMe+LMcPAKIhxSQjxAW6Gk4IFO0eEsRBjDb4=,tag:0eUguU6zGzE+PjX8jCoIzg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3MFdVa1g4d0hEeElJdGsy
            a2xkVUUycjRqdWZZMUt1VU90OWpUVGUzTlFvCmdQYUpENzRnVXUzQ2Jzc3I0bTIy
            OUhsbHFiU1VxMmNpWUpOZTBCaXBLK3MKLS0tIFBhbFYyaEU4L29jbXZ3Y1pUOFlQ
            SW5iNW1abnFsM0NSZGtNUjFPY2tGaGcK6Gado0h/7T+EEWQqe44ugep9WD4Ai4n0
            2QSvKOWcCbDwotOqX3fxCbdVOXKA/idXr0f5E1dJRKLnjQKpR0vfmw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cjaxalqu6gs9mev9w0u537793ql5t0gy3a6d9qn0265s49k9ss6q7flh4j
    lastmodified: "2026-07-26T18:24:12Z"
    mac: ENC[AES256_GCM,data:JSblDxciTzWJ794docR8gMOMybcddk5hkBdwGP8AMVb0rngZENSA3f81svjOC73LpLJiEGlt24qdqY+rR4NT15ldDt51/M4KcD0Q4tADZ0PwwbrMaAfSxtu2pGRzXmGW2dzXc26dwTBl2BBo82pDoe6d8NrVe1AHTt+u2OojKrU=,iv:ZcaRApowPibJbFsTz3JP31MmIjoUnkf5mUm3OQ6e1xY=,tag:pq//2XiwBnr3AkCgY6wNAg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
