conf:
    ceilometer:
        notification:
            messaging_urls:
                type: ENC[AES256_GCM,data:lqNaxI3zTO/BeGA=,iv:Nas0Lmz/yNwQ8m+WMudYH+KEFc7UiDptVPIJ+4mguzw=,tag:86S4TvbbSlVAG9stApctvQ==,type:str]
                values:
                    - ENC[AES256_GCM,data:AFTsywtbs8p6Nq5lXCd3NiaqfCGzGhU160E/O92AwwyYKlvhCeulfKtW53GU+QM9OxLmcFw5+rteaNDcdnuOnqfvOQXdxRkZCnXcYCXMvqhcONf7cDqVFxR22N5WvSFNTxIQkMrZSDPOfBgirYEjmkmbc0eHKw60XH5+KPY=,iv:PlsocIwf5HegD5WCvBnXe2loi0b2yxXQrcJpOUmRmZM=,tag:EDcWGdnKuN/OiNW3Cqdk0A==,type:str]
                    - ENC[AES256_GCM,data:+19EWjnHlhomaQQDOkjAMS7Ik5Tu7TXCR+5xyJErA3WN3yvOXlBdrfmyZVgfDNmGlxL7/5qySn4iGf15iQ5jclVIkmwqQd/g/C/oAXKuwTGbbw2j38yNMeYRXUEvjADA4OMNw7HGf8zSE0vKZJeGKzl9ClNHwyNWM81KpNQCS78A,iv:U2yX/mS9FAhQmiQXPRfwXMVoTZjWm22tHN1d9LIaJ8c=,tag://tL7B4dCMa4z2yUHDG+PA==,type:str]
                    - ENC[AES256_GCM,data:fNjfA/VoQaBWc06KLIh8jlOlw1zKcaB4GJ8dMfz9bfAqdZNfMOdm8yY+qPEeSR8y1c8aRVdmcPJw+P/d+OfY52W5zqDCcn7NB1HzPknzlTqOp1Bfz1r/A6uT2fw9XQigL2pOl1AByhBBmtzch2HqZClTDtc3iLNHGIgNfYa0HRcc,iv:XOaDea2ph2hsibPt1SbXE8WuasSh1SQC54p686EoJ4Y=,tag:+LsRr3b9X/8B7tNfW9DFhw==,type:str]
                    - ENC[AES256_GCM,data:vmoAhUzXv0W8d9I8XWauDBYPwesuytvbgtDdjQ1STm8R8pTWfVXQ4keAID15zaGUDGZZMwqps9U26NKhsBibtRKHnuWVWf3d6XQ+Nxf2B7KudHxhJ9pQul863GSKcLY8sc7Uu5dZ89HVIzHwyvzYPaXrzmuPLjtu3+SaobL5uRzLTS4oAQ==,iv:KOanb58k3cF3hgMpXAfd6SHpJjKnjzeLriDVjWcC9iI=,tag:9gNwjc4faL4bG6Cov4AvDg==,type:str]
                    - ENC[AES256_GCM,data:QUeS7BKX+oruAKpNWRWNj7bAhq7LwfftV/tVwFegl/6Yi0dC+kk74UH9kjQ8wIEZXXHDcTkR21ILad3YQVRlSKF9gOP5JVFefPzBxU0xz1M1wAky+AkxM4hwK5EpcXHZzrp++TV8b6H5rJizyXZw9WMqPhAc6J6jJ9xyoJtJibvwP5U=,iv:fZKylfZVwZOpaNOnLh9kVynK34+Slw0UBFi8EM39d1g=,tag:aMApEHuDmKAHyc8g/0Onbw==,type:str]
                    - ENC[AES256_GCM,data:Dqr/ZPxoTBz4s9W98Cjs5E0pNnHZiklVZpZmOYIgFJzMqCMm3gp09mDMAXoHKf5r2OykXaUsEMnYRPFUyUSj/uwyPntY9uNUSOkkfMqjju4b6Wf+WaYAfdw2u/OP1lF62g1djkSMv7a1zdXBt0qSeEBOqWXjkdKgvoVsTmw=,iv:wiKDIKhIjcCdkN6SN9Wa+0SRU8aYK6Rocdw0vGno5S8=,tag:NOqB4Az4jdw4K1DehfoYXw==,type:str]
endpoints:
    identity:
        auth:
            admin:
                username: ENC[AES256_GCM,data:zgtaBNk=,iv:SZr5VqhffQtoQsIdRWBytCu/ciNaAcH8DbzExLcaTXM=,tag:RI5PEEAlqyeBX2sR4AR7lA==,type:str]
                password: ENC[AES256_GCM,data:4XfsWnV1z6BpomPU6pdjYeFmyNg6o5xIT9j3cvx5dUDp24LyhENrJV+3wUOPwoiNAx2mXi33OddpAtLHugr6pw==,iv:9HOqohHipB9lW6hjgcFIM8crJWnQc2sf4AKPdrmKdx4=,tag:3MkgP0WP3F1t+gqSOXTULg==,type:str]
            ceilometer:
                password: ENC[AES256_GCM,data:tz3kVXfnprX5lB5/fOhumq0HP5g9+843aD9fGQcMhEo9eb+AYQ20CMyv/VGQyltR,iv:xZ9jdODN8lYAX9VXsS5HiTOb3G1sjvvYttREIxDP4qg=,tag:6nO179BjT2D4a4dvhF6ocw==,type:str]
            test:
                password: ENC[AES256_GCM,data:NF15g8C1ChP5ei2/lYdtF11BR5/211auCwCDiW/9CRkNKw8kW1PjkrD9D+5+sr/t,iv:Mu6huv1JZIeYN/N88YXrOm6KCQvLxQMch5k6HZ/9Oms=,tag:7it10pDe7aV5tZurK9vzRQ==,type:str]
    oslo_messaging:
        auth:
            admin:
                username: ENC[AES256_GCM,data:H6SyWneBM4A=,iv:4R/z0tSBSSRU3OrOpFW5yG3ZiY5x+6wdjZM4Tx+IV6g=,tag:78mYq9WO9xacOIi2FzErHQ==,type:str]
                password: ENC[AES256_GCM,data:AbLeDIbbmQ5q9pthOh2FJyXhT0Ac9ryPn6ENElRxstNiINgtdGY5+hO+7C4LX62nYi1o0jwKW1kdidYXjZIcaA==,iv:G41cQP5WjO5SKYQ+b3Vra/F2JLyI+LM6urczZFCRNbo=,tag:EB6HlGrMlP+MSJI3891Uqw==,type:str]
            ceilometer:
                username: ENC[AES256_GCM,data:gMiChCZLIhrdvg==,iv:hneaQApfdyyPHaR+Z6ucEPmE3+FhHq0O1FRATx2s5/0=,tag:iyfEuXJJIg/CBTcViCL9dw==,type:str]
                password: ENC[AES256_GCM,data:87WjXDrRtFuHz1Z4o8ngc9nBJTIB38/ZhZ/CrSC9ZFR+XurryJ6S/1IkP9BpVh0J,iv:j+3TqZk18+A93HWukqJdDR+aHtFNzagcSlnf2uAma9s=,tag:O8FeWtZp0n8c5EX5eajLPQ==,type:str]
    oci_image_registry:
        auth:
            enabled: ENC[AES256_GCM,data:jNoSnQ==,iv:vQOmEktzextp+UF7aEi3ex23oCX98XuJGQEelvrcU9g=,tag:AHRGTzjumbCAv4OjJ85JmA==,type:bool]
            ceilometer:
                username: ENC[AES256_GCM,data:/cYZBxI=,iv:YH3RdqbQmMQ5DzQ2SLaCjMIJMXuF2GKDjE0w6JBvJI4=,tag:mvEFIrosZ/UdJx8wc2Spig==,type:str]
                password: ENC[AES256_GCM,data:zrDpNfrdxV2qIzQvvDnoeREEfsfVVKpOwlp/5iqCIwI=,iv:Vrsj4nchd8GID79An+bOmDjuq3O68ysLjNIiYX72uQ0=,tag:wLHDQLqMEvsQAK/lKyjUaQ==,type:str]
        hosts:
            default: ENC[AES256_GCM,data:sNNmjmtOyrfOQnexrEclJUSIAH0vAA==,iv:Z6cuLMk/byKtGRSlusGgW0DthDqGXpHKNbchk9OSUyI=,tag:VC/P4e78TKw6Bbm1pm/c7w==,type:str]
            internal: ENC[AES256_GCM,data:9lxcym/N0pwyKNb28XoICuCjBlN6GA==,iv:CgfB6vk3FNYR9QUGhSFDldr3+n0EvZoX0l7454Iwvio=,tag:YY/OFle0Jwzevq+eVG7GKA==,type:str]
        host_fqdn_override:
            default:
                host: ENC[AES256_GCM,data:XH/nNpLNaomkpsjZClNb9H4u26Nf1A==,iv:dm0Egx8nOYwbwH0zMmLbUnl2iPl52kP290U9Cp8JVH8=,tag:R/KM9ojI84w6iajva6u3aQ==,type:str]
        port:
            registry:
                default: null
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzYS9INUZhY3BQVFdaQ0dt
            WXFEUngrR043am1walRNcndDeDZpa2VvdFhBClhBajFnSXZuWllwSWZYSDJpdFJq
            Z3BoWWFYbW5CN01rUVc2RXFNdnlzNHcKLS0tIFJWSG1zeUVIQ1JqNVJHclpWZTRV
            M2U3cy9IcDg2SlczOEd1dlZ4M1hudkkK3Fa7MeQox11QOoMiuH/P2+d+Er7iNGjW
            GfG9iuhx22ivBGVn0rKEQoTFcuyULRbTBaBkm1fKppxvmFmLHqirHQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cjaxalqu6gs9mev9w0u537793ql5t0gy3a6d9qn0265s49k9ss6q7flh4j
    lastmodified: "2026-07-26T09:22:08Z"
    mac: ENC[AES256_GCM,data:L/bXXUNqrRIn/fKjSzes7/ddfY5qPTbTQ6Q9bNxlimAGn6vQ1X1PtwPQzQt8NEaMkKtfADD751QvbYsKkoam6DnbbWX6ajb3U7/0/j6PSSS0hT0FcENdB9AJB+jjHXjAzdUggEodYMzkGhRgdzdZ/Imvt220L8rDPWhkR7n3qsM=,iv:LMmoYPKi2tHGuni2CgWnBWVwn+vWKbgpsdfnR4WGcGQ=,tag:q8jlgnpXQRM/2QTSM76OLQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
