endpoints:
    identity:
        auth:
            admin:
                password: ENC[AES256_GCM,data:yCd/s9vM1ymrKO/Zd1fOMmNq2QwrXRpp38ZZw8lKAtnxN3RYf4CfvN2lYEEtusr2HFL6FsRN03Qk/jhqp5wCQQ==,iv:f/jLfTiaK+07ZzEYFilM8dEdGFEE3xbaZXRJ/JmdqYs=,tag:4m15YoV0Bu4p9qTrERWtzg==,type:str]
            cinder:
                password: ENC[AES256_GCM,data:KjVkd7CM4UWVnQMSprAYjCXbZ57znqKYvUjQ7Jbfm3tw9nEoPZpKu2IOuNfQcnO7YzIal1XdBN7J8wTI1gSy6g==,iv:pfVlsT030yW4mLbV25ijZgmEsqUpo8mbTlYwnRDiLlM=,tag:L3xqah+aUciKaLuurwmVyg==,type:str]
            glance:
                password: ENC[AES256_GCM,data:sgj6BWVju2gOPTvXLP2H0JENA5WwJ3K4QoW27gR8BXY6pjwMN+AL1eD1ziOjEYhLG5LD1TdcbCEZKQx8NXEFNw==,iv:brYDi5+B6uZUsEgm1nCBHwZ0VcXlKU6oRq3oBPy33PQ=,tag:MR40PyXurNT5n2lDt6rlKg==,type:str]
            nova:
                password: ENC[AES256_GCM,data:/H/KTvXbdZzyy87j8PaHnXfXFgjHmHjYgBDJUuZ7ZLUU+WXX1B08yMK2cYofDGqqxHnZhoHR3L+zqxfPW8Vblw==,iv:zJehzKz3bA8NtZ1/7QhreUfmz4aIfwAcLTghuDJMRCE=,tag:8MAiZyOYESI+w9fw6Opjeg==,type:str]
            swift:
                password: ENC[AES256_GCM,data:gBQ1Ao1U3f41jFD1+/j39SywDQxbG9jKQ9mpj+lyOIW63AdewD3isO7O+OZ2by35Kgei8oYOzwzIa1dXZ26wcA==,iv:ZVYPx7WKRrCqn95V7+PPLMP5UYvP8JUv09xlwed05c4=,tag:+m8TSH1VEbviYkS4mIWbSA==,type:str]
            service:
                password: ENC[AES256_GCM,data:88gJ99/QhsbuWVqMWGpo+9mwRWJixPr8zhRsu5UUJQXB3wyb3kvnCL3zjs2tY8Yp4rH00bNw4U1mSNtZw7K92g==,iv:0LtxEpdcUxcyiOSno3srJ4OkLNUQVzsq0hagTGauLUU=,tag:3h/8Z/+BG6FKbO2v34K7/Q==,type:str]
            test:
                password: ENC[AES256_GCM,data:rP8bLNJZAyCBfIcSbXtPfkUT+oFTQ0gh+0L6D4J/M1DjPqbJkUzR0wdCMo9B17Qfw4bijJWv8uZaqrZGe7RUtQ==,iv:cXGxXuKw9l2uPARmltYR4zraM8/0JW667PxpipChWGA=,tag:oIRvDYJQpfABy80oAxV8oQ==,type:str]
    oslo_db:
        auth:
            admin:
                password: ENC[AES256_GCM,data:AgmygjNbZORCeioIDzBoxMVQ3cE2PC0qW0upRwp090F4plK+rfUJhHVf0o++73IyOeZ7paiObLsULULYcFc2sg==,iv:tKsJyc5fjhK6J4he1YgxUlIcZzT/nkbPXWXJyZVB5Hg=,tag:KJm0uQAa1wHmIVL6TywQhw==,type:str]
            cinder:
                password: ENC[AES256_GCM,data:GEKAKBT02sLF22NRihvCPYhEgWnnR2c61FD1U/NYzrLWr/MJYxnUlIOP7TtWhof0JQm4qySTwSSJrEm/uRG/Lg==,iv:bPw43Drx0e1QIhBMYYPN99OvLNmbKpIC6Dl/24wv7nw=,tag:azaGRDcFGFLBjcEA/ig3dg==,type:str]
    oslo_messaging:
        auth:
            admin:
                password: ENC[AES256_GCM,data:eHi3m0l/xAcpmefHoRtydkwNhMDrGBApW8+mvjSFxLpFeDVp6XH3/y/hoCtxIyV/Afu1EBKsGDpLGqLBIsyMBQ==,iv:mLYa9j71FZjV+gU/ZzKRcX249Rsc/257Gu31+Wy7hac=,tag:L1U4oRNwY7bArqWC+udWCQ==,type:str]
            cinder:
                password: ENC[AES256_GCM,data:2xjPV+YNRLC2z6zBhcHbOKRGvkqI3YNbpTiDrFjuBHduo2ZsbfeUo4PYXbBkM+RnkbPLGjmksCcHDogmLaFX1A==,iv:w78RW+laxFJmhCGzGazX7nG4SFZmgy3GGEZGS/gvD1o=,tag:bQZo3xitYclzFN8ZKyZ2EQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFSXBnYTZIVThIU1k5SXZV
            NlVzL05mSzRzSk9FelZmUUVCcHJHQmlFbkNBCkNvd3lWRkNCTHNVaTVxbk05Vnl2
            VU8yaDNWdFFaVCtXbGlTOFFJd2p4alkKLS0tIDRaZG5HOHNqYmdNdEI5UnY4ejRB
            MmlaMmhnUVByUHFRV0ZycEJ4cTlrV2MKfGC/TsmPQA5NFrBY7tqq4Wo15/k7czb8
            dm+7D58GLGhFkTQ9Dxg3L9xbknyIBBf6VKFOEQPe8+wKhiQxIhY0ww==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cjaxalqu6gs9mev9w0u537793ql5t0gy3a6d9qn0265s49k9ss6q7flh4j
    lastmodified: "2026-07-25T12:59:50Z"
    mac: ENC[AES256_GCM,data:GDTLi1gWsV/LM01i+AKNOnhN6Y4oxKRmXNlnilJbkmzD3M0Ch/MdWUTWARdLjpXx7QPc/1I/7Z7eDr9SlUkpD8pR1cQSCQVhDtpTZqFCrR2rZqOe4IsJKFs2WXUsEdKgqQkTRRCcHwtnpl1xDYyI+Yn28l5iBzuEcSKV9ya9Yro=,iv:Q+e1ZM/3qidci7gzPVwJl89r4wIF9uts0zU100cPQZw=,tag:oTaOjJ76DN1mj5l8yVC6vw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
