endpoints:
    identity:
        auth:
            admin:
                password: ENC[AES256_GCM,data:x95+N8iITooCIRvXZVB2d/BS9c/+BLBRTddy89sDmRMm2pA5IVPVI9npoKbHdS3wYPsJsG/7ch2RU1kizNhqmw==,iv:hkQf1K5gGHfH3WK7x5VoATwhOQwLTxomDjZvAhSNdDU=,tag:54heOk3Je8E3PwlFjp8P/g==,type:str]
            cloudkitty:
                password: ENC[AES256_GCM,data:5ahmQfqogbPYobrNhXHJiHFKACr2QMBmNK+sGJVGfKDkiyz+TY1iOnfNlXhNeLYu,iv:Uy4CNkzERGx53Kt2NniEsqfYOTx+Bv1Iyj+ikkpfJF4=,tag:EsD9m8t8lcF9q3zhLo9iEg==,type:str]
    oslo_db:
        auth:
            admin:
                password: ENC[AES256_GCM,data:niW+7/ip9DR4sQkUOcLukrPClELNKtxrLaoXb6JYU+9EkyVW3Dt7TyJqbaZFw0m77/sQDmSTu+6AlKpbyGeNYA==,iv:4qT9QDnD2mytmX/HTOYbXffwN6Yfzl0jahORTDuQlEU=,tag:sRsY+Sk9XsRSQk/sDdZhTw==,type:str]
            cloudkitty:
                username: ENC[AES256_GCM,data:wxUqtUoUSQ/9HA==,iv:IF2AGc8CDLXc9TPN+61XE2oAtEv1ux2mwOcF/oPob2Q=,tag:xC+KHGeBBPuuFo8HE9VyCg==,type:str]
                password: ENC[AES256_GCM,data:QHig9UzFcAn/AdxPPdwAFryizKNGPLIpFeWjWCCnuNnd/VJZD/VzqLjd7piTCjIf,iv:I8/HJXxYHtmvsDrf9iijk1fNuodiXop0LG6m/1+mzrw=,tag:wQk0wxFZC0Oav0fJ8d7jZw==,type:str]
    oslo_messaging:
        auth:
            admin:
                password: ENC[AES256_GCM,data:vbCZ6/mTQqGKPOt8XqIAdJtpdVVoDlCpQCNBpYl9KsKeLqTe3NHX9l1G7Esanb5OZ2od79OOlZ3tT1QImDIGpw==,iv:mfgcu+pbSShhlPvgOoJttKZNUezntsQaKXl+C9L7IOI=,tag:CszgCzjWq9B4SNteFzyddg==,type:str]
            cloudkitty:
                username: ENC[AES256_GCM,data:X7J9UYBVTZvOsQ==,iv:BR9eTfhIX7EFaVMP8B9vfNGKXFh+qHK2N3ylyrAKmJY=,tag:/q1ZZL71hYXyAlHm+oAVoQ==,type:str]
                password: ENC[AES256_GCM,data:niYRBMH1ikXALNk1Ls5kvyr9ohOGvxUfzn+jqxVve5PzVu3yuBB+CJUYnVgHHSUC,iv:CQJT9x6GDUwSNgxtW0/vn6PFQ8j0kaodRX96E8IOlBw=,tag:YOCuW5RSWO8/eCVIF5WQmw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUW0vd0dlenJiNWJhM1Za
            ZXMrTGhRQURxYUZrd0hXWHhucmVHL0F0OGljClJDQlFNUUZJUFZzMUVuT2Z3OXVW
            ekpLOHVnZi90eHlZTFNRcnlrcGlkSDgKLS0tIDFTUG5qOFZWOXdZKzZFeEZMQVRV
            RWY3cFFPWjczWG9QeCtwZU95TWpSYW8K3VB+YIedZGt5pO0FFLvdeSIkv6u1vTUh
            qkShMeJE4Sz/37braevEGIfg9fdnyxDtIvjYzxiaXnZzwu2O0JxOLw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cjaxalqu6gs9mev9w0u537793ql5t0gy3a6d9qn0265s49k9ss6q7flh4j
    lastmodified: "2026-08-16T17:56:30Z"
    mac: ENC[AES256_GCM,data:8JI8TUy2mbK+rWxgOFViptX8FSBmFpcAjRVwogp7sxQWSAtvwbpnXwSqL70HM6Vv4z6Qa1xf0EsnqGN/dGhsWgt1Za+OZcdq1ojDla7OQLwIWAuSzAW6meAppdv3cVVtnWtMH1d/zf70u0sagCNBnePh35EsjpnfnAJs+6VVJGs=,iv:g9/NPgaR5tzFOLdewqA1a1LrXPM36pSgpC1F+6J7NPE=,tag:+uUGKdIAir4/9CNFUaImEg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
