endpoints:
    identity:
        auth:
            admin:
                password: ENC[AES256_GCM,data:kuw7FC0cX7dHrjAPzVBvE75Hc85yUyV0IFA2Z9ezY58ievY+tYtwHG96MDwEGf0ooExc1faMIl+eNg+Nla6wLQ==,iv:puwmdItsjqiCY5trAB7EMBcq4gtuSmF69ewtX9L1Wng=,tag:9vn4OxM189lX9H8xKDNeMw==,type:str]
            designate:
                password: ENC[AES256_GCM,data:Ro2OrKosYptclXoEElLx1aYYp9fOZFOrCTZ42F0j5T0de2S+YRuxLEgRv55cXA55,iv:SGYwy32N8/nYZ5qgiw/nP0xBxAS45Uprf+CKcxV081U=,tag:lNZDpA79eDlhpPhQd96ItA==,type:str]
    oslo_db:
        auth:
            admin:
                password: ENC[AES256_GCM,data:2g3x4WFQCs+S4HlZz53cd2DzisJLFWeWeR6Zl+QsH1rtc6tNHrcu+Pw1GSNyeDQ22hN9MWlIWP1JJE9dN9O+rw==,iv:a/KBPIPcFtSCRB7KCILPQHzo2ka98ssAYKh0Z0OJrSk=,tag:dx1JG6/J/z+dCo3P2eu0Yg==,type:str]
            designate:
                password: ENC[AES256_GCM,data:5iukZuskmNiGiH08P9BqAskpQAh6HWKwZtPHrbdg1skFqUDv1Wa8HcoCkR6yFKVF,iv:RCDh0osqNMUnBU/E1xFM/KambvQgaLcJCRdV6WdKJ6o=,tag:ZK/YZVR1SJfCkB+tCS8ixQ==,type:str]
    oslo_messaging:
        auth:
            admin:
                password: ENC[AES256_GCM,data:P6C9AnHTjkELocUBAGqBAf28cbzrQ5qS3a6ar2px4mz2a6wi8vhEXY6Ae5Nc/rQ9qR5bTrIv5J/t1Egxeg6y5g==,iv:OI325NY60uFpKR/UGG0PR7KWdVmUNULaBVfeJU1MC7Y=,tag:Y23CotEiNEBniliblYLMBw==,type:str]
            designate:
                password: ENC[AES256_GCM,data:Sq51R43PcIhyoEF18dLpvyM8G3SReBVvFB8T/8zG2/ApFuC6aKEmq85SaKJKtKDG,iv:JyNL2Bvlw/0604tl2yfzhr1o1Fs6i6/sMOTDSpH8KSQ=,tag:90/N+J4fHBit7i4dPMOLXg==,type:str]
    powerdns:
        auth:
            service:
                token: ENC[AES256_GCM,data:94S//Q1T8Y9shLJLAKilH+uKje+4nloWTYoxrDYIfDyIVEFefXIGr3p/le5kPu4g,iv:GvzAoGkvH9qURTRxN+e0CMpMLejKvklKJkSvJ4fwyPM=,tag:AsYyaCme7JOoqEf7lchahA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZ2YwZDdFdGdRc3dQdFlD
            a09pcjk4S0FMYWxWTy9PNk1zeWR1MXhzMkV3ClFHUXpFZDMweUJLOTNsK0Rmcmcr
            V2VabEgvTTJ3M1kwQkF6czA3OHl0REUKLS0tIDhhVUFCOUtRSE5leldJV2hrTmJQ
            YkFtcFlsMmwxZENZUld5N0tVK1NtSlEKKC5hRx/N7l6oP6j8ManZq22SQ1I7yX52
            QUZ8SB49MXAlfXTLvNnzKT+oU62ddT+8ACQatGopxAhb4VD1crXOww==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cjaxalqu6gs9mev9w0u537793ql5t0gy3a6d9qn0265s49k9ss6q7flh4j
    lastmodified: "2026-07-31T05:37:59Z"
    mac: ENC[AES256_GCM,data:G8llgSwvLgeWqhpK1Pcjr6FP6u/LaLRjAtq7tJZv0WyiwAbxUt7CFQG+JOcB7z3+kwdmw1lcg0BRmHECZ+rbx9u90Df06JoFEPPtLX1iVCXsupOGuecL9KGaNyPtbgkhE7IYXNuPirQCL8TXWWD1Mnu6q/mfaQZ4g/5BKPrWiVk=,iv:9iWXPmxCgx2kV80RTGNTqpGeRgYfZEydB5AqJt9TlXU=,tag:D3S/GSSVVWCHlGGZDXmyBA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
