endpoints:
    identity:
        auth:
            admin:
                password: ENC[AES256_GCM,data:koxr5nqzvtmrq6i9BIS6lUynFBDz19BEp1Lh4xPzTPnVKbRWJRp48AMa6+EzFFylLySr/XR0Up3wOYPYA8mIuQ==,iv:2B0NRT/X3qz444yQorwHhDULeus5qTMZqYWNb3zCkfw=,tag:1IJpX2YBzVdzTfs2hfKg1w==,type:str]
            glance:
                password: ENC[AES256_GCM,data:qnXWZfjH5mJn4ts/PVWjPUQ7Mb1LZTHvgxxOxAaZeJZ/LLNr/mF9mRfQHj0nJ2LeyFp/XfMA7aGmHZ97ORchiQ==,iv:TxOJU3J+qFKOfmLWr01et2FsJh3b6Ljy0iYl0Lzz6W8=,tag:rkFe8AABZvGIiXz5MD6CvA==,type:str]
            test:
                password: ENC[AES256_GCM,data:Nl5EAZCGEcFvKHpipyrn5O6OVqiH4NrsSZpmt7aVkOyb52XyvwkActDBfozn3ACQi28upMa6CltRmibspGHCDA==,iv:Dh9JRb57SEDavv6QeNgnoO3mCwqCWbPSZKRytCxsgns=,tag:it3/2Y4OL8zxfMV5VxGC+A==,type:str]
    oslo_db:
        auth:
            admin:
                password: ENC[AES256_GCM,data:QNCb6PeY3e3FckRrUKgrLz3jAlW1ca0M2sdKc8SaQk5o4hpPJE9a8WfPG1E5jZxnFFDePVb5MNezVAuoMjy3uw==,iv:Rv1rjrufTOvwMmjEicMk7+Uk1nRr1cB6eTsPUVPP7rw=,tag:i25DvOJoPSs6/AT1a1HoHQ==,type:str]
            glance:
                password: ENC[AES256_GCM,data:uSWhhfiHDumTnT/LPY6azL7YbRCbSeqq4RE1CrWDLyGO8ihR2JNJwlmS7VBkTPfXvRNmsotQM2l/FulBXeFiVw==,iv:KGHMAYz2NV9/yAs4r+NuaRizx3ZmphdFSWKdWnjbLe4=,tag:vq7eCLLF6YynKE8iI+UIzg==,type:str]
    oslo_messaging:
        auth:
            admin:
                password: ENC[AES256_GCM,data:bVVANiXon19RstZ1f3+BCnddWqSkSRFNbmY4TIrHpyIT6bTKDCh1uB6And3JBfEwjlomYvcBUmMX1zVDTFlTEA==,iv:HSUYeBmOa5qakt3eO4Zo7uV9YHSb5CR2WzbQm1ZVfaA=,tag:n/DEDjWmjuBtp5vwiwNCWQ==,type:str]
            glance:
                password: ENC[AES256_GCM,data:kiuiow5uAwGyiMuY92usIZag20yZbRznG5ylXgtJhEPKHrCoEQnInHzJH/nGsE4hyzA+Qqdkc0XCR/wvyEnxxA==,iv:1t5fs52/yBhsGHvlekybGmpxHJtHSOPhPzmLv+sz+/A=,tag:sd54EnSQOa2dqHT2+V6Mmg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3eURzSHNoNHNjcC9DS2ly
            dS9SOFMrb3pqdDBhc05XVzFIaFBRdGhBcVdrCmU2Z1FsS0VsSDRRcmh3Z0dFUDl6
            TW9LYzN2K3d3a3VTaXFVdy82NGVoWXMKLS0tIGZBVTBtY0hleXAreDVzd2E4a3Nu
            MS9KczNDMzJNb3dQblgyMjVaVlhmQlkKLt0RJNRJl49S81uAgAvxlVhPM+fO/She
            P95hw5IxVQSST3gl4OTmCIhCq6mGMxdZJN/XkD9rkZZHx5Co26y+Jg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cjaxalqu6gs9mev9w0u537793ql5t0gy3a6d9qn0265s49k9ss6q7flh4j
    lastmodified: "2026-07-25T12:59:50Z"
    mac: ENC[AES256_GCM,data:DJqaEWqr1qr1wxR2flR9vjgOtGtl3IcMn05X3aAJKsb03/noLscMf0F+2q6v3PtwLoO/K9pirHyo52WTb9QqfL+JWD1rHrkly0fNXblxclk7m5igyqr1lkFv82YVnwDiagw2APPJWDc1bZ7eJOWMgzhPemCPZJhsAXT8o0Pcutk=,iv:7FXmuaO3jJOeDakrEmqmKRsbYUjcQ28E6yx0SgUh0KA=,tag:Rdd7GTMbCYtDLtQFFoXgEw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
