apiVersion: v1
data:
    DB_PASSWORD: ENC[AES256_GCM,data:FjfZV/2Fyiz+TBmEadnGcLggEpQXXOOUgkjmIi/Iyi4UIMjFcizyTVONBXR3QMdsrvvua7YqAMRKwOSdAFioZA==,iv:YDJKjsoNOM6muwdGZqtqaxSHUr1hY2HqZeC4XB2xxSg=,tag:OX27IkbjuaZiDmhJwa0rVA==,type:str]
    SERVICE_PASSWORD: ENC[AES256_GCM,data:bEtINMyoDfOYIshHzUaPuYdvVRajwfVZ7IuDYFpweIuw3yRG0EUNtKibVty9kmrstgixV9wUbiVCofrAKtXgZQ==,iv:REa1N98UJV3uT0jHuXUf2pV/K3eODCclKAoOs/UfpGg=,tag:sva/MF7t3KW5Owz1te9gVA==,type:str]
kind: Secret
metadata:
    name: gnocchi-runtime
    namespace: openstack
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrK05sc2lqVXcxQWVUNm95
            N1hJNGNxRmVHR2FLb1kybGtCT2x3Z3hNNXlZCnlYNmtndDV1aFNZZURqSTc0ekFt
            Z09WWWc0NEdYbGpidkRHRkEzS2hQTkUKLS0tIC91N25DNGtLZWlMb25zWE9mQlZu
            N3RWM2Y4VzZrOFpQZHJZVVZFcVVwR0kK+H/Kg2lHk9v8fSUq3AA7LUsCblct55XV
            KMGt1FXoEln4iN9lwlKfWD6EYjmxQxng9SAubhrkkf95zzO01A6svw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cjaxalqu6gs9mev9w0u537793ql5t0gy3a6d9qn0265s49k9ss6q7flh4j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T09:30:01Z"
    mac: ENC[AES256_GCM,data:dHY8Muk7CwmBormokQpLH2Ylrt49uNU7h17f5erCJ2nuOjhwUwqqLBPy3JMmZt4ubC3eFHlgLSfus0KYoozgLsUoIFGocUFdYvBTk3xEMpNM8l1t5vB9xtsTkMb8vTGIZznhCu8s36theAhAZTeO+imWedFoQ4AGbTQLEc9psJo=,iv:WQEkdQFMKKy/NMrjutOjiDEMK2cFb2GoqKVCH1kNDB0=,tag:vAii3Qv/2gfBSQcVuP275A==,type:str]
    version: 3.13.3
