endpoints:
    identity:
        auth:
            admin:
                password: ENC[AES256_GCM,data:+2jrdJ5ysKw5f86sI1KrDspC3UUjbvnLI23XtDpPvwc5UKB1R45gbfCw/A1cIXwZQCwPElKKy2ApdemsGkcu8w==,iv:OBksDNuEi7W6bhqf1pBGsRobYwKzScML+EmslzZBK7s=,tag:2ycg6oOsSG0qJB6ArsLKzQ==,type:str]
            heat:
                password: ENC[AES256_GCM,data:okqHJRZtPxKTzsPa8shAw0q3hF+02YG0gCuBgCCKTdmpCKA/7Yb/rFnV3bmBPsQx,iv:KYJD7WQnDfehCNEcC6pTDNeUtsO3KYxWHIFdhKvTZ00=,tag:JDVcR/3K0HgLschnWXAHtA==,type:str]
            heat_trustee:
                password: ENC[AES256_GCM,data:sAz9uCb4yDU9PqeISQ7lEh+gK+kfK0xWLU0EINdvuOUBNdqZmYk5b03Qqi9Uy1/R,iv:4dF31Kjzf1Tsts/ORB7hjFx2hzyZ/YnQrSF1WH4nSeI=,tag:y30hlSWwZ9uUi9rl7a0NQA==,type:str]
            heat_stack_user:
                password: ENC[AES256_GCM,data:1w/OcdhIgG383WpwllR3wUDXEUTU9QWn9ijiHLHquoEfbEGHstn6nw/a4AKjZ8cV,iv:3BAkhU5dq9O5Om0OQjewtn+0wZ/UpzQDPBIwMS5Dxus=,tag:bJ8alCrfmEyOsKyuEZu9EA==,type:str]
            test:
                password: ENC[AES256_GCM,data:diNFrYQ8BRzRdyxAMgpQFrHxpWpBlAzCJcgMf3mj9o+UY172IeTYcXevq1jxwMh5,iv:eOJYEGOPjy9nQjsOBhiyecIMbdwCYXA+xp4gwrH7XcY=,tag:T+aOZ/pVGUQcvk/cgzMNdQ==,type:str]
    oslo_db:
        auth:
            admin:
                password: ENC[AES256_GCM,data:8VSSQ3Vo865D9f8tUoe3TKPBjLvfnpH4w3Bs7grD9XFFupcJ9y/Nk342QoX9k0fwf2nY7rZp3OahdEO8WQwcLw==,iv:8ZJB2Ao9Kz3SPdVvrT086g1gYY3k14yOti3qoiWykUw=,tag:52MZAYjvWw3c17fCmB/RKQ==,type:str]
            heat:
                password: ENC[AES256_GCM,data:ZtT462ut8pxThnufM46fjpK1tTwQIfpqRVCGzLeVz0cGUIetjCfhe2JK4670zFYJ,iv:qONZtD4wsNLhj39vnfSNmDDIvAIcMR/KJ2m9pgjF7ek=,tag:DNEqv0Z2az73NE+Qhp50Nw==,type:str]
    oslo_messaging:
        auth:
            admin:
                password: ENC[AES256_GCM,data:G/9tisQEMGpCM3G0aZEUZhiHKqqf7+Cu0BZsY9QYBa3L3A0u91hAuUBcKVWgHVjwyIJL2Fcf/kFFSlqWMBgyIQ==,iv:Bd91tA1LgRNd6iDD4GTrFYDxPtdsPxGJCaVIOdGb9Mk=,tag:A8JPtXhanGGB08S5Xh31/w==,type:str]
            heat:
                password: ENC[AES256_GCM,data:pS/yvWWkhoh6s3qiEh1a8Er06Aphur3FZMVey0q+DKhYVLQdC8wFySbUk3WVVwewdU7isSse6AEoTjX0OcdBHA==,iv:+iJFhA4MxS4jSXV8yotNNM8yE3CQOQ4QunUT1VVgFK0=,tag:SkFDi9z/qzTAr3zEm7g7eQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGQU8ySWpPRlF2WlcxMjhw
            Q0l5VnB3RVFlcmtsK3dLUXpHQTZYQ1dGMlVVCnBHUWZiT01SZ3VwUlJwcEg0K0VR
            TElaaGpmMm1NV3JNcjJrYUJCS1ZFOUkKLS0tIFVtZ3ZlQWFLdWlZamROeXF2SEY0
            dzdDQmcwZk8yTDNFdFNocWdBNkFUVVUKRX5wm46L3Ku2d4jSjlg78aEywzsHNa4E
            VMicNUIbWzCHNbCV60hbacS9hKD7fWDGZ+X0COx8Me+JKAcG5VFfSA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cjaxalqu6gs9mev9w0u537793ql5t0gy3a6d9qn0265s49k9ss6q7flh4j
    lastmodified: "2026-07-25T15:49:59Z"
    mac: ENC[AES256_GCM,data:LvCMaJ0JP6XHseMHZmo1f7Dh5zAo327Nyz68sm9sIvwc6n4oC2rzCXaUQq4GfOMHpLXfbum+ocQ6HnHy2ycpf0FqDSk4MYeoWoZKngRl62S417wACVBac1rV4bEAw06FOL1baidHw9wH81tkazwU2gM9m72uYvzlEreCdm4xEpQ=,iv:pngbt8ReKji/gvSzWo9pMV2JpRtwlrzhJK4zODE1p1g=,tag:rZ6O0WJndiYYdFlk/msvvA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
