conf:
    horizon:
        local_settings:
            config:
                allowed_hosts:
                    - ENC[AES256_GCM,data:r2aGKfBG91lNjFq+fJ76xgapGg==,iv:BGVmsjQGtbRrxkJEmnU7An3ie7lf/ecQg/k3pXKD8ts=,tag:Ara2+kkL/MUj77FDZUFe4Q==,type:str]
                csrf_cookie_secure: ENC[AES256_GCM,data:Kqt0HQ==,iv:aUD65zGpBBTTziWouB3cRQezrWPcYJEBAiuYqPSZgw4=,tag:f/BCD2PqzLqg7Pvrs9S3dA==,type:str]
                csrf_trusted_origins:
                    - ENC[AES256_GCM,data:abQO7G8uDlIKKs4RvsPmK6V5GbfaCaduHklj,iv:6AMG+PNq0ljACPtBx+vanEbYGReA/r1oCohlB6W6Dzo=,tag:fTtS2Ee64EtvxpfBEuiJog==,type:str]
                endpoint_type: ENC[AES256_GCM,data:2SwXweDJVjUSzos=,iv:mggdOcOODqQCwWZpdRmo3LNymjaBWFvCWmwDTEoA164=,tag:i5WdgREjIwoeOykB5O94cA==,type:str]
                horizon_secret_key: ENC[AES256_GCM,data:Ve+CdCC6OBbIl2YZiniF8JSIVx5uGsV+wEUGR5PKk3lCxajnBlsbq06nrxXwHv8VdGsgqy0zNf/dBvOvqwrvquiNxcz8AL1N5nWWRANckYkCeyVwEjrBICuaugSc5c1g,iv:5xEVG0nnu8U0im7lSex2O4WNz75I5nrX2Ur6XQfQsvg=,tag:vD++dH7hrFKaro3Z6rxaoQ==,type:str]
                raw: {}
                secure_proxy_ssl_header: ENC[AES256_GCM,data:uMoqVg==,iv:9MuLvzNctKyuEFPNnIwJb81q83RkR+08ul9nC1RuNuc=,tag:xZOilsITVzE68GT0lfcHTA==,type:bool]
                session_cookie_secure: ENC[AES256_GCM,data:cqbbBQ==,iv:E271vgDffKPeMIoWiMJHqnEH+UTEwqKMI9pU8PKfPMo=,tag:n3LkIpW68sxUkxq3HedyvQ==,type:str]
                use_ssl: ENC[AES256_GCM,data:OEXmYw==,iv:Z87pK2v1yPVC8aWUnV0r1cLIBOz1ILC+1d1Pr5TNhEc=,tag:+Sh+HXkRTsDhGlnGZ3PskQ==,type:str]
                session_engine: ENC[AES256_GCM,data:qXPqGbP4ER/8sMpn3AoUIYwZEOHst9M5tZok7jkc9pXD/wI=,iv:HEXpgJj/dYVzS3fuF31kuqD9hOoeZpISUGDewjEdh9A=,tag:Cp1E8uWTbfqqsjpETYaZcQ==,type:str]
endpoints:
    dashboard:
        host_fqdn_override:
            public:
                host: ENC[AES256_GCM,data:9UQEO/q9d+FuUP1Bpd57oFpB6g==,iv:8Klc/BXlfaXhuSG/3l3TYMxkYhXegE1NK073ESUZam8=,tag:FOTWz/ldys2z3rL1ywgdUw==,type:str]
        port:
            web:
                public: ENC[AES256_GCM,data:VYxz,iv:09zvefkdHFdqkOBefsx1RKUNYzwWXZBgy5SYw7X+VwM=,tag:JNuc7O5es/kWp4BHBJCy8A==,type:int]
        scheme:
            public: ENC[AES256_GCM,data:er742jk=,iv:eh2JOVRuDfW2LTNx7OaLyKU9WmDipEfwVPffRvSKEmw=,tag:BDriea6iAKojKUNcy4pr6w==,type:str]
    identity:
        auth:
            admin:
                password: ENC[AES256_GCM,data:qGieED9REK1hLikOVeY5P9GXAv0u1codpmo/tfI07GYqwWa101bxaZcZl/bM37bp28fyG8cnmSZ106l0C9wvGA==,iv:JB/vbUpVF9d9LqXC4q+lWO1ht/4U2rzVPMFVJYKnG9A=,tag:V2aWV2S0r2lnliN7OIB7CA==,type:str]
                project_name: ENC[AES256_GCM,data:Bh/8fNk=,iv:UVNxr86lQVJm8aDnP2L5Kqw6URIrSn8l6jIbzGiH9VA=,tag:16m9nePgNLnhHugfSKOsyQ==,type:str]
                region_name: ENC[AES256_GCM,data:5+V5H6TvU8Lj,iv:DKck53oWVZWte9WN1CjKkKsvfoaSPs/zNssUhPQLpKk=,tag:IqQjmGwtwxyyMJCFFyFIQg==,type:str]
    oslo_db:
        auth:
            admin:
                password: ENC[AES256_GCM,data:OG8yF1G0gqKhj52ezUVckqb3uLjngT0ua/jmmXZ9/Oitdkpn+PmRrB418RXCLug/xpW1qgZt5nxdqc9VAK2aQQ==,iv:BJylrz1nI4pGonNL2q3DBvXGD/8oOTooAUJtdD9efeY=,tag:CqYBSjhGirs4OkEA3gG7cQ==,type:str]
            horizon:
                password: ENC[AES256_GCM,data:bnUh0++6XGUF1hrc+6H9QyeIsq02cuFY7cEz3bzbpFb+MmF8kOQWplG9YyeA2rW3,iv:Xi5FOWyG3G1m+JvpbJWveoOW26kzojeKCEEZyJ7zlKY=,tag:OhBvFpksyaqeo78if8IPwg==,type:str]
images:
    tags:
        db_drop: ENC[AES256_GCM,data:xukzS5DvKg67wYjNql9HgnURnzdt2wyHhQacWosPAIe62MiFClWyBfeycFAxdhVvc+RWMIY3,iv:IuXka2y4wV9cj2iWVgDrwGXQPQFgNafiWoVByMdI8PA=,tag:mr0EGMTRh3WkC0W8/FLO8Q==,type:str]
        db_init: ENC[AES256_GCM,data:ngwFC+V/FnofAWpmu2WTynuFjrAw7DPxYQoizHV5X+YX6K7InYLp+EYM0czvK+WEIVHc7qXa,iv:ACm256tqHo5C/4UM6V3Vtky2032PxEwsS6g52qEAYs0=,tag:ztq4mqMgW7ayaa8ejndg0w==,type:str]
        horizon: ENC[AES256_GCM,data:QLeOJWHsIg/vmC7cXehnzScVdsFN3a2tH61sdEmQ23mGjInykDMcT/ZjBrtkihVHyXvLfZY2eQxubxjPgQKxK4zBfYxR0XglzX3hAHKFhoMbwBe9q28LWdiPn8ee9dZmNaatOE1Y0yJu6yX/G5LCFw==,iv:R+X/m7qpvfYlZHfnlvglYcYjqx+wvXIQaeSU6tWDI3M=,tag:D5VneDd0wihxtdf6TBgQQg==,type:str]
        horizon_db_sync: ENC[AES256_GCM,data:GIKy7xI7vapJ/gLZ2fEsfh+8fS6OFtPXsSPxA4nCys0YAiF9fjl1bfY7virV,iv:8zp1O3NphZhz/TTawO0nN+W5DCnI58dClcIR/PjGeAA=,tag:tiLcTZ8CUbefGfE5aJgwFQ==,type:str]
manifests:
    ingress_api: ENC[AES256_GCM,data:ob+XATQ=,iv:wDb5dOZjZY9Kx2O9n+3bwfSReopLaJE5bYH8VNmkkEg=,tag:66Rh/axDc4LNqH75EoKuSw==,type:bool]
    service_ingress: ENC[AES256_GCM,data:EjwD73A=,iv:+lMlNUwozidOLXHc93Be+ZLd368x191v+hVxDrvEjqU=,tag:TOfWI+XsVH9zw/GMBObTIw==,type:bool]
pod:
    lifecycle:
        disruption_budget:
            horizon:
                min_available: ENC[AES256_GCM,data:Ag==,iv:/ZQBJrOey+188xGLBNuvYA8+zfTwe8kyzGkF0E1bG7Q=,tag:v2tFTho4Uuw9Y+sLts+zrA==,type:int]
    replicas:
        server: ENC[AES256_GCM,data:Kw==,iv:7S9ORb+XB5nh3CYfnqv3D8VNEe1XDgaEidBi24VFqlI=,tag:VLilKZ95pH1hJL+oFw765w==,type:int]
    tolerations:
        horizon:
            enabled: ENC[AES256_GCM,data:7B6NdQ==,iv:PFR+IWwEGfO8dHexv+fALbSj3NN+/5x1Wk/DB3IBwqc=,tag:7os34SPBqYEvELjQR8oOxg==,type:bool]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZFlRNmhNWjlaOU9JUnAz
            VHV1N3F0K1ZHeUlaekJWa1dMYTJIdHZWalY4CkFma3pUWUMwR3p2MEhpTHdWd1FK
            UUl1VlQ4aFFXOUxpV2JjcW54a1cxM1kKLS0tIDZBUnpCRzBCZW5Sc3FodGxRYlJX
            N3UxVGpSOWtwTEgvalVCc2xTL2xrbWcKlXXei8nPiASjeNu6g25aO/aN71U4fs/m
            sdUscBbKxUO6gesC95GflGkqJAuYA1kzyAfM1hQ/D8UF76gHb0QeEg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cjaxalqu6gs9mev9w0u537793ql5t0gy3a6d9qn0265s49k9ss6q7flh4j
    lastmodified: "2026-07-31T06:54:34Z"
    mac: ENC[AES256_GCM,data:HXFWYidMxqC6GHJjlzTUQaEBbG7fEoAj7l5M0OQfhiebgMavFluLEegn8TeEhCuOJoPvCgBgTbWiF/WkIwLSQwf7LO34AyIK6eNyuHIvASac8BOhOZwlWU//ouo0yn5SGD+V/0wlbhPW67dZsHdqwCtVYl4RzGIXm7OrXSTWQvc=,iv:Wd8pKoCy01aiYzspb8/6WfcmEqvThkP4vQnpjpmeUQs=,tag:I4Wvi/YI7Ny/4Lbpfrh3Hg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
