conf:
    horizon:
        local_settings:
            config:
                allowed_hosts:
                    - ENC[AES256_GCM,data:gTnm0lMo72UmIHqGIkCrE5QYrg==,iv:K1sdoW8Oc9DDELJZ8tSPie1nJtHX7erhs4hmTPA4A30=,tag:eyvJWZcF7AMEDgAIF1cHsQ==,type:str]
                csrf_cookie_secure: ENC[AES256_GCM,data:8jeqJg==,iv:LFsaNq6iRzgdn/tlDy1ltOCQSA7UCEmN49q6slkDzQo=,tag:GoGRXlSxWPE0EZtALmwWCw==,type:str]
                csrf_trusted_origins:
                    - ENC[AES256_GCM,data:9uRIU6Zv9oGA8dme9N4enewbE1j3qidMk8lD,iv:rDoEAfpfF4wtIZVQK9JkgHBetAkG/8wP4QiWBbGKxZg=,tag:3MQDOARgoC/1h9Am2D5HiA==,type:str]
                endpoint_type: ENC[AES256_GCM,data:MfU5Bj9/W+dKC+o=,iv:gnbWCbzMzO+po25ommMdL8WtNYJxcf19JlK0faayeOc=,tag:XfYqtEM6w/qs7I/4MuXpFg==,type:str]
                horizon_secret_key: ENC[AES256_GCM,data:uRccqeXsyV/Nj9cEXHc6ItkAwPHIU62l+Jd81dlFEYJ0Z0OKxm41iUODCNLxIeout2/1H/gX+SbytkhTJ5X8yQXRUWhUPlpqr8XaU0/pvpdPr4WaVQLxDZjR9xxfRw2Z,iv:RBpXFfDveezJcX6FQ6ns6cczllFAdjiqZw/LNOLS92E=,tag:LPJdB9m/Hu50Sj2u6mayFA==,type:str]
                raw: {}
                secure_proxy_ssl_header: ENC[AES256_GCM,data:DdkoOg==,iv:L22TLQM9wnFxG9+3EhyLDBJB6SFy+nmXBgMM6PX8PMo=,tag:0VZeAzWj6Y2Alul9qPpBBw==,type:bool]
                session_cookie_secure: ENC[AES256_GCM,data:nY9rMQ==,iv:z5je0+3atq2hA9UReofMmLYj7KF/ezwTP0LFmWtB4dk=,tag:rJHuX30b87oUpEiYLhuwkQ==,type:str]
                use_ssl: ENC[AES256_GCM,data:jIyOBA==,iv:FE57O8JGaC55d4cD2Ow53TYK9zf5XJqrTMHzg1GIwKk=,tag:gJ2kPoC+AtM0wExFAeaAKg==,type:str]
endpoints:
    dashboard:
        host_fqdn_override:
            public:
                host: ENC[AES256_GCM,data:To7aSxr7Ac3odA+Q+jMeZgGGAw==,iv:5l47eARX58xotTK/FrJkhK791xliCdJEo1IegTiyyH0=,tag:Wan1nVkD2u0JaYiqWgEqIA==,type:str]
        port:
            web:
                public: ENC[AES256_GCM,data:5qUw,iv:Sjf8JG31W+BGFWB3d+NcckOrc7EjyeFXdVUjXCdPXSw=,tag:XpokzrDy/WMEVDvJigiUSQ==,type:int]
        scheme:
            public: ENC[AES256_GCM,data:n9zT/Xc=,iv:bCvKdxPaviHJRZa//3aIot4KyRU5DhUZXpdU7W2soqU=,tag:vt8H5dieZYqHw1emGgxGdw==,type:str]
    identity:
        auth:
            admin:
                password: ENC[AES256_GCM,data:IzyA3m0Y3HxJ02es2s2FSZQI+olTpWCyGz5T/7QjXVdydD6Jmtv5W/Lyug+6cv5ve6FBhVVyrvZQm+641T4ZKQ==,iv:TIOFRrr9y07ZMxYMqVxi1OwMgABTS3orxexvA61GZZg=,tag:ABJyYkzHoTx7qR82X5DaPQ==,type:str]
                project_name: ENC[AES256_GCM,data:MLZZFjQ=,iv:6zp/NhaKSi1oBL9yfWxex3GCQLua2Pjjx/3Ub7MV/D0=,tag:DG1qsYcVByyGV/mlKcY0aA==,type:str]
                region_name: ENC[AES256_GCM,data:ALJ38jUrJYf0,iv:rGaXCBMIgSsHn1cV9NVzGRbDGSCEBGSCwfuqO4MvKx8=,tag:jCeZdL2EEl4YB2KSIXxJ2A==,type:str]
    oslo_db:
        auth:
            admin:
                password: ENC[AES256_GCM,data:C1AMxZOWwpCEY6B+hWwv4taYzZ+5cVlKMjO2lM7U6Vqubvqd/w8MdIEK5EWq3mekMjZh+mdQeWmDRvG95Oy7Gg==,iv:qXI7y6bA0fiCF/93oLb+uodur6ARAFGItlILBCuEKnA=,tag:sHbLttzRHkKksmtryxyumw==,type:str]
            horizon:
                password: ENC[AES256_GCM,data:FM/RbIivsORCYvbBZC1Bo0ggNWjNRDTLX4FU/LkdQ8dpaSxzOt+UI5Ads5elcryR,iv:UtO+5fvqjcGoBCT1Ad011NaeKfAAe1S2sDFEzcKY6LE=,tag:3+bXV5cgnLxkxjlqGoMLHg==,type:str]
images:
    tags:
        db_drop: ENC[AES256_GCM,data:8RIm/mV99Kw2HhV0V2LGpxOSSvLwzthkPAmAcOO/SuBI+dIyw+T1zkdhxt+f3OMW8M+3L3b5,iv:97zZUnM1z/ADv2OHqID8FscwRf5XLZwI4EttxUwl8sE=,tag:30m7KgHmzNoiWARHKTJhxA==,type:str]
        db_init: ENC[AES256_GCM,data:BUE9rUkWE1QK3jrXy4QnUU3t3kJsZsfyJYdvesSDscbsagigdV01Z6jNAj9bVN/+030IYvTP,iv:Y0m5wk+TXj86tVVQ6fg+URbThz97114WA8HWsOBEruo=,tag:qe5l850GbiBNdGqlNFZihA==,type:str]
        horizon: ENC[AES256_GCM,data:hSu+cFOhvIPX6qMH4WxxlVBYuUuY1DXHwPkcUZTrwT+4p64kroQ+RvKbKnwo,iv:Ei5h9ePUXwR8ee72K3f1cAMyHuP5Wmd2qJlwqU+U/80=,tag:as3un5Rb9qK1F2F9kcbHwQ==,type:str]
        horizon_db_sync: ENC[AES256_GCM,data:QILx8t2XMoyuwJaHG6lReXjHIsV+/eXTE9V5sfXm04CE1Gvxt5ENwmuaukaw,iv:vW76Qg6Q1cFe5lFteJ68GZE1UgNEmkoKdwy6YLlQRyU=,tag:woNHCodf1IClEQRyVmzTwg==,type:str]
manifests:
    ingress_api: ENC[AES256_GCM,data:5n4pPis=,iv:q12Py4MhmAbsaqYsqSO6EOsfUZjvLZdN4HnQgUL6SH4=,tag:qzPrm+OJWKX9e3qKwp1Low==,type:bool]
    service_ingress: ENC[AES256_GCM,data:Ped8Vwo=,iv:NZiZoZgl5yULtht96sIUbEmS9gvRcmmqiTEaC5r77vs=,tag:hN1EQ1MhoXX+ABPkJdvU8g==,type:bool]
pod:
    lifecycle:
        disruption_budget:
            horizon:
                min_available: ENC[AES256_GCM,data:VA==,iv:78TT1mXGpMaXTx5fwmtyWTgE+SEHOZKnShcJX/uDog8=,tag:dlVcUcPyBKeeycUUehNtRg==,type:int]
    replicas:
        server: ENC[AES256_GCM,data:mg==,iv:dso/j3VHH/XMxeEqUS6i4ygobyQXX12YZzhzPcl9clY=,tag:zbvsgv0BEMr2xKdkrEqMBA==,type:int]
    tolerations:
        horizon:
            enabled: ENC[AES256_GCM,data:wVnj6Q==,iv:KpWzb1yMsuwi1qUoo1cAQkU/R8ruEMZVuZi7S8x45B8=,tag:aAskcr9Gby7848WZlvdE4Q==,type:bool]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoY2VDclV2SGlCSm82eFhZ
            T0k4M285Um1ZcUt4QnZZVUMyTmprTWplMFRNCkhHQUZFbGZPZkx3WkVYRXYvNE9H
            Z1poNkFETHRvZlgraGxpYXFtcWE0aDgKLS0tIFJtNzFvdGhSYnlOc01vNzBmbW5r
            Q1BIRXNVdS9aQ2tGOXFtY3JQUlZmdU0KyFyrPzCNMFjldiFTfWFK4m9tWHfWBU03
            Dl0kxsrKKSd1yfb1zMubsNMFqYib+ubBqPqtuP3E39XCZdR2VFqmOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cjaxalqu6gs9mev9w0u537793ql5t0gy3a6d9qn0265s49k9ss6q7flh4j
    lastmodified: "2026-07-26T14:07:37Z"
    mac: ENC[AES256_GCM,data:+/amgjJFaJ/rh4WjkidtGfkOyGLpOMpNxm2chF0+sOu98ZhmG3Aly8BLkoWRujdCnh4GCYjMV+OE2dXfv1dMErAOnmtKzHojwIJSdctuxruDhHt28aMXdPSC8GucEcAZtOAYSJlFcfAlfRFQ+rOJvWABDW9A+uPPCHCOD+/4lLI=,iv:CwEe/IoMuMtiFBQrdwIV7+v0+8XS/Vo/K7kH/Dvgo24=,tag:6EIngBnKAvodd6eTJB4XkA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
