conf:
    horizon:
        local_settings:
            config:
                allowed_hosts:
                    - ENC[AES256_GCM,data:whe67XT1A/+esEMna9LRT01wcQ==,iv:iRv255e9HFt98LHytO4lU+cEC8aERbimlzdxZ0zQK2Q=,tag:jofQtHEC3Y/L1cYQtuciUA==,type:str]
                csrf_cookie_secure: ENC[AES256_GCM,data:eMvFUg==,iv:6X+X1RhQPwU7QiJgnYBUMVOeZ6LSzwE8rvpLwPny8eU=,tag:QyMb496UxndkEZUyiOguXg==,type:str]
                csrf_trusted_origins:
                    - ENC[AES256_GCM,data:oozz98tQet8gUNG/bpZlzdEkjwtmitNbdaQh,iv:m924vue/fd6jdO7Ydsnh/4F9hjQNq+E8KTYSdFYiS3E=,tag:Fodf9uynxRIBu3OgYLLhgg==,type:str]
                endpoint_type: ENC[AES256_GCM,data:AVQLKrcgfoS3fI4=,iv:TD0Fuf+fuqF6qfreZ3SktQN1yLMVTaZjfvuW6j44i+Y=,tag:1nY8MypXHTdwlp94VdL9Jw==,type:str]
                horizon_secret_key: ENC[AES256_GCM,data:Pr+QaEN0xYkmDU+1WwSj5hgCCC1d0jDH56ZYlc5uXJpNT+5rBSEIwCBFg1BlaYGXbCmehXasmb4F2WNFAmMHLDe9cUjhNL8whJ32MLn12ATWzHwLVJjLTSm88b5qYOfq,iv:DUVy0aR64IFc17VpXzsDvYAAP/KD8MCZ+ifG0CRAKNY=,tag:QZGOa7BjXXn9PpVVEH1Xog==,type:str]
                raw:
                    FORCE_SCRIPT_NAME: ENC[AES256_GCM,data:sODs8Y0vVN4=,iv:5WNsELVvOsNmXArPknaIHyzMxfKnWWbnnQdR5AWBNE4=,tag:LepH/1eVbB/9WK0ViADhdQ==,type:str]
                    LOGIN_REDIRECT_URL: ENC[AES256_GCM,data:zvzNAdCh4JG7,iv:tmf2D/3IG4Mdj4mJ3EuWqF5IoIp5b7zISPnbvwInuLw=,tag:8ptZ6fKjnicj6vaLVWr2kA==,type:str]
                    LOGIN_URL: ENC[AES256_GCM,data:VHEn5XC7cybbojo8qO1lzGaGgqw=,iv:PISk1RoYZOsHvduiJ4wAOavGIpkF8ihNRGMfPA1aFow=,tag:tooqs+OItSpXz/zQggM4Mw==,type:str]
                    LOGOUT_URL: ENC[AES256_GCM,data:ZTe8w9vIOaqy7z0bbjeXdxILNHBq,iv:dZB6BKKny7s+KBk6DoehyXRfMhOtLDbCtXcVygIM1L8=,tag:y+aUw9rivxT6OByd0aGlVg==,type:str]
                    STATIC_URL: ENC[AES256_GCM,data:SKj6t4GL8vop7s9nWmS7YA==,iv:BIzpeDUw3De0E1jKzqf89X1DhWP5oQcIt/qRxW+KYwU=,tag:DAgNpyOXmSfmDu/32WOCfg==,type:str]
                    WEBROOT: ENC[AES256_GCM,data:3nPZJ3764pki,iv:16s9qA0cHeUP/Cuag2uYSV0kjrstP4n56kQ7oGOLriM=,tag:tLdA0mdrR8RF99xHEhuo7Q==,type:str]
                secure_proxy_ssl_header: ENC[AES256_GCM,data:oP8S0Q==,iv:pQ5FJCzQTbMRiQAqeL6huHZWnroVIglYR7DkcpuT6VE=,tag:XqIVviq7VQIQpSiY9Z4HaA==,type:bool]
                session_cookie_secure: ENC[AES256_GCM,data:cZHlEQ==,iv:FHTdIEzAx4p1BKIZxeKFs25tqhWlC2BsJJUFbqZPc2U=,tag:8Wu0GXgkKWW64WsAzAOLuQ==,type:str]
                use_ssl: ENC[AES256_GCM,data:fn2Twg==,iv:kJahB+F8bOspVfY0jxxFgyu71xUBDpe7lHYL5kvEakQ=,tag:p4LZZoxpdAg6kc6k2MaXdA==,type:str]
                session_engine: ENC[AES256_GCM,data:oqU9zusXtowTZYh5+QAu61NHOkN7GubFzpwRVXw8Wtu3S20=,iv:DzTcSMRudjHKf+kqzPj1HjbOVg4EiOCW59RFL37jo40=,tag:ZLc3KwcCifTC7uIJNqwtqQ==,type:str]
                compress_offline: ENC[AES256_GCM,data:NRcR4mg=,iv:4AcP8kmTzPTHZTwrCPORzhf1tleuwdnFVkljp7edugY=,tag:j0SE0qUhZKRNdJMnx9FI1w==,type:bool]
endpoints:
    dashboard:
        host_fqdn_override:
            public:
                host: ENC[AES256_GCM,data:LgHtGL7+aizh30IVZ8sMfRAJoQ==,iv:Wtbb0miNj2D5jXwCM1miGvuPaL4upr65888Mcs+APpg=,tag:GMQwzJUVTXjzEVmvaQL6+A==,type:str]
        port:
            web:
                public: ENC[AES256_GCM,data:rRQl,iv:hf+JPb9OSI3YIBu9NiELk6XurNqrnZrMsiRCmCwBQx0=,tag:e8iu2HnCHMAW2BZgqNkbmQ==,type:int]
        scheme:
            public: ENC[AES256_GCM,data:Ao1z6IM=,iv:bJDPEyltIV3we/IJ7v6GcOOKKGLPhdxLUsNtaz4zxhA=,tag:GqxfzppkS58pFLTxQug6zQ==,type:str]
    identity:
        auth:
            admin:
                password: ENC[AES256_GCM,data:dzP77ES2UEu6Xf5JkKbZKv7xknob5GcOX6CyOC/o7hLu7UpRdLm95D3EQayfGnDQvY7Q824k5vA0whzwKQo6DQ==,iv:BCbbrCWmNIfbySKuO2IhVviTEssYL7xzb+PX787Thyc=,tag:lAWLbD6tObajRUp5K9aepA==,type:str]
                project_name: ENC[AES256_GCM,data:/LrN3X4=,iv:czqQcNiJ9eIzx4x604FZEtOv46pFdXrY9QV8FtHIvOI=,tag:Sv0ISb8+09jyT9vbiIBrkw==,type:str]
                region_name: ENC[AES256_GCM,data:hfz2dw41Aq/6,iv:RckCG8jl8p9tbZpFlt5pqpFLm6QoO8MhTzMCOAbz6nc=,tag:6ZJGndBNNm9Z7q4NwwBl0g==,type:str]
    oslo_db:
        auth:
            admin:
                password: ENC[AES256_GCM,data:IImFefCtUAWW8aq6ZLNYADeWd91eRtjzlDJAeqS8bWixEr8mYCjqnLRcMyjiFqOw5b43PfTwxNmDErQyu8yQWQ==,iv:2R5RDTgdMp5gw8Jc+ngE10keOj/jFtJzxZ/3lhAO1/s=,tag:K+LUsRtFz7p3JG6pnR7BEQ==,type:str]
            horizon:
                password: ENC[AES256_GCM,data:sXIf1ZAgNVj9euaAATSDZ5AYj1F4johHbNZi/RWByQP/zYJCOMaHuJ+LH9Nprr8c,iv:u/PQ5vIljoISyG47Z40BonEeZ7zkapAWJLUuWrVuKw8=,tag:5d/w1Q/vbR2xvqki3SMwaA==,type:str]
images:
    tags:
        db_drop: ENC[AES256_GCM,data:ZkgEtzWRILvb6vBeU0d+cO522S+KoZfCig/NdDNDjDjhskUwu5svMHd2b14Xzu9TSWR/s6nd,iv:Je/Q0ian4HVR4qw1+wcT6cnaG6LmS+wM1Ogpr8+Dy0E=,tag:pPlkX98TNQjEQqeufwKyrA==,type:str]
        db_init: ENC[AES256_GCM,data:oflZLuPXHFUb8QG59rvYRVU5MvaYCqUlWUHZn9HhqXWrn5JlgLHVecbqHcoffAOgn+Bh3S9p,iv:ZPc7o5koHArnFMtZqy9zRFx1VtFJvEZ/+0/o9ytqIYw=,tag:ed6wT1CTBIQ9jvmessW1RA==,type:str]
        horizon: ENC[AES256_GCM,data:yXdWFUlkfiOoQ7Zt87g8SSTdxO9h3O0D81axjpLEZQgM2p/7Zk5Qif4TsQPkOXte1IDYBHdY38nHcoe7ky302v4J69hSDKln+M8p/IDQ0goV2nE7GO1Z4RKgIJlN9V+Lky2GqD+R3oIOIWYTQ19D8Q==,iv:WT2fq1Sx7KL+SeDrpR7+elQCfors3AfpZVZWEwcwPs0=,tag:Zv+I6FkpL/BxusvoBuPUXQ==,type:str]
        horizon_db_sync: ENC[AES256_GCM,data:nkfJRxn70FF+yQkizJITbqfAsK8I+cTBNnw9EhBZZAP+ph4K4iueY2Opu94L,iv:ubXkDJFiHf/7SSGe08hDX/Nau0OYeUKTYuPf51Un+Og=,tag:Lwpf1ceBW9OK0cPLcFZjTg==,type:str]
manifests:
    ingress_api: ENC[AES256_GCM,data:UxY1HKM=,iv:FrIjF8B02tjcACad6LKJulUQN53v5PZSYBp1ePN6n4o=,tag:sQq5FcTKGI6pCa/CZDMvjw==,type:bool]
    service_ingress: ENC[AES256_GCM,data:CElkmZc=,iv:pfLcs6s0Z1emJ4mf12TULow/WV3Yzya16hOZKTZ3k4o=,tag:ql4uzFQopmV6Is8iG9DMEQ==,type:bool]
pod:
    lifecycle:
        disruption_budget:
            horizon:
                min_available: ENC[AES256_GCM,data:QQ==,iv:ea+QrM7mdnieTUODcgtgubNU7PtbCdvjTK3AZb0HNOA=,tag:2HgSnWJ0i+lmWJkBT+HHOA==,type:int]
    replicas:
        server: ENC[AES256_GCM,data:Qw==,iv:oAfbRmxS58Topd6k0ML6BPQkTRDuVghNQgfbnWn5toM=,tag:UBPxTPErUCDjsAVT2KzzPw==,type:int]
    tolerations:
        horizon:
            enabled: ENC[AES256_GCM,data:t/6i0Q==,iv:LMmoUrn2/w+SKcNnw2/n2o6smRQ12uBZ9dDU2s5rg5A=,tag:rfwb+Vi+2sfm+pp1g4h2cg==,type:bool]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwUFIxL0NLbE1pOVFNM2lZ
            Vmx4bmdXcGdHU3hVd0NDWUhqemJOQ25EYlU4ClZ6RFlVcjdjTGpJWjNYcW8vRDVW
            aUlRQjU5ajdaMWdZQWJYTTJmYTdHaEUKLS0tIHBwRXZYZ2tMdTl0TGxuKzdqMzli
            MmIwQVZXbThiRWRrZENVanVNcWwrM1UKhwbTTWuF2jP6SuTAhT0GqX3fuh0khK6t
            MH+1CSUEk3UXWTHiWtpRheGAfV6mTinrS8PmX0oxLEEmDmnOwJdpcQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cjaxalqu6gs9mev9w0u537793ql5t0gy3a6d9qn0265s49k9ss6q7flh4j
    lastmodified: "2026-08-04T03:24:52Z"
    mac: ENC[AES256_GCM,data:sPc0q2zr4Tyr8LXtEGYL8X/qLGczezaw/Memas1spf6gfntUbSyvZz72q3DZy+Gi1nqb0M5NWyivfKmGJxZGG9/Nl+Lag4vIn+rSMr1aUxNJZSIpWWjx6DT/PFj4WOiuR6UhR3os9DpKBCwbrIBLBcSigkx6XxY6Xnzd/GJJlg0=,iv:RjvJZ5kptunp9xNzyo8S3avnSAAzg1un4o+lFtVxyFQ=,tag:0tKQ+SPDiISr5Jto1I0/9Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
