endpoints:
    identity:
        auth:
            admin:
                password: ENC[AES256_GCM,data:LHlK6ySlYgqpZxVtmpurx/jvF44eFEo7612bkX6WCLORPw07Zpj/HdfatunRWNIcePVZsmXhrvaDqD7pWGBUDQ==,iv:BhMXuzLLWF/kefuod64N95D72yLQnvvnboSsd4VzAZY=,tag:0sNQzZkOFAm8+SsWZJPRAw==,type:str]
            glance:
                password: ENC[AES256_GCM,data:wjFNbD2TK4KE3slaNCGTFRq4bVcTcIayIQCztq13nKu/+XftX9AxDLOIJtbosMJRfMxRqcwLWKzxbBL/isJcuw==,iv:MTQxBEy4H+v+p2VI5JsakY6jQ1QH1giAUmDY+6aPb+o=,tag:kwPbcVHxEqTcTmmta56pjw==,type:str]
            ironic:
                password: ENC[AES256_GCM,data:ej2ZFTM+hhuatgcdWOYuwN/hKryKVrnFjNdVz27+H3fkliSrxQ8Qhm8mFd4PFFjG,iv:4pqZclp7N6tHfd/4SkOZrgU1OOpHdLSHkx8iryGctL8=,tag:4EQfaugacMOK4fe7juotmw==,type:str]
    oslo_db:
        auth:
            admin:
                password: ENC[AES256_GCM,data:Z/FYwd7nXJrcD9zss4FjpkUED6oRKL9wlF2T+WiMeqcj1cVXbhoMGYAj6ynq5P0swSU/L5gGvZkcB2HUvAuUiA==,iv:zknA/pu+mS5uEeNUkpYIRF9pgcp0Z4TsfDDOO/JqAjg=,tag:y7+marDB76vpIxvRcWDCqQ==,type:str]
            ironic:
                password: ENC[AES256_GCM,data:UdS6ziV+QXSzDnF0MYXyrm5GL2b0Q6Kn7mGsjW4H/DRC1NwTbNhKm70NQ3tVCUap,iv:Y/qVpoM71eUJLWKTqYGzf9O6HkgSwmlSrFCge+A1Taw=,tag:RRTjLoUSkAnquZnEkYMfyA==,type:str]
    oslo_messaging:
        auth:
            admin:
                password: ENC[AES256_GCM,data:VSHXhRF2SgbfjUzu7R0sBfvGuxULXMzcIed/NUjLgwjDulwwIAdWCw1MwSDAqK3UKFXKZ5tjYzuTsRymaBepPg==,iv:g+4eHXZpIqQh5j4slzpO1Ta3+6ANY4E58/GDtYCvuGg=,tag:w90PWfL1bedttZUBv9F44A==,type:str]
            ironic:
                password: ENC[AES256_GCM,data:AvLHIrRo3SeaKvlGvPmO+5ErxaQTzvy/ruEy3jH/StdUimj2DuVLagVEGaZpcMOsiVF2i+7HwK+kJJYImzxjpw==,iv:dam3JP6aRl+1qWLEwv9t63Bh3sYvGlO3wkw3h+p4Lw0=,tag:bsULnrfYseI/D9pMbgoAIQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMYnVzT0RlRllnYzEzL3Ny
            cDVCak5IeVJIMjR4Y0FpbHM5RHNWWThuU2hrCjFCZUFaMUVsNkEvenJXT3d3ckhH
            bzg4NklHcVIvVG84NVo4VnZ3NmJlVzgKLS0tIGFpSVRFeEtYOE9KRTBCTk1wb0Y2
            MUFGR1FYNWl5RlVoVGt5NlJXVEtFZ1kKL47kLTK6xHMhJvyRd8ZAHt0Tk6ywMjye
            uOFmYZkG4U6QFpkUGS03comFzDjstZPBUndmc/VeGlfW9gJDHT/7dA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cjaxalqu6gs9mev9w0u537793ql5t0gy3a6d9qn0265s49k9ss6q7flh4j
    lastmodified: "2026-07-30T13:43:51Z"
    mac: ENC[AES256_GCM,data:TS2gitdfmyy/5CaVVgnBRpXVnOi/bwzKVqsQB88aIAEk6CfkMFLQN36oHHgNTJ+upr/RYUm5ljV850o3e+5KBWNVC0NhLDYCroYqDdo+ZI2XlrX4omd/eCnIc+HIUFDgsdPDOrVzj21r9VrSG93/Z3CN1GO+Mn3830xJv6MS0Fs=,iv:Q64ir8Ya+AMKJZmnKChZkCH8yl8gQUO47Zf22tKdXzs=,tag:4kVH9RP8B4TjvbPZLOyyRg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
