endpoints:
    identity:
        auth:
            admin:
                password: ENC[AES256_GCM,data:Ih2JNePhmEePCGDAk660eNarYghORAvXZU5oR0SdIp8zvmY3l1rBI2ZuIXS7E+1hrXxOeqh4dxv48yaFOIGpuw==,iv:3VBgL/onKAjVHMban5bxchOZN1pFxbm8Rt+ZLtmn59g=,tag:uDxcnkkgmycPclVL1lYRlw==,type:str]
            magnum:
                password: ENC[AES256_GCM,data:swkOEYTGgPnGYgNLih2QmrewpgokS0/BJODTHNFJ/5IiRldQoPNgpXM9vQduzuJ9,iv:ID60v8w5FIrgAp+S5TmSopjv8295OtTCf698bZyst3U=,tag:2z+4iWtIi6vEWcslwPZdxA==,type:str]
            magnum_stack_user:
                password: ENC[AES256_GCM,data:fjYc6XOKPADvdyh4UriWXzhdKIjxo+eUeK1DryJDvKz+t5W+CA9QDAnkRiJGm6Ik,iv:pGU0GtTJejLMkncH6oAnwlQbnNcrKIAm+MjqJ58mLbc=,tag:/heIxwOiHviYTbZsEEI7Lg==,type:str]
    oslo_db:
        auth:
            admin:
                password: ENC[AES256_GCM,data:kYhJ9ZFA3Ga2ghF9FUlF6YzAZo4r1p1NOG9jly2/6vHyxIP1zZFuAJ5QVWAhS2H3TCAgSGUvqEv/jGfdBZrVXg==,iv:9I3XWGWB2U+Wgf6IpJ628jucQBRo/kfLQ5mzeq4+GHk=,tag:tbZFC9SCh777H1CWxKpz+A==,type:str]
            magnum:
                password: ENC[AES256_GCM,data:PSygQL3Glsx1OAjVm9xc9Ntq3sc5mepxwOCZr5492Lt6d6mA+ngAzHbf0UBLB9yt,iv:n/3JHrPNYkcSZBmSk0+VO2QPOQzsOzx30q8IqQxZ0nE=,tag:pacHtKpt+dkQa7HGLWMWzA==,type:str]
    oslo_messaging:
        auth:
            admin:
                password: ENC[AES256_GCM,data:HnGBUFiQntj2rW5CDp6ym3bR139T3aSZwJ3audQHIDyDzORN07ugP87dWh6yuDqG64cYhp8kWRLNvbCAKEGsVw==,iv:5mRfKSu6fhui1R0CjlZc1jQx4Ph8FdIPaNvPN7SNGpA=,tag:Pxu3UTT/4BW8I1qeLw3F3g==,type:str]
            magnum:
                password: ENC[AES256_GCM,data:nizX7Llm4ur80pw7JRePidsBAMz7DIq4tR5N3/n0oLj+we/yBHSssdSzegKmbXhO,iv:4a/NBr+juGCT4Enrlnm+IefjeYjCrOs0eklw8qjRxUw=,tag:9a38HRWuJ8TjCtotp3kDIw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SDNMY1o5clkwU3RzQWEx
            WGwrN0JCU1RicHFadXcvK1VybWFkNE9CL2pZCmxGYUtGdWE3a21sS1Nxc0lsMkkv
            ekZTQWkxMWQxSkNuUGkrWkZMU0dtY0kKLS0tIDF1eDN0ZXZuYk56b0NpTHBZMDN4
            Q200d2JYbGF4VXdLUzh0VS8rMHB1VXcKXrUKiJt345QRZVEPOPS1a1w72gdFgS4o
            WifHKEF0A2sD4moogFw9Y9pDz8o6jtHLHkOtdK7wW+Kux+dY6fwgVw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cjaxalqu6gs9mev9w0u537793ql5t0gy3a6d9qn0265s49k9ss6q7flh4j
    lastmodified: "2026-07-29T03:23:01Z"
    mac: ENC[AES256_GCM,data:Q0UO8s/4x9ISi4JIPaLYWO19DU0lMAS9hDHedEZOY+8UiVXiQuWkOneeWJtr3vlADYpvaSYt4UeUDzT5DvFbZxEb8nvXDdY/vXC+TfCSJ9CmIckRZ6sOycGTUC90Tyqb5rCZU4+XgVLxL1vEKUw5HRBaCKnlq6oF8SJVvYxd02k=,iv:PjagLujLg4s+1aJK72deNR1GuIWiuFKIGJpboZqvoqE=,tag:1Jfju59pYzd1i/RWCH/Nhw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
