endpoints:
    identity:
        auth:
            admin:
                password: ENC[AES256_GCM,data:lc7vpoPVl1MF9RIdmQj12h8be86jCsG7ghrWmBDaBRm1Fid3NKMQFExSeSTi/BA4/h3ALcMzS3JVTGzTSlBlCw==,iv:ZXqnqeiq1ll5jAKHByD3wcuJwxsdBh542I8P2wlq9Yg=,tag:pzL9ZzxKrMxgamHOZqzHZA==,type:str]
            manila:
                password: ENC[AES256_GCM,data:5qh75t8boHmSrzJRFFkAJ70JQC+/HyBsEVb0WVt++1c5ds0QDdx82Q6u6Y3ANz5u,iv:Uj44qbGdyz6Kmw3HFI9v8oGOKRgeNkSYjU2g5ZOqzSg=,tag:jJeapBZ6LaKsLf3sdnOP8w==,type:str]
            test:
                password: ENC[AES256_GCM,data:RdNZJ8UIDNnVsrzVtHFRN8iDmAMmtVtdiH0r6ojcapD9/Ph+hClDGZRp33njBmA6,iv:nOIg2S51VS1wFq5aqQaSZozjqkY0V9Q77eQdALCRq/w=,tag:6APmE+faAJnvYt/j09hYuQ==,type:str]
    oslo_db:
        auth:
            admin:
                password: ENC[AES256_GCM,data:X+Ci5Okzb8G2s1jDZeXsA0NfsVtkan5zKosic/V6O9zVJC6V6cT0URtrPachKw/HWERoBuiZlFWiVaYmO2OQeQ==,iv:xYwFUdlv1etrVlIM3Tg2MsdrZQfForLKYJAFnJDzvTk=,tag:ZBLNJ8TVKx74mNX3rT9RWQ==,type:str]
            manila:
                password: ENC[AES256_GCM,data:1OrDhDsNakcGLGvbXnaINO4NBvYxoJBMlYR5gkEgmgM7a9Q39G9mod7LzZ6SjRYW,iv:kJ5qndhJYzgwKt0Fk3YCJLWAxRIkENard2JWtRVRN+s=,tag:9C165KDOePcHuaBqA7GjIQ==,type:str]
    oslo_messaging:
        auth:
            admin:
                password: ENC[AES256_GCM,data:985Z2eFha0x42aq/jFmUFo4xY5RPJchVjIDCUF/Y5BadSUumRMdVCZIeeZczqGcZ9dvs1X9pdgHjB2kzaJk3zQ==,iv:HKvdRVgcnDj52wZ9LWvmftw7/oux0IH2BGLb8FJE40Y=,tag:4CAi0U6wIxWU2UOynnY5Eg==,type:str]
            manila:
                password: ENC[AES256_GCM,data:REQ7U8p94C90Qr63v9z4hHGDiKnrPmUB5ernl/X37WUm/orxEmtHs4Ix4rk7kTQZ,iv:BZ7thiewtsrThnNn7jz9YHw/ryXNiEyGK0tMgsNYmKM=,tag:YB/BuWgpmQv7px38iN2AbA==,type:str]
    oslo_cache:
        auth:
            memcache_secret_key: ENC[AES256_GCM,data:AWwYnpj42MS075HyevW4Jr4TUzncoJVADx7R6QFBKeWSHLZeciH+KUYSaL9uYxZf,iv:WY70Ly7Z59urGCJVsueEdP/axEy8pfVf6UQzrI60yzg=,tag:WOCtYm85TmZOeKRHoqyK9g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxK1BhVjk1SzJMSVJ1TzhK
            MDkwcjY2d29RYlZVeVk4YlNXTGZrcWgrTXdFCnZlZ0swL1pCWTlMV29pTitNWEVq
            SFhubitQTWsxbkNTcktMM0t6dldEc1UKLS0tIGduZ3NPWU1yeDJvN3JjSHFZdjJD
            UHRlMWtVMEZ4Y3hUeEExRWVOMDdSYjAK5J0UNAWN2MSnQdqgYjXotsy6iGVmfcqc
            WhrJwqxnvMDdY12GO4sHCyj66qTJw7rR/XvVZFeCcCVgcNSzGh9evw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cjaxalqu6gs9mev9w0u537793ql5t0gy3a6d9qn0265s49k9ss6q7flh4j
    lastmodified: "2026-08-04T14:38:04Z"
    mac: ENC[AES256_GCM,data:BlRWQqoCKAmZpcoInFz8nS94uxqnOVS3y0/Czvxcdgiw9mQD63tU0MBHoRfepzt/NopxZamxSNZDoHt1qDFgYCCIrDpTW/J/YCKLB2zd4LzpYif2hv7Z5EdGEHmmmImiOo7td/kNh8OwgS8tP/yyYIbcJqIgN6gAEgCYsO6blqM=,iv:1IOmhLXtVojreOzWIh56LYlYivo1+0iXgYCbHDlH/AU=,tag:XlIRbco4BmKt+RjFxzGXrg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
