endpoints:
    oslo_db:
        auth:
            admin:
                password: ENC[AES256_GCM,data:YfCBC9Y1SmMxBq1hYZzaSadC/yCYlMMoXOmOPiMi631/OH+ON7BPpoclCaGMfSH/W0kvuayp8yfst7Xw78MLPg==,iv:r+OyLPOcsns3Dat8eWztrx+TJ6q1ypDBbaQhlmV6PnY=,tag:/Tsq72WYXixfkxWTGcEh4g==,type:str]
            sst:
                password: ENC[AES256_GCM,data:OoZcw2iWVeF77tbXvR2tiSNA7fdScWoqc8e2BeLVvW+ynZt7iw4q/S0eudSD0UIiT8sW5hBPqvdpuFyTi+M6yw==,iv:Fq5sqkMxDSoM/y348QB6AZc4Q/Z26SvfO5uypO1C1jE=,tag:2IogN+dtg0ZxN6z2KOpbjA==,type:str]
            audit:
                password: ENC[AES256_GCM,data:Xmk2fbnky02h6Qm7dudh/a2qm5WRcYcc59BFOM+Ksp8A0MShyyz8BxPzEtQag+MX1EYlr8jvDpihIkijh9ppAA==,iv:ujKxCTFTPxJkdQSSZ6z2/Qpvc0aUPT8fFfzm0kjewyg=,tag:rzPMnbX1jWmgJQZJ5O2dEw==,type:str]
            exporter:
                password: ENC[AES256_GCM,data:l9ocTh/iyltwDkGs9c6wHpjbOHl34+ggfqVYDVAzLHgDbFrK2xvMPUxF2IuOeCnDhPSdsd4v9yqyf0Fk0KDuIw==,iv:8dxrbNbH7+EkpUs1XQ3+EbJo5ZGOY1NVmokb2aVygKo=,tag:4OHLTqZx18tSBXuTwbPtYA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCU1A0dnZBR285R2djNGI2
            amhCbHlGS1doMDc1NVdXV2hCWm55SWdpZnpjCjRrTHVQM3l2TldDVUhNZnJmM3BL
            ZGtUSFdtOEFZbkE4RmE1MG5qelFNMUUKLS0tIFllQjJsWTh5d3FFZGdUcGNWNXBI
            Zkk4eVlBRHlRSjdBMW9Dc21sdlVUbzQKJPu+6A0cH+v0b8WHZFruPYUHvWNiCXgA
            CfDKwnG7YG0fbi58OAdszzaI+yLjaJ2jxJfv172KLxkD2qcEATTfhQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cjaxalqu6gs9mev9w0u537793ql5t0gy3a6d9qn0265s49k9ss6q7flh4j
    lastmodified: "2026-07-25T11:54:52Z"
    mac: ENC[AES256_GCM,data:HsPXRcvbydAOGAcKjmpSHUp1wXTTKZA3GDcx3tCfpEYHb9fPRVTxvdQQ6eG+Wtmzx/Wwlf3t2NElwa1wI4Vyaa7wJrDCCi1uOmgG8MXNJA0jo6FEXZeOZFfs/UE1xUg5dSSYJnFnZc2Z0ZWXkYgJFuZAx5BlsZeTFRraEx9MEQg=,iv:2BonkUEFqH26weLsHUOmdJwQaAiJwO1Ea8tutIiFEz4=,tag:p41il5MdM+PcW71yJ+o+DQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
