endpoints:
    identity:
        auth:
            admin:
                password: ENC[AES256_GCM,data:NguaxanH3Wm7fx2/GNPJOtvzo+2/H+ITSuxZ8IgdeLRIdfvYL+uuSUaZwnzAObhhuQvhtwXtb7od1hErOdFuxA==,iv:7bTG15CvM04CFPiTvf0GS6Z0fC8v2FHpNKGAJoCvROI=,tag:3WhA2B2MjnhlIMsE05tkXw==,type:str]
            masakari:
                password: ENC[AES256_GCM,data:XZ4hP1/qsKQRElU1s6P+eMZF3PbOBPoHqpvgS9COA5LOk2CZkxqPgfE0sfyikGsV,iv:jhK1vL9HzIdpDC0NWtiH9LHYzcSN/FBI17IykfuQGlg=,tag:lIgEvINvbDCdrigmlz2QIg==,type:str]
    oslo_db:
        auth:
            admin:
                password: ENC[AES256_GCM,data:UBkZDANtBwTBEi8wgfvSNpj2ZNm9XOhuicYfP7HMN5OcBp6DLbKyQSf5xuyV95+Vksbuyy/yyfjJMlMlsm7tQg==,iv:r+smpwYxIZwjy7ANXS/DyoFvSRM7oq8VQ/kuHK5Oi8Y=,tag:guBDzxv5+x7pXbsaPss26A==,type:str]
            masakari:
                password: ENC[AES256_GCM,data:O9KJy/xKgxZFA8KqYytEgezCWu8FdKbYhbtAGr/Dh1j+R71FL8Oj9MgEpnbvwap9,iv:xBZASQ+X4JWyfSoGBOj5nePH78FxVG1rfQuIJ4CflMA=,tag:ufj5GaKb0vNfEiiLCX69Kw==,type:str]
    oslo_messaging:
        auth:
            admin:
                password: ENC[AES256_GCM,data:W2bWdCRfYVF+FSaGHMKK1a4rACsyacM8e6yyxEAniDr0vdJ/PYCfqRjI8QKVrG7WxJNAVu+4+eArBzdB/WGhbA==,iv:5g3zP0xgyLCnLlXo6WBVPDxonttIvPtnRWC37OBY90M=,tag:rFbzfF/27IeWbJDj37xn8w==,type:str]
            masakari:
                password: ENC[AES256_GCM,data:FmrAPrTLq3bypiJxk9ZDqmGEm8wzsR6nhk4OsVdl2nK4xPcewoio3tWglbsCRxr4,iv:V9aZUz7zY1EsFRiNE/tVcVQ7bmJ8I+mF8AFuQNSpes0=,tag:wLeutBEVTinhCzUCg7cUCA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBySysyWHFRQ2RZQmV4YStT
            N3RhRmlyNnpKRytmQXFibDgvbWc5NE1CTlg4CkpHaWZtakNHbkFia1c4WFhqWllC
            bXNseW5CTEd0ZkZnVTVFVjh0aEtpb1kKLS0tIGdYMk5GdVAxQklPOTRjcHhMUW9L
            aXFKd0pTc1pRMGd5QlFpTHBLekhOUlUK5x8v1BW7pkR/BoZ19HDMj5+hdnIvvjcx
            Fxfymoyl9PyJJpEBYcfOtXOuf0zSD2PJq+T7wNjCntnPGVau59sWog==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cjaxalqu6gs9mev9w0u537793ql5t0gy3a6d9qn0265s49k9ss6q7flh4j
    lastmodified: "2026-08-04T16:42:36Z"
    mac: ENC[AES256_GCM,data:wQgb9cxHZIrHfx8bgnz/6ENEE3CqFsRob4ZC+lUmti21Vdp3Z+sX5QHtXXcXE/3ZV7BFWn4ownIjLfov7V/aVFVIyF1zv9nBtMSlpbmJ2TkpBdj4RPCcvVTa5IyTxHE99b38CCfyqHz570D7wVwq9yIB9g9D06QgW7L5Z8n9nn8=,iv:tl26opG6UL3O3VqdLxEhG5+D4S878uAtMxoqNPndazI=,tag:SKujHi0sRw+tnsPgkxMy9Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
