endpoints:
    identity:
        auth:
            admin:
                password: ENC[AES256_GCM,data:+XbMw+4n/s8t4wCZo6kMex5DjL7+xau12n5hc5s4o4DrjK6doL7ln3nkXPUeph1+/s7TO0XNEbwdv/Bx4ybipw==,iv:u7DzbLcDODaznX3lISM2X2iXND3N8scLHt2ZpthNITk=,tag:pItqk2W9R1tFDSWhBW6Atw==,type:str]
            neutron:
                password: ENC[AES256_GCM,data:Fq28MjiEJ6uMw9iWLdBeqFPW1pfewlxM7nwpHmAXaLLIVC+JPKvr+bc0soQcuXC4bOpyFK7nttiGMzlNUvJK3A==,iv:52zTj8ed6yalI0zjHUzwvEXS/r3yBO8RslNmmQZ9QxA=,tag:919UaZ14Zn0Qkf4Sm8ZbBQ==,type:str]
            nova:
                password: ENC[AES256_GCM,data:6GcR89ZMjsXEn2MYHenVXoEFyhQnwP4CJkv+SEG09sCZTSHWO6yL5QmSdwKZZsCCg8xxShI9VTvLToft5pokAA==,iv:LyiiVD/v0q0AjaFZxum9udh86OIW+kqbvsyfoFu3Mzg=,tag:YvaAx4JyPaTEOHK7b+/nhA==,type:str]
            placement:
                password: ENC[AES256_GCM,data:bcAtOLA1lsA6aAKSrvLhBM6NcDGZ2/hTlCCVMcEekdkhcHUZOElHr0FabqGjHRuDlD4YChfg0dpR8S2hUf1mZA==,iv:ueXRCKVpbEQrfSKB9D/vvIPF54nqI/OYzYccOoszku4=,tag:toqpOqxqEbwi0Sg8UvdbdQ==,type:str]
            designate:
                password: ENC[AES256_GCM,data:RaxtQtj8N2nmctHsZw8/KtzupIcW2x/toO9BOZCS5iZ/UQdQ1VuTRX9WFrV4ireK6bqagi2fHIADWW4GrWPK9g==,iv:d/TJ+yhRjzlJRhFngJpWLU+/OFKxyJ4d4sfhqDlP9HA=,tag:Eraw/ah8CSLLnO/C2Y0jjA==,type:str]
            ironic:
                password: ENC[AES256_GCM,data:/v7KVFl+yQmW7+0RVSUtjyyRJoKtaBsFTRdo78JtgXdow4/eDfY9C5hEGMau02CaIYjwAiFqvDxO7uudiJvD3g==,iv:ALm4JMY48fMVY3cUNTKTetCZo4Wb4W1PYsAKU61IS4Q=,tag:1gO0vMdOD50YbChyKNx2GQ==,type:str]
            test:
                password: ENC[AES256_GCM,data:SnLCEqVOcdz4nHvSPEKop6AffpdOfJ9QB42des83vmHq1kSRKbz3J5oJHR4/l15DIncE3bsbRcthm7S30NAeyQ==,iv:rMxazsELksQC1rl0dzqPtMpMc6OAnLJ9/+QnQtpenT4=,tag:xXSLUynQVSUgPpfJmurg1w==,type:str]
    oslo_db:
        auth:
            admin:
                password: ENC[AES256_GCM,data:f8VW2fh8msH/tO0pCVzkwD9oWXp0JPa0vLPe7grMZ3+KehHMz0GuyOns/eYwsWNASpv9Owjw8CoyEBn/kg2J2w==,iv:AjIK5PVfF1CcJgQcylAMr0FBKdepfzN8GEkPOqnuTY0=,tag:LwgnQVf6XVZ0l/bqvcYk6A==,type:str]
            neutron:
                password: ENC[AES256_GCM,data:1Yc6bsnr+dnT+uxK8iEsYltRTMz1mIrRLiGQGOhJZAH555LA83b+Ydrlc7cQJnsB/U/Tyhh5mWUjbJ2jn60+cQ==,iv:joJy7Y+5wEIhpFBNGdxz5b67X2QABrtSFBVKp4k7h0Q=,tag:z6x88KOhMyWeBTygK1Wa1Q==,type:str]
    oslo_messaging:
        auth:
            admin:
                password: ENC[AES256_GCM,data:C2O+Y2cTlcBHkvy58xYVAqpx+/LYdQQd1lCb1wt3tnnXO7qsUXt1kucpa5OgkJ9LczLm2T5SsnsBd3Fpfs+4xw==,iv:rEima7qPej/DuXQ70+M559H8W98v9z+bvNLZ9gCbleI=,tag:dMkWsQu8jB1ZWdRdTQP0Og==,type:str]
            neutron:
                password: ENC[AES256_GCM,data:S1nmuxA0hjmXhLIyle6rk0NrK65kW9LGQp06LMxrlN6VXTHz36BdygTI7+OkHD9gmrdeSVddWxiHFH7S1O55Bw==,iv:2ehCVBgUXFQLRhdnW3IUhNeYMzM3OP88hseu528sry0=,tag:Ej3+rGBgs2+9r7ZvNeQMtg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBOGpGd2ZnUWhpT1M2Q2g0
            WU9FT3hWMGhmWFg4TjgvNk16UkFhc1NFUENJCkg2NklhczgwSmhOU3FBTW40eUF6
            MkY0NDZabFRhaTQ5SHFNSEJ3MkVPYzAKLS0tIFdWR3VRS1hZcTNaMFR4WTVYRVZh
            UHIzMVZPZmtiRHd1OGdrSU0wY1g1RUUKxgwglFaf8VFln2+hL9CucTilwYE34i3O
            P14rJqE0Fw4SqazUE4u2gBdKCSqICCbvNubNTftiu8XuJhXWSiMYMA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cjaxalqu6gs9mev9w0u537793ql5t0gy3a6d9qn0265s49k9ss6q7flh4j
    lastmodified: "2026-07-25T14:50:40Z"
    mac: ENC[AES256_GCM,data:SZYjgvCL5GN9xhAgUJg17O2/W2bBgahpWaUuSS145+D8XRJtMtPydKE8IY5Mc4jftvgEj+bXF4fSwdWOEdqQvZ68aSm9ADf4/hVbkgHVi2+2L4IG+gU/bqgDFadbru9U+b354q11+6oZBqQ3Fl+GXELLwV9k2M3JSWTwyjSBs9Q=,iv:0tThP4xv6910a+BjH1dIzQ4WgLxYLFbrd25o7BG4Kc8=,tag:qXJekq4a5cM99TFfRt0Acw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
