endpoints:
    identity:
        auth:
            admin:
                password: ENC[AES256_GCM,data:ghS5Fjr/nZdJw0dopIAJ/dHPNPw3wBi+4utVR32s72dOrfCh5eUdat4/RkTmovyx+O1ZifGxIz2yw+YRoS2SiQ==,iv:UrHnG/B+s4w8N2e7Nn4DfOmHwxEZTgx4oZ1TpZjvhT0=,tag:RLj469l0Rf3Ir4m6E7Pu6Q==,type:str]
            nova:
                password: ENC[AES256_GCM,data:DXmlDrLu+2YgucVqZcsmJjPlHQD4tqem13GU5tdnYjHUBMdUyf9TZWzkLWMdFLkiu/QmsC2owOoBErC3CC4/Yw==,iv:x7zEZooyEcjBBACpZU1vy+KfeOl0EgE5XsAd67q9cN4=,tag:rZrpEUGz7uD3SQGqxHZFAg==,type:str]
            service:
                password: ENC[AES256_GCM,data:sik/ekvmjTDx9K4ibMuYouHhl6GZ1ALT3oPxUilQC+oEjAQ6pnIx1r/SDl5y3Dt4V5v1AvPhA1zMHipB5hdphg==,iv:0k7L+okkxLrlEbqi1jMHk/Ch3FEsLoY4uoCNECF6In4=,tag:I3DzeNhEwJklRUhze10taw==,type:str]
            neutron:
                password: ENC[AES256_GCM,data:iwdKi3nMa8tI3hMEBt8LL34cywe2Wv5XdKf/Jz2VrY0gXbb03eyZ3Dk6iVYmdbfhDNrxbdc7fUhMmA3ZvH9pQw==,iv:OXquYkRxr1tyb9v5iSxFYYi5ls9iia5/QJPSBgqmMIU=,tag:8j2mY1pt/6T3pDj9+cU7FQ==,type:str]
            ironic:
                password: ENC[AES256_GCM,data:S2ftEvUsQZtAA3/V1BKY+QixJfDnHNbP0+EDMAcJlbMe9Su99D87mk3vtOHS22k64a4f10Ftm++V/87irPWIXw==,iv:kuI/2/U6Xge5vVvU8zy/1Y955NNjcigBkEtZ9WGhmvI=,tag:dPTNFDMPEe0m7h/dvMLgLQ==,type:str]
            placement:
                password: ENC[AES256_GCM,data:9RoRnTZfbxGv65FxlGy9Zd7wlCMoRl5PZj+ofVbQt9XGhuJpkLlCR8gQcFlmzZ1+6qLTOkL9JZDeWaeLjhsF9A==,iv:/fVZ2ZRaed/cvRgw4RKzvBoIxF16hOLmVOPxu/ps8/4=,tag:0lJib8M0etAudVeWQVnCsQ==,type:str]
            cinder:
                password: ENC[AES256_GCM,data:IKKXu/JQd+nRINkxG0TMQNp/Gp0dfe+lJixsc+lqa7uTlFTvGmT2ga3Dx8+5Pq1N8mxfztXF0PVH12CGCrtFgw==,iv:GO0gtQKnwlJJhlasYaknV5Le9ybP2rTj70KnnunbVNI=,tag:9fJqHFrZL0KxMJKxPKryiA==,type:str]
            test:
                password: ENC[AES256_GCM,data:BrlkABVmjIm7O30fadEXqq7Jb3Jcdl8ngGdrHPSfqaU5p168JzDCF4dT+4WYzkcsOc6kLVVPWlo1SuiGYHqPUA==,iv:AVa40VmJ4El8PxQzTRh2uKjJJE0tN0z/lxpkwYe/hmw=,tag:CyCQ7w2Lc7/49eXwUzEJ2Q==,type:str]
    oslo_db:
        auth:
            admin:
                password: ENC[AES256_GCM,data:Ox6O3V2fWncRb8tLL3c9Xy6hCs3GCxkT2+Yn9d2sX9NgSrbE5JA/Fz1akShtZQMbAoUZBtNTxSHUmJXh3hS9FA==,iv:2Enlcc/19m0Z8mAR6D2xXkWR55aZQi7bcE9yaZKky0s=,tag:X81YLTaMHSC9jvyUNJ/OCw==,type:str]
            nova:
                password: ENC[AES256_GCM,data:LPPzjCXYfNhRo+L5eBmh5wE6PxHUpf4n2W9JDdMlySj/qLTVjYApdHQm4t5VFJzBYD6/taFZXBtJmO3KeTb7Ig==,iv:MFllcCU9rv7PVG5mpy62DeszWpyhHlDmUqyOSkAZua8=,tag:6Bs3/RmPyVPQovtBtj8b3A==,type:str]
    oslo_db_api:
        auth:
            admin:
                password: ENC[AES256_GCM,data:nAFMjtRBIP0JbjDDqMvWQe5yf3Z732znM3bxXgwzkmM+XEs2qN1tuCUSCAmOz9jM0+CRvZM6LRWkI/D8t21dhw==,iv:sIQSBTd+urP5b1k616tt350Dq/2GsCyEHCMZf87Fhjw=,tag:fQ+ZNc1zqgKXqVqcEO0i5w==,type:str]
            nova:
                password: ENC[AES256_GCM,data:arhY2UVbYMB06/4IZmzGXi/1DvzpztFiEOBG3TxSFk17ppTeGYFkjv+44rSo9RT95O6/iNDxIY0u9g7/yTwpUw==,iv:fTyeI/ACRwC/Ph3yqcJsJpErtwV5tbG/EnRN9Rc4Oeo=,tag:6GDRaMi2FDB/nv/1aN/iJg==,type:str]
    oslo_db_cell0:
        auth:
            admin:
                password: ENC[AES256_GCM,data:LYb0vPPAmEJE59eSNlymGHf39fUqBCZ+9as58FdTqfp+hUEzO38XD5ENIR/CGF3dcvzwQQe1Aqp+YzojaK78cw==,iv:V8I4nQgaoFcX46AdrA34VzWR+Zdl441MsmpLrCm8jPE=,tag:OPKwl0BVg0DfhQXtDDIfYA==,type:str]
            nova:
                password: ENC[AES256_GCM,data:zHd8A4KEwYMMZ3FkBvwn5cr118vOUeQWMRxvEYkT+Feqyaw3AjcA4Sb0DYC9201m8yMmGdAH2bEByxyexLtW1g==,iv:zwAwKBxWsVxZwgBxGfdD2bWKZvMK7a1McuMUWIDmmCA=,tag:U2u9JqYZoQEjDbQFd4jcHg==,type:str]
    oslo_messaging:
        auth:
            admin:
                password: ENC[AES256_GCM,data:kSJpVFErOZfX7mtp9lDpLrgviga+26+1lj6N9395AJ0J1ARzYW/sm7XzmGl/rePuwXauksS8Hy71vMt0BsznCw==,iv:fYOnnQtX23ojinpQZjnFI/ENnP4VYuJDy65HVYX9kwY=,tag:julNhMm68n6jcVPd8oFj/w==,type:str]
            nova:
                password: ENC[AES256_GCM,data:8rb2G2HqxTPjt2jwKQg0IzHRPBETMGR/0aLPDJqk6dI4bWWp+UMrj9WbgSoiBph6h1wMqEnZNCnTRmA8AefCvw==,iv:+hXrJ1h7G0BuTr3SjEIGVfXd+MB25HOnSJJgNrpzCiQ=,tag:y7xJkrCKZ05sXqVY7GhM3Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSdlMzMjNPR0JjbndKSStL
            ZVFITkdkM3FLeTFwSTdGRUU1YVp1MGxXalNJCi82NysxeWdiazZSSXNIaFNReHlC
            UU9rZGw4djRucm84RE83Smw3d1N2K3cKLS0tIHZJd244WFJldlNGcUd6S1FuRC8y
            cldMN2dzcjEvOWpOb2Z4bytGaVpNb00KmOZVncDMT+jdOBbLc7Rkx4H3WoKhHIXU
            +63jrd0w75qRihRkJuykojWGyKOmb5ASrw4Q4Qn0PgumNMajQmZ4wg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cjaxalqu6gs9mev9w0u537793ql5t0gy3a6d9qn0265s49k9ss6q7flh4j
    lastmodified: "2026-07-25T15:02:05Z"
    mac: ENC[AES256_GCM,data:4+tlGVWmmaiD8DlDPY8exjfZZCr3Yd12iW00S+AgRgV/3jkzOF17gAxhjpLWus7Cf1qUJalzS7Puw1xlliuz4PzbHoBHSey8m2CTaCZOBARR1kpafXX0eQs5k2BxuKvoQySU7Yew6LVX+O3B7/FheD3hiF6i5EUbGjcy8n/yoZ0=,iv:zIzUc39Q+HUdwY4e27Mqz/aTPig+jas3q9IQl0uRqjo=,tag:A7zxFiMPsBIdFFCtWYLWiw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
