endpoints:
    identity:
        auth:
            admin:
                username: ENC[AES256_GCM,data:UPf3x1g=,iv:fZH42dqV5rbeqGbLeMq3W8+Kqy/sZ+bURsHXYZpojWk=,tag:KbrFyS8MLU6QU+NS/99e7g==,type:str]
                password: ENC[AES256_GCM,data:eRn/5D0VjS6slpPwfj+mte8aJY6TsdqIH1BFTOEX/seUi6tp9vPJXrfvs7C6/k+RRFgOQABBNo/6MDAeiwD1sQ==,iv:wkmXRli+BoDMYF3i4HB6MpTG20f1q6hm9saKwjP0IwY=,tag:Ph8fSdH8v8+PAyus9T98FA==,type:str]
            octavia:
                username: ENC[AES256_GCM,data:0aRFLkE+yA==,iv:zB1tT+hO2k+/bqjioLO94aU/XMOtVaW7RZ714vqaXP4=,tag:OX49V1Mbz7+p8CX68cGjpg==,type:str]
                password: ENC[AES256_GCM,data:nWxz5ApzAa5Xjknsj4kMpviyUez2IIW0ltUT8GwB6AVXJIOYe+qTd4U3YhbAd8U2,iv:w2djr05CLCGu4jwG1tz4zlG3d0JwevctjvyKEMnKebY=,tag:mKTuYifm6dMAg1ddRa2KXQ==,type:str]
    oslo_db:
        auth:
            admin:
                username: ENC[AES256_GCM,data:bpbGCQ==,iv:mUUA0/ZAdj+u0rxhobz/t9eYY0L74xgPlHIoV6qsPUQ=,tag:QL3cJ13+8bU51y2IzMtIZA==,type:str]
                password: ENC[AES256_GCM,data:j/sgI4R+mD+5bvCkfmPyQ/tU48lC/UApDmbRufNSv/ZHW//uGI8GRaULo0SedwDAh+RG5QCZep81EsKcS65sxA==,iv:V9S/6xP1xHKkz56kpVjWeATtCOveFy3a3A297iMyGpc=,tag:r+gUqfLxpzmLOoSXE1YmjQ==,type:str]
            octavia:
                username: ENC[AES256_GCM,data:DbmKxXI41w==,iv:XNuWcsu4WMhMIUejOAUUtF0EOjWqZ+Hm0cj/16jy6B8=,tag:d9Dk3EHM1jvfDqDU8VDm6w==,type:str]
                password: ENC[AES256_GCM,data:KRt/+lGVSqfwuJel59Mti7ghaRunyA+aUPUItMneC3g+eYmIAK7yYmxhi6QWe+oE,iv:3bFimSqw8jvcUcUymMXLa7YAnAQ9PKSlZ/VltAr1KqY=,tag:7F2nqf+1Tv3U1DfTylRaMg==,type:str]
    oslo_db_persistence:
        auth:
            admin:
                username: ENC[AES256_GCM,data:Dfv4yA==,iv:RffltGg4Hhl4r5sxnMnvsMlgqKY3nFx+OtrmUyS4ZUo=,tag:ZMtA7AXVbvRekkFoY0i6UQ==,type:str]
                password: ENC[AES256_GCM,data:1LK/cLkfCtDrZgMZPPexyiRtMYidPxm4V5gk+F3dLtM3X7AeMxsOT4TrUHmI0ZRLxFnIakdW7DMOLlavrsemHA==,iv:0Axo60H2qAwViQPUXNblSF89QB0++QDnk+Kqt0MeKP0=,tag:qr3WED7owgM6cUZ9NTAqCQ==,type:str]
            octavia:
                username: ENC[AES256_GCM,data:l/to8H8ds54EWWxuwWt6J/dFsA==,iv:OgODKDeIj1vpSmNh2xJaoHzttsE2eoQoprkGd5jNq8g=,tag:NYWyFDr/Z5k26rjMDE2KDg==,type:str]
                password: ENC[AES256_GCM,data:R51IxaeTpG1tPkV9s2HCGDxIgNtR5xFyeAbY5cbSvZUuBDZl/BRyNfk3h+kSlMyN,iv:/Hd5OqgtnDniTuqatG8kqpHkJUSsh6rGEED/sp54+04=,tag:1YMu2wlcMcw9jfGypDqzrw==,type:str]
    oslo_messaging:
        auth:
            admin:
                username: ENC[AES256_GCM,data:vxVcFoxzhdk=,iv:wq/4GAaXCLGJYpQhTXS6IAEcN2U09nb6fGYm/+dh4ac=,tag:NHzeDdtww1/S/euJi6aPkg==,type:str]
                password: ENC[AES256_GCM,data:T6StpqruE2vC5pcFT0FmKtE15f5TFk9D9zw0D/5xjJgmWAaLZo7SkEejA7oj7+rP6GiNXZZSLZAYnlhJ/kS/hQ==,iv:0DpoAQm+qyPe/WCIFO+4ZQ5b7qn1ZlqcSsZ3bO0lN5w=,tag:N2kzWEOw6urfaBG1Eyrj5Q==,type:str]
            octavia:
                username: ENC[AES256_GCM,data:EFN274ovjA==,iv:7al5hBjEh7u2Y3mpqEBfRsGURrmnOAXQU3v+B0ujmq0=,tag:VNKzNuEBsB0n27nM6qV6qA==,type:str]
                password: ENC[AES256_GCM,data:jiyzRReRUFJKMsapSNI9KY1NZOii1KGSxWBdq4nrcl3EjO6tsh65XDXPZqWq3bMZ,iv:5kPQsnDksLVK/v5l3tcZ9QsI9kx2tyhRCESeKtpRdiI=,tag:hLfHH6CWOu4pjNxiNY8Qng==,type:str]
    oslo_cache:
        auth:
            memcache_secret_key: ENC[AES256_GCM,data:3kjTwORMwmpKpWAFXfFJyyO+Z7JbI+w9kXf1V21QJ4acilfszbuMo7NCe+0IYVxzdTI5Pscjd3wBuANsL+LNHw==,iv:SqJSZaGvRYDMs3VqAMoRH8X3fU6ICOhLaCrZCAzV+50=,tag:OMjz7r9heYNU3J8RxYt/JA==,type:str]
    valkey:
        password: ENC[AES256_GCM,data:Pido65+EG8e7DeRf45csYI1ANFJodFUKTHsJXbXE6qCiFQfbfQ0YO3LWTaZFqqwa,iv:Wqg8sbvi0/Z4fT6nGFlFqp6g5C4pKe6JQfEGEHfW4tU=,tag:cPhQAgW15MKfCKO69je0pg==,type:str]
conf:
    octavia:
        DEFAULT:
            transport_url: ENC[AES256_GCM,data:VrP7QaUAVjvnU5CjOlbVDqIeWcRm9S+zo5Y7ti0RkDZ5TiCEL1/Xz1vd/LVUYoriZZWIVDq9YzBy2FOLbtoC8eqqY08ViUrwM1NX4+NRTP+60vJWsBWJ40lek/sy6axsd3fZM5GVZ0n7opTrbdUfN8I7Qw==,iv:4TUO9OaiykewcipcfcPhyUzu3dGjs0GAw7sKpcdm0sI=,tag:8FFQtrBQnRo6qzSewY0TRA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvT3VkeWRPanBiUkRNRWFY
            VDNWQ1hrOXdqbnRSU1ZJYmViSVRyT282c1NvCkkzalZqNEcwL1crY2NKYjBRZ0VV
            VEVZMyt3Q1lIUHU1YzN6TFA0RkRmNzAKLS0tIEdIRklISkdFVDdqM3kzUG9NSVd5
            ZzJUQTNIa1ZRL25ySW0vdWg4dm1VaGsKIEzRVDL0pVQsG3ErG3t0dc21bywS97cM
            PvJG0x7FOYUpf72Nyjq9hy6SaGj0SwlEd7V9PDnfgZJ155nack7cuQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cjaxalqu6gs9mev9w0u537793ql5t0gy3a6d9qn0265s49k9ss6q7flh4j
    lastmodified: "2026-07-31T08:49:48Z"
    mac: ENC[AES256_GCM,data:ncdzAoaswVWyoBMQMqrDMH007aa/8LwS1qSgHNKBtLglx+/sUaslaAlQmBSpvI73YxW4CpPnvVwTVRYwjQKZKkkMuprMpfNMLcE7/w/NsRDw8gC9DVKdmqKDUk/2wbjstv6UyC1TYGb1plpYimvjkx70MA/K2xdF5aITVf7ildg=,iv:WZv4OTvHcfMBpDWyAcHhtiGlYTCrXErYLj8XRz/gKLY=,tag:6nnnl+onBBtEVc2+P4rpyg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
