endpoints:
    identity:
        auth:
            admin:
                username: ENC[AES256_GCM,data:jqPrDms=,iv:9RtzFRBW+SWOi7sz0wnfbh6fCzXoSMsV8WQqoyxbRo4=,tag:2GNK5hB/qEzcLsrbgcmcng==,type:str]
                password: ENC[AES256_GCM,data:ZIYiXGFkknO0HhhJHZvGbjyj/sx2VEWMyaIk6aOzzKkvPYut9J7lQYhNzAyJL7nAGyXTT5J2XpmWKy3ObL6gCg==,iv:tp3nK9kVak0Y3CTwW/u9F+7It8bb43tMOZF+GInJPFY=,tag:0KjATY5/1sw9y4segi/tsA==,type:str]
            octavia:
                username: ENC[AES256_GCM,data:8557qE3ARw==,iv:L1H5Fb1oQBnQvQpM1ZZ2I0kEcb6cHFO5tnWAEI+/htM=,tag:5CVdP2JgHLbc9v7E+aPM7g==,type:str]
                password: ENC[AES256_GCM,data:ysbD7j+VKq5ti+1AvaXbilR7I0Yg80Eg6leuHAapuoiAoRCsmYIhMYcpnEmLiChz,iv:yUogmUEbzqkSbXVBEQXPiP3Ij3NKiEVrq1yv5gQBCx8=,tag:XltiPC533+raUl29rS8Y0A==,type:str]
    oslo_db:
        auth:
            admin:
                username: ENC[AES256_GCM,data:aWHl8A==,iv:YwMXuQLBXwRM0pFMn8Lu7FouTEgulBDoOA11xqmZOZI=,tag:Q9FmdfztnhZC3muDaxxFhA==,type:str]
                password: ENC[AES256_GCM,data:G6lkhHau3LNbmKwlFtQ47KCXFjaiUnxcxGB/4xLihc3X4FTlPOnM1NvEhCIXu2XuimbZd1Uc4J9rm7VW9Tt5pQ==,iv:RH3KC6bnWJcedFz7wjpWVdK7NcOCXKF03B+W5bT27go=,tag:jLzMAqwDfWiZok0lrloY2g==,type:str]
            octavia:
                username: ENC[AES256_GCM,data:Uy5xiTh6KA==,iv:idmsj2z4jH334R3H1hMKZZWivIkBtKLn/74U0qHpz3Q=,tag:fLeXKzwcIZQDr1Gzp1fytg==,type:str]
                password: ENC[AES256_GCM,data:MNJKsihsJL17EY8D+xvc/9KBjGvCU6lPNqp/QRY3+mR9k/3CsLQWy6wBjWAEqUor,iv:V2X7adgWyKxnydj2qBeRXxp+pOu9b8utoUZZyAV6DCQ=,tag:FUHaf1EKpAjUfA0VH6Bu3w==,type:str]
    oslo_db_persistence:
        auth:
            admin:
                username: ENC[AES256_GCM,data:MDv4ug==,iv:+reD43ublRSoqzSAqJKmpZe/7+e6Ue2ut+V7vtpPUEU=,tag:o9aez2CFaKp5m5llvkBiXw==,type:str]
                password: ENC[AES256_GCM,data:8esPC0tnY5CCZeXJ6RbVmlXie2TUNccTqLrqhKjWumSAkl1b/z5h/t3B93iK8UkS6NrQqDgMliR8TBPJZLznNg==,iv:LakFEoWIQ8S0LCgCfhvYRvzTfksHZVB3wdT7oC6liZU=,tag:yz9WOSTpVByFhB3AqL8/Uw==,type:str]
            octavia:
                username: ENC[AES256_GCM,data:0DVkPN0A1ni62uNnqdUeSqqing==,iv:Fb/SQJPJSaiiRVOfTzPAnNudL7wGAQOexCsTfFEi0pM=,tag:W2UNqsbgSVJ4fDXXqtYoTA==,type:str]
                password: ENC[AES256_GCM,data:4UJP2IEVVWGvUaMPPTh3G3b2/UdtZMvKw6lTuck1+qkAa/tyzbBjeZ4jiF9PxSXu,iv:2P7Bsv0PcN+YftFiJFCluAOCrRCLfvPr30pDS33jVRA=,tag:NGrQ26nFQD0j+yBRvrt80w==,type:str]
    oslo_messaging:
        auth:
            admin:
                username: ENC[AES256_GCM,data:2R5OTzLqjy0=,iv:QXYhEi1AgGB18x0II4Ln/HDcplZ2Npg/XwgW6VVL3Ek=,tag:O5+ijVFc0835GaVt1PmXaQ==,type:str]
                password: ENC[AES256_GCM,data:1IMRIOmNlxvY91jOyo+MbYjr6G+wFtQFoBUrG9KfcQu+orPuG0QIEh+fHGCRp22E8owxhODBZp5qxOtNv5Eatw==,iv:RHFmhC7ET1EDizHfNaxWjAoM1RRV25CSgADeduQvGa4=,tag:fthmvRMuQ2EeSps+DMPI1w==,type:str]
            octavia:
                username: ENC[AES256_GCM,data:F+t5TN/hOw==,iv:pjc8MRV7+mrjpS527KW+sFlLczvER7sqqtQYIXrxO9w=,tag:h9P84DbQg5zwSf1Ac2WjdQ==,type:str]
                password: ENC[AES256_GCM,data:bia8DiHbE3lJ4ZTLVzs7ckkmythi2FyaG8g0eg2DgH0ps26Bg8aHgK3DjFcAQ/kR,iv:NdrCwZSfweVrcXVgeZfAajEqnn8FjfGHfBL7OSGPYNY=,tag:QfBKAn3JZpr9usBbg7KC8A==,type:str]
    oslo_cache:
        auth:
            memcache_secret_key: ENC[AES256_GCM,data:Jd8en0uD2PIbOdoAFupe+C2dfxClSh5CdJp8W2UPpXO2Q2l+gU7CcxV1yII8tE2aRo/EzrNNEp6dFOGsNPT6kw==,iv:yN+PQo3G/Vfs9iPh5phVxY6X5lM/IajLHmczfoP9m4A=,tag:DJjKBdGFzW2wxFaq9r5WyA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3eUVNd24xa1dTaVB6ZVVh
            cjFJa1cyaUF0bFVQRzBUTFZvU1hsU0YxeGhNCnJhaFhlN3pCbzFTcDJFQzNDcktS
            blh6YkVTL0l4K1huYjVKalBQMUNHL0EKLS0tIFpwMVJ0dDBYL051Y1c4R0Y4dDh0
            Nk5BUER1ZmIzY0lnWHJPNnVseEVtL0UKtnLZyutroh/hlCpEB4Ne4BZdC+/u04GF
            piz1qlNqHBjri189cC9rzSeEUrmnMO1mJX62Gl+P3fBRwk4JmALIVQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cjaxalqu6gs9mev9w0u537793ql5t0gy3a6d9qn0265s49k9ss6q7flh4j
    lastmodified: "2026-07-26T15:07:54Z"
    mac: ENC[AES256_GCM,data:cMXGhStqQ0A3gdIlPHtROywefpksHhbvb50Tes3jKaxv5+EL0VsLt0knzBW+IH0ZmdLs7NLRJIhL6LhTiqAn5q/itM7nVoSL+G66N73t0/SV9WIbRIBQvB2CiXe0+PpPNkNmQ0n6mjOUbii41xH4iUPYWsK6q/GmtA0wsAOyfZY=,iv:fl8MXDpdP0rnJwaapbmpB//zYMbzxSx3ChPWyYGRFWM=,tag:naDoQju/3yn2UbCfGThtqg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
