endpoints:
    identity:
        auth:
            admin:
                password: ENC[AES256_GCM,data:vmJe0z1GGVVUmqVr/13jVd1juz3op5rhjyyKzkevJrXOM5tCvwFekW/cqCsAjVXn/cZphF/sI+fdOkuwttdS/g==,iv:+jwN6v4XfGJCMOhlNugqSg+hLZBn9tYRW6agOsBfGj8=,tag:l33TYf7rcodz9mM2bb0pGA==,type:str]
            placement:
                password: ENC[AES256_GCM,data:V/kJNuKAE6dtR+gvra5ovWyD2Qa7f5m5wEcPuw+PC/0zYWAYaNDFRa0XFOlL3Zxw5eL1QFHf2jeQGlGxn2ULhQ==,iv:MH48V+7gOe4f5HRwggzVzaKCDWVZtrty8GYuj9qQ3ps=,tag:2hwb7ZDYDj/otnlL0Sl5PA==,type:str]
    oslo_db:
        auth:
            admin:
                password: ENC[AES256_GCM,data:JZJzkevgjAo94gqnM7+3mxATeX3YKzA4iTWI5MVV6PuFus1jRIKYVSfWYh/zJiFbHDvBCHSsIeTI+rRdBieC9A==,iv:FlBC0+xnM8yoBeh1wtRH1FcPPnfvlyVudhhcGMfIcT8=,tag:+6kGmXZaFkrRHFXkGMPh0Q==,type:str]
            placement:
                password: ENC[AES256_GCM,data:hb00OUsrxNm8whEfT1VDpQKkzPsW2pdOfh4pAx69H45DepBwvveNm0o/TJZ6Lx3hEvYCu2wJ/I3L9Jo/+OS9gw==,iv:A+aMawyH9U/vuqfJl5WIaIplekq3+zpenD+e5bDBRTM=,tag:dVjhgFTXeUeT+1OPmq1bGg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwR2pDU1hEVXFaWXdHM1NQ
            cFB1Q3VSc01SS2d4b3lKeDJrUXhjVkczL3lNCnNQdTNOUFNHbjJpMmk3TDY4aFJh
            YitHa0VrVkZBdWU0eVZjUmovMzE5dVkKLS0tIG1IN2JFRk5oTEV3TGFuUmJJQlhh
            RElPSDlFalNGZWtzYlNMODErV1Bqd0kKD5DCAsnAXjRjz7rbOcSNG8ZDanArjB/X
            A7LfQNxGPST5pJqPqTVshQW/tA74O838EeREhPZb3yr+sx495zPh7g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cjaxalqu6gs9mev9w0u537793ql5t0gy3a6d9qn0265s49k9ss6q7flh4j
    lastmodified: "2026-07-25T12:59:50Z"
    mac: ENC[AES256_GCM,data:Dw5xyez2UEfvQXJYeV7Wm8mGPB85V1TjS1nYQoB3s+mo/yEmjM6lGkOs5hilEYio0RbEESzdNWvf1CPoPd6iRrneLvWpUJjQ46asYuGLie6hg2lE0wLy9AUrfNO6/yE14TFCZM5ULVKxCElhFkeqgWSEoB4V7ZUnDjnEfVPedYs=,iv:5welJlB6CHObe23iYTFYo/PJV9i4SrA+kOnZ392zoWo=,tag:N8r9P75OHMvbDDy7rCG5uA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
