endpoints:
    powerdns:
        auth:
            service:
                token: ENC[AES256_GCM,data:qQn1GCc2divkig8e6/WfxuOravX6Us/mCRcUmIouDSE25oB6if8U1wremUBPztW/,iv:OII1k5Ui3HRknwhvAb3lAYxjIw694uToCn3zBB4qoP4=,tag:MHi0IkTdQwQNgZTK2HniJA==,type:str]
    oslo_db:
        auth:
            admin:
                password: ENC[AES256_GCM,data:5/qRthpF/oHldbrKekc9Vi2sd/wyQgUaQKpZv3J4OEyrEoMTjCOwR+DWeDP7cXdw0H9maJNxdh9aSJPaQ/7hLA==,iv:FYGPeRDzXcFGtgdRh1naRaecxb2q6Z1n2CEj2WXHNcE=,tag:OQ86MvOK2M4BePlMwIu7zQ==,type:str]
            powerdns:
                password: ENC[AES256_GCM,data:CWanoAojJdoWc6Dza6I0AAqlObScb0WJkpl0s7Bcf1k5u4grgfOz56sCSfOoDQ7g,iv:KElb95IglkbdxpO+scpVoUcHCwcWCi8tHwKsWx9aeaI=,tag:Xwts0m1jYhfZA4k9wQu+8Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5SElEZ2luWmhXL1ZjRnUw
            YW5RT2Nwa2JKUm5XQlVxOUJpQVRGR0FxVmtZCk5rTXVvU3JVeGh0amlvTUNiN2lq
            ZFA5TkJwSDRqdWp4dERuYnhnYjVhcHMKLS0tIGpONFBBQnorUG1OV0RST0tNbDc5
            MlQ4MEE0eDROMytZNGRnMnhSbTgwUDAKk4J9kjKS1maHUE/HthYUDxrV6bW4Fpb5
            VW65WXl5nqIfoMjFTsOKkHz27R9LZL2n+u0lKW/TaCNurcSjPjpN6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cjaxalqu6gs9mev9w0u537793ql5t0gy3a6d9qn0265s49k9ss6q7flh4j
    lastmodified: "2026-07-31T05:37:59Z"
    mac: ENC[AES256_GCM,data:qpxqRkelXBxxXrInLxPDWTbOz/s+AqjIsMfKOeQ6IddowLSPE+S22eRuib3Vc+B43J32dcLwxwPXi2lt1SFypRhmjz7fTTiPnCGS5sVegOaXgQu/xPXPNjIf7n7O3BVXK8oFY2LfhdEyJW7eJuLMM22JlQMSzI1QL8TUenZdeac=,iv:B92PY/Un3HuHyUl3AyVeDzyfuxxVrcWbg82SWyFQ4zA=,tag:YZW8YodF7Xg6WKDaN99GnA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
