apiVersion: v1
kind: Secret
metadata:
    name: project-facade-keystone
    namespace: openstack
type: Opaque
stringData:
    OS_AUTH_URL: ENC[AES256_GCM,data:qOd+aZCQjJhBVkUEMojtU+nlgWfuNTQkkwQkSoxH/y5OPQ4ED4tAxCZv1yHuak/DANgcxmP6tg==,iv:m6IRVvoP0UIiF/pIgPZPl3vx1KfyvkFtld+bN27syj8=,tag:LoJZj4GrgIxNfckwCQ/e/Q==,type:str]
    OS_USERNAME: ENC[AES256_GCM,data:j6XgZjTUzupTjCXvPzw=,iv:TNQMxFS469axrgqrSmHw9q5U2XrrjSIOCb6i/ZZO90U=,tag:WwEbCH89uNAPR7dr0CkLHw==,type:str]
    OS_PASSWORD: ENC[AES256_GCM,data:/d3MYR6qUa7RwuZ9vTCVUkCvjageToRwC+qMrHkzze4=,iv:nqcyhO1g+QQ9s7RnmL5KCy7KuZSRt1J5bKyoqJYv2go=,tag:HXslqb2nkgz/DirqQTuYng==,type:str]
    OS_USER_DOMAIN_NAME: ENC[AES256_GCM,data:NOdymspljA==,iv:SIwSJt7kHQ6+wHYOXaTRQxHn2wh+kEgqmiVFblQuzb0=,tag:cMxUX0UBYR7LCA74k9Evgw==,type:str]
    OS_DOMAIN_NAME: ENC[AES256_GCM,data:k6y4,iv:a8DYmsqrXd4tcFzbACSHtx2bFYPE7t+I3BdAG6GGL/A=,tag:O3ZqGCp7lldW/v4lOzvR3Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsQnRsVEZpQTh4L3o2WDVi
            ZTZvcENVTkJzaDRTQ0ZzZFhjeEw2NGpFeUhRCmZDSUc0N2pENGtkRmxhYTFqN29p
            dDZaOG5FOGVqNUtSZXUwTGpQc1F6OUUKLS0tIHF0V2p3Qmk4NTcxd3Mralo2YnBH
            a0t0Y0RVd1VGeklRVnRzMFFOL0JDNjAKPpcaOutUH143xXo8NUqR4NeeyFOcwY83
            AlppGr0/21t08OqMg6fE/2r4d9udVogMZ1bMcOnA0DSEMFpqF6xf0w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cjaxalqu6gs9mev9w0u537793ql5t0gy3a6d9qn0265s49k9ss6q7flh4j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-03T03:15:15Z"
    mac: ENC[AES256_GCM,data:XnyiomSJ93+7FVyRXlRC1CCKjDXfRbV0haGKhiAypAl1M/thk70oEhPzK++PjB516v7AnFE0wJpUAuByGpEcwj7p4LEnjFnzXfw2EF7ri1mzoCIfNfmO76pjhIPTEbnahFMjSk2drmyi6A9e2sKIi8QY3jQlmNrVi3vNCDhjMPo=,iv:/y8d97VMTHLBNd/LJrC/zWWFyo/4mjUebsKeZublMeo=,tag:9NAjskK3gZfFKCpJMOYUKw==,type:str]
    version: 3.13.3
