endpoints:
    oslo_messaging:
        auth:
            erlang_cookie: ENC[AES256_GCM,data:lCpmptp/DLvugzdTiwLUJoJRXwrLFWUrRXOx6MvQnMfheh5m1vdrAwC3Zb1OFEpDBgR7KHdlJk3//eMZHhN3KQ==,iv:Yj70uObDGCoc1vDfb3mkgl0sd4qcBZdq8zL9SveRiOQ=,tag:53FL8l1MEzUwy6W8clKLmQ==,type:str]
            user:
                password: ENC[AES256_GCM,data:3/8jxCYaAzAhHAoC0KvuSkrT2xdgP6mYWumTcYB/qjGOn8OTncQRKMDKyN5AehDkjdbjM9thq77lLh2+TZkiWg==,iv:iJKrgV0kJm8qLcx4kjNdbaP1qLeZO5E4GY6SidhjOzs=,tag:MfjisHgKxQqGyxNzkcWK4Q==,type:str]
            guest:
                password: ENC[AES256_GCM,data:x5cWGlG7mbVdy/vKBC7/pJSJ9DVsUa0KLBBJJaxWpOm/BjbCnuKU3uNP1+kLtp+BMO9JC3YHBIRkxGn1X3Uucw==,iv:bR4LGypyWsrJXjCzaiAuoG1AQ3BJIpanQHHtsQGTdK4=,tag:2POgUK9PQ52lN6RNDql9xA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSXhycmNNY2NUM3ROaTVu
            RnZYbDd6M0VuNTlwR3k2bFJibDVxUW5ibEFJCitJak5UV3JUMmZFZmZIY2hIeDNh
            WklBYTNkTDNEaFNPTXVtMWNBQitRRkkKLS0tIHdqblVQc0pKajVEM1JsUGtLOWps
            L2wwYW1jeWhydk8wRVhvU0xobEw5WDAKYh9zLnXsi5KMnG+tUOcEzwqWp8ksPL5D
            j3nrMKybG+FwwOhDQJ8WoPQW5pOQ7CSuY9uwUNxdENhDEBjCCoySVQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cjaxalqu6gs9mev9w0u537793ql5t0gy3a6d9qn0265s49k9ss6q7flh4j
    lastmodified: "2026-07-25T11:54:52Z"
    mac: ENC[AES256_GCM,data:S3UoRxi0BS0dDoizdzCWBVUe/8TVhTl8cD41LEuh71c4hmoFX0tRPVW5Ly026r0m20hrgMfGiawwlzI8hCRYcd5NeO1B6cskxTeCqI0Ps6/O0gC5co3DmJSaOQLhVSakrydhp97klzcHN6WKH9rDjuMVQjAxNd/L2Jg06GwwHEI=,iv:mqZFF0ICQzL7+1ZpJddnYFFP6Snjj7ELU5KUBR4CBUU=,tag:XQiS/s2RfA9SSegiAD8WNw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
