#ENC[AES256_GCM,data:v7VdbzYMYAktKVsEAqvf6L+C2D+zipnVnUsaqsVRCxIcEkYIBMu4OqCq7Q+A5H2LEfjc16St8NqtZnkLdQys7Q==,iv:R8AwS+hQsvg76kBkutYA6xUtk9xryw56ly8DXXLc3Qc=,tag:TQfFbUJAR3v2EbZgkL6Ytw==,type:comment]
#ENC[AES256_GCM,data:oA4OBt/KtUcC00vvZbdGlmfXOqLm5xPixbXDDGoiWYzY8WueW75qU4VC,iv:nW3zJnO3KWpvtSoOK+Gr5bF94saCwrtsJYCfL258YGQ=,tag:SFLRkKdaM3HXV7iQiF5gwA==,type:comment]
pod:
    replicas:
        skyline: ENC[AES256_GCM,data:bQ==,iv:sN6Dpl81Ym2wyx9v5kJguoRluTu+I4L6/lxkUcRhaPs=,tag:vvwW18YrpydfqKq8HQeS6A==,type:int]
    tolerations:
        skyline:
            enabled: ENC[AES256_GCM,data:fR57kA==,iv:d2pNGgJDu1Og2MgXGMOoCOeuIlfUb0sONjLvIGoSBTI=,tag:ULIbGADsnLTDdRlxLqPpXQ==,type:bool]
    affinity:
        anti:
            type:
                default: ENC[AES256_GCM,data:CWU1JduHmkpljTc15snUGQydcWx+mEVrukKYF3iOnmQH+RRLQBXlX0g69GJcdQ==,iv:0A561Q7uSSeTZsbkO0jvpu9KlUY/NR7BGPkoyhpkya0=,tag:XP5P+VIjDeLlbistHq5AnQ==,type:str]
            topologyKey:
                default: ENC[AES256_GCM,data:7s5CPzneBdAv4LCuHiHeKxCUipCaqA==,iv:hPQtpzafwY4UglYVcI5DCubfJUatMCzrjLYp8RxcVVo=,tag:xT6rkWHwKo/cmHfg1dvjKg==,type:str]
    resources:
        enabled: ENC[AES256_GCM,data:LQ9Hng==,iv:N/1WVVZaqfo6rKcBx61TwA4thU46ZVKbLmieutOSstQ=,tag:eGAXX+kadWn9rzGYYSqxvg==,type:bool]
conf:
    skyline:
        default:
            debug: ENC[AES256_GCM,data:0ml3V6Y=,iv:FdEetmbrQUSZiigvjcjC9pwBDu42GdGjsQZobVIspes=,tag:r4lbQdcWgyFqBpebtJjPsg==,type:bool]
            secret_key: ENC[AES256_GCM,data:DI6e5c7/uM5en/d4eGzzxgJf/aciz0dTiC47qf15qdGSLV1bW4atNr2w2cn2+h7ior3jfEmss6HTFQdphG4A4Q==,iv:mZ1PbpS8fOmbZbp/r20RNsHAyKtQ2Lhf+xQcG9SnMHM=,tag:cYc9r8QAg3znc7zSRV47PQ==,type:str]
        openstack:
            interface_type: ENC[AES256_GCM,data:upvouPQvnv0=,iv:NM2mQzESC+XmlWZeh7ueqH2FCGp5OTlI6yFz4i9Fx2U=,tag:O0zSMTEHmXyNao7tNe+lZA==,type:str]
            default_region: ENC[AES256_GCM,data:4b2xZ397au2T,iv:jbY3QfV4Fhr5zEw/+OBcD4K/SW4r/4hI7e+VU3BR2fE=,tag:cXo7TjgFhhO+ByncuxA4XA==,type:str]
endpoints:
    identity:
        auth:
            admin:
                region_name: ENC[AES256_GCM,data:QyhxhUN1UqYd,iv:muaY1H6OIbsSmYJ2I8gznpFgfQpbh2SGkvf8PLofSvY=,tag:1dX8t0D7qOA+ZqA1io//TA==,type:str]
                project_name: ENC[AES256_GCM,data:05ZWjfw=,iv:oEJ535TlShipAHxIhm9qCJh5kOxpppfWu25EoXdrM+U=,tag:/aV46pPYOhNEneaTcDQSGQ==,type:str]
                password: ENC[AES256_GCM,data:5fqgyBKkfoYDwKmQ7s6go/FNqboOT9asXITQbYbZKsS387R4q5E07sC0xY8a40RPPNKPsSN03mu9rspr9hj/cw==,iv:2BMBZXZBkkDsyMrGMuaK6TQ2i8+2o4bDrL+Z6ER6KUw=,tag:n+GuQAZgO/oEjesmKotGzg==,type:str]
            skyline:
                region_name: ENC[AES256_GCM,data:90Bevn0KKtTb,iv:d65cAZyPrkP29ckTYXsyfrwNX3/01nrVh6MMcRYGhX0=,tag:o89lPVqnijh3P0uAKA+XJw==,type:str]
                project_name: ENC[AES256_GCM,data:pfW+/hI=,iv:IwWnXzH0K8kgLR/v+AL5EtaZdP5ijmPW5DAgm/Wxm70=,tag:JCAEXXGN4aWjp5OG7MCF/g==,type:str]
                password: ENC[AES256_GCM,data:INNpt6y33I0TPrz/c9+OSQx/PHV1K5YdhdHIG4det7EPbT5nyCwAOMsC7Z/c5QHU,iv:L3oGobRtKQUlSVhrAw5otVxPCIJWf3rKiXv3J91pffY=,tag:3legppgAgkeipvIlLqU0PQ==,type:str]
    skyline:
        host_fqdn_override:
            public:
                host: ENC[AES256_GCM,data:aKmL/8bxuAe7PnSjEIk2XDF0iw==,iv:X6i0zQP+MelVX/XyON9d3fMFsfTIn72uevrM4QHGdwA=,tag:UmW4z8a7epzoGcDRnF+/7A==,type:str]
        scheme:
            public: ENC[AES256_GCM,data:lUN++Zg=,iv:BWtbaFPsGQwKuBwltX1hAv18IqB52BTJXDGHB/YbyEQ=,tag:wHbqT8Ls7gPy4zKbgjb6bw==,type:str]
        port:
            api:
                public: ENC[AES256_GCM,data:Bjga,iv:H8CBZyYZ5KjVhxGdtkDKqn3OXpL+lwUS9a9fbC/kDvE=,tag:OsGFOLr2K1zu0BfxzE+eCQ==,type:int]
    oslo_db:
        auth:
            admin:
                password: ENC[AES256_GCM,data:Roj/0fCMa93nCxEJvVWNq8PVCvPLFw9wDPVBBBk+S21QINc1fHdaLmJhoSvsA0QhUvuR62oXCWrypxzbIZ7EJA==,iv:isYgfC8x6Y8cUXILNsWSWQY0IbH3PUp7FncwYkq/cwU=,tag:znOaHypwSg9bM23zRW1ByQ==,type:str]
            skyline:
                password: ENC[AES256_GCM,data:4vb7g3eqCjCYxXU1ihemtjWwv+njwHxbfGPJTemt9dIIGMQHwGuZjHfk5Hk54p/xk4S1SgAehq0Jx+KG7+qUXQ==,iv:x6YspnD5iAbwdFxUpXepNu7I45VXjFAbgI0JaDTX0s8=,tag:6ap3tDldbwT71a4yXt+JCA==,type:str]
manifests:
    ingress: ENC[AES256_GCM,data:xFpyScM=,iv:bxxdSoy+8NWxGNptGqwH1TqGMRvP119JcKfUjd0EYKo=,tag:VU0IqwOaep9WxaaZl4BePA==,type:bool]
    service_ingress: ENC[AES256_GCM,data:PlpYppE=,iv:LIrSeb3BRYHIxMOeWdZ8CGjo+f0ktWG39LshiN+85nc=,tag:jytr8z5zYLPVg4knR5wNuQ==,type:bool]
extraObjects:
    - apiVersion: ENC[AES256_GCM,data:c+h9qj/7T8kf,iv:F6G0TfaWPZl0wj2TYOEIISKLu8iUthilB1ScbqwW/ak=,tag:toivOMdfhGrNoR2u8cMTsQ==,type:str]
      kind: ENC[AES256_GCM,data:mWdsgt7gzOHHAFe24wa/IR1Gyw==,iv:8mrylzrnQi7n8iYFq09R8wM7bKoZmQabHysv5f5DzNA=,tag:1TUcVA+lc4qb9u32wOscpw==,type:str]
      metadata:
        name: ENC[AES256_GCM,data:uApNKIvsow==,iv:458ilB+09GlEz8R7MUuJ34bObupZGvMjcojPvvPO1aU=,tag:orDVl7+g03AAKFkTWLhVlQ==,type:str]
        namespace: ENC[AES256_GCM,data:oocacgEEnqUn,iv:kmKi84A9ZJ2dHif4uV2ygo0fnwdf1VtbC4eQWBzWrWw=,tag:IcUirByYn0NzN0uDODpG9Q==,type:str]
      spec:
        minAvailable: ENC[AES256_GCM,data:Kw==,iv:HLd9c2tXON5qAqsGlO1lDqx6vBBEVvoDp++YErbmJh4=,tag:CjWNjxSa5QTb6mZ1O2dvWQ==,type:int]
        selector:
            matchLabels:
                application: ENC[AES256_GCM,data:KhYsIdARNA==,iv:6N6NhnbZW33XcKlQ3ZWmizVFtrHRVFmwczN99afowu8=,tag:QVVxwhtUQ6xnurXRIg7u4A==,type:str]
                component: ENC[AES256_GCM,data:ZAgqqslScw==,iv:LF/BWP/zmuOafyKJDW76Vvm52HxNjs3k6s4ypgjLiOk=,tag:XfhuZQVACY6/+w9eUl75yw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4V0VNNzJKaHpkUzNKVHJJ
            UjdDYnBMSFFLV0NjYUIvQzNoK1Z2Z3F1OXhrCkNKY0tQZnFMTCtGcXBCZFRrRFhB
            eDdMV2FDZVlYalNLSXVwOFFXVkhlZnMKLS0tIG9oS3dxS3JOZ2hEaUt1ZDhuV0xN
            REh2cVFHeno5ZlBsZW1hZDYyc0tJTVUKzGXsDxXnbD/GmDQ7qOLgl8N3Xltyz/Xu
            JSXw3XJkJ/KUxml8PzSYWbx9qexCCrdHCjgB7gUIiylFRcWpdhb8hw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cjaxalqu6gs9mev9w0u537793ql5t0gy3a6d9qn0265s49k9ss6q7flh4j
    lastmodified: "2026-07-26T11:34:56Z"
    mac: ENC[AES256_GCM,data:7agQR+Rawhd4XBsD7YRm0Wq+DP1trboViu+jdB8KW6hY4lPNlvMOn6WzB1A7r/tdA4Tz1WWETbj9SrfKix9NLA8+Sg71pY9Q3ezNj3tUYlsbesKdNTod6+v4ox6mCJaHkMoAJoZmnkc0k5O4kO8JkGBX9CYKBqWZ0ILF+lW3ajY=,iv:T3LDyilunqA421c9k1XfRn1lzZza9u9uJsOrs8s55Uc=,tag:m/hvznt/FuAZxItPN3VPwQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
