apiVersion: v1
kind: Secret
metadata:
    name: telemetry-harbor-push
    namespace: openstack
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:dkIV+DN/Ib96SKkxU0ElCuMETlM38rrMb/zDvfqnu0udwHM/1AmpU7in7vqbTO5hmi+r6TUQOu1W/b6Cmjwa73z3nzvzN+FBU2xoO9YgrTi7bbnjXYFjPFH1aOyYv4r6/lah7SKZxbZHCQbiYZNGzUccAB+HXKoym+Y3u/iySyIRDFB36KSx2L3gAUSt/MMz4N5mT+pQlkdvqcnKWhr3Xc8fcIkxWOi1qmuY6iLMVUmqXkIl3EJBHj6K9MJJKfeU9l9X3+oowIUtxTy5wElG3wwdywjTa7OPAbAJQA==,iv:0Y8ogjc7B1rH/JrNu/5RvyufTaF6UkV5uLcj0JGwpns=,tag:o88riDY6XMOneSJOFYkQiA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZU1wYjRZS3pmTThGNXFJ
            WEdXdHFuU21vSmF1WVFOdWVZQ2pUU0ZrWHhjCmgrYU41a1JjeFpWeXRxSFdQU1JC
            RzhUZm1iZThiM2ZjY3AwY09EYjF3RmsKLS0tIFBlRXpBOXpORzk5SXdNdkNyWFJH
            ZTJZbC9TNEJDVHdHYnpNQ2w1L29OTncKE2s9Gdqzax0ggV8qdshSxaFVExHQwrgO
            pG4m9DedL9T/M5TbPAdtNJFOK4/jj49NyrvtqAvFlPJOzXaP5RwHaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cjaxalqu6gs9mev9w0u537793ql5t0gy3a6d9qn0265s49k9ss6q7flh4j
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T10:11:47Z"
    mac: ENC[AES256_GCM,data:V4C5C/9dTpUrU6SpotCUp4I2L2YJEYiuLBVDZgZQ8wniWYw8zF6tcBbeHGxrArDYB8nCOyq6rD2Tn9WvZnlUs5P4g8MoaPrfSzZPUcmQeJIknf9fv+W5DPF9IFVdZbWsqw3KPWI+1UHjQdzdcxyrbRzGeezWMy6scp5zA16n9fs=,iv:+Zo96myzUPl3Hbnz6xrNrGrslP1HsK9FqLSC/lkKNhE=,tag:0OqeopOLBuVKkuk//e3Wdg==,type:str]
    version: 3.13.3
